// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: hashgram/p2p/v1/blob.proto

package p2ppb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BlobManifest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Manifest format version. 1.
	Version uint32 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	// Total blob size in bytes.
	Size uint64 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	// Chunk size in bytes. Every chunk but the last is exactly this long.
	ChunkSize uint32 `protobuf:"varint,3,opt,name=chunk_size,json=chunkSize,proto3" json:"chunk_size,omitempty"`
	// BLAKE3 hash of each chunk, in order.
	Chunks [][]byte `protobuf:"bytes,4,rep,name=chunks,proto3" json:"chunks,omitempty"`
	// Declared MIME type. For encrypted blobs, the MIME of the ciphertext
	// container, "application/octet-stream".
	Mime string `protobuf:"bytes,5,opt,name=mime,proto3" json:"mime,omitempty"`
	// Whether the chunks are client-side encrypted.
	Encrypted     bool `protobuf:"varint,6,opt,name=encrypted,proto3" json:"encrypted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlobManifest) Reset() {
	*x = BlobManifest{}
	mi := &file_hashgram_p2p_v1_blob_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlobManifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlobManifest) ProtoMessage() {}

func (x *BlobManifest) ProtoReflect() protoreflect.Message {
	mi := &file_hashgram_p2p_v1_blob_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlobManifest.ProtoReflect.Descriptor instead.
func (*BlobManifest) Descriptor() ([]byte, []int) {
	return file_hashgram_p2p_v1_blob_proto_rawDescGZIP(), []int{0}
}

func (x *BlobManifest) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *BlobManifest) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *BlobManifest) GetChunkSize() uint32 {
	if x != nil {
		return x.ChunkSize
	}
	return 0
}

func (x *BlobManifest) GetChunks() [][]byte {
	if x != nil {
		return x.Chunks
	}
	return nil
}

func (x *BlobManifest) GetMime() string {
	if x != nil {
		return x.Mime
	}
	return ""
}

func (x *BlobManifest) GetEncrypted() bool {
	if x != nil {
		return x.Encrypted
	}
	return false
}

type BlobGetManifest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cid           []byte                 `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlobGetManifest) Reset() {
	*x = BlobGetManifest{}
	mi := &file_hashgram_p2p_v1_blob_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlobGetManifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlobGetManifest) ProtoMessage() {}

func (x *BlobGetManifest) ProtoReflect() protoreflect.Message {
	mi := &file_hashgram_p2p_v1_blob_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlobGetManifest.ProtoReflect.Descriptor instead.
func (*BlobGetManifest) Descriptor() ([]byte, []int) {
	return file_hashgram_p2p_v1_blob_proto_rawDescGZIP(), []int{1}
}

func (x *BlobGetManifest) GetCid() []byte {
	if x != nil {
		return x.Cid
	}
	return nil
}

type BlobManifestResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Manifest      *BlobManifest          `protobuf:"bytes,2,opt,name=manifest,proto3" json:"manifest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlobManifestResult) Reset() {
	*x = BlobManifestResult{}
	mi := &file_hashgram_p2p_v1_blob_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlobManifestResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlobManifestResult) ProtoMessage() {}

func (x *BlobManifestResult) ProtoReflect() protoreflect.Message {
	mi := &file_hashgram_p2p_v1_blob_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlobManifestResult.ProtoReflect.Descriptor instead.
func (*BlobManifestResult) Descriptor() ([]byte, []int) {
	return file_hashgram_p2p_v1_blob_proto_rawDescGZIP(), []int{2}
}

func (x *BlobManifestResult) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *BlobManifestResult) GetManifest() *BlobManifest {
	if x != nil {
		return x.Manifest
	}
	return nil
}

type BlobGetChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cid           []byte                 `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	Index         uint32                 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlobGetChunk) Reset() {
	*x = BlobGetChunk{}
	mi := &file_hashgram_p2p_v1_blob_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlobGetChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlobGetChunk) ProtoMessage() {}

func (x *BlobGetChunk) ProtoReflect() protoreflect.Message {
	mi := &file_hashgram_p2p_v1_blob_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlobGetChunk.ProtoReflect.Descriptor instead.
func (*BlobGetChunk) Descriptor() ([]byte, []int) {
	return file_hashgram_p2p_v1_blob_proto_rawDescGZIP(), []int{3}
}

func (x *BlobGetChunk) GetCid() []byte {
	if x != nil {
		return x.Cid
	}
	return nil
}

func (x *BlobGetChunk) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

type BlobChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlobChunk) Reset() {
	*x = BlobChunk{}
	mi := &file_hashgram_p2p_v1_blob_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlobChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlobChunk) ProtoMessage() {}

func (x *BlobChunk) ProtoReflect() protoreflect.Message {
	mi := &file_hashgram_p2p_v1_blob_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlobChunk.ProtoReflect.Descriptor instead.
func (*BlobChunk) Descriptor() ([]byte, []int) {
	return file_hashgram_p2p_v1_blob_proto_rawDescGZIP(), []int{4}
}

func (x *BlobChunk) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *BlobChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// Ask a provider whether it holds a blob, and how much of it.
type BlobHas struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cid           []byte                 `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlobHas) Reset() {
	*x = BlobHas{}
	mi := &file_hashgram_p2p_v1_blob_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlobHas) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlobHas) ProtoMessage() {}

func (x *BlobHas) ProtoReflect() protoreflect.Message {
	mi := &file_hashgram_p2p_v1_blob_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlobHas.ProtoReflect.Descriptor instead.
func (*BlobHas) Descriptor() ([]byte, []int) {
	return file_hashgram_p2p_v1_blob_proto_rawDescGZIP(), []int{5}
}

func (x *BlobHas) GetCid() []byte {
	if x != nil {
		return x.Cid
	}
	return nil
}

type BlobHasResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HasManifest   bool                   `protobuf:"varint,1,opt,name=has_manifest,json=hasManifest,proto3" json:"has_manifest,omitempty"`
	ChunksPresent uint32                 `protobuf:"varint,2,opt,name=chunks_present,json=chunksPresent,proto3" json:"chunks_present,omitempty"`
	ChunksTotal   uint32                 `protobuf:"varint,3,opt,name=chunks_total,json=chunksTotal,proto3" json:"chunks_total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlobHasResult) Reset() {
	*x = BlobHasResult{}
	mi := &file_hashgram_p2p_v1_blob_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlobHasResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlobHasResult) ProtoMessage() {}

func (x *BlobHasResult) ProtoReflect() protoreflect.Message {
	mi := &file_hashgram_p2p_v1_blob_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlobHasResult.ProtoReflect.Descriptor instead.
func (*BlobHasResult) Descriptor() ([]byte, []int) {
	return file_hashgram_p2p_v1_blob_proto_rawDescGZIP(), []int{6}
}

func (x *BlobHasResult) GetHasManifest() bool {
	if x != nil {
		return x.HasManifest
	}
	return false
}

func (x *BlobHasResult) GetChunksPresent() uint32 {
	if x != nil {
		return x.ChunksPresent
	}
	return 0
}

func (x *BlobHasResult) GetChunksTotal() uint32 {
	if x != nil {
		return x.ChunksTotal
	}
	return 0
}

// Upload: the manifest first, then chunks. Either may be refused for quota.
type BlobPutManifest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Cid      []byte                 `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	Manifest *BlobManifest          `protobuf:"bytes,2,opt,name=manifest,proto3" json:"manifest,omitempty"`
	// Who is uploading, so quota is per identity. Raw ed25519 device key.
	UploaderPubkey []byte `protobuf:"bytes,3,opt,name=uploader_pubkey,json=uploaderPubkey,proto3" json:"uploader_pubkey,omitempty"`
	Timestamp      uint64 `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Signature over cid, uploader_pubkey and timestamp under the
	// "blob-upload" purpose.
	Signature     []byte `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlobPutManifest) Reset() {
	*x = BlobPutManifest{}
	mi := &file_hashgram_p2p_v1_blob_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlobPutManifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlobPutManifest) ProtoMessage() {}

func (x *BlobPutManifest) ProtoReflect() protoreflect.Message {
	mi := &file_hashgram_p2p_v1_blob_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlobPutManifest.ProtoReflect.Descriptor instead.
func (*BlobPutManifest) Descriptor() ([]byte, []int) {
	return file_hashgram_p2p_v1_blob_proto_rawDescGZIP(), []int{7}
}

func (x *BlobPutManifest) GetCid() []byte {
	if x != nil {
		return x.Cid
	}
	return nil
}

func (x *BlobPutManifest) GetManifest() *BlobManifest {
	if x != nil {
		return x.Manifest
	}
	return nil
}

func (x *BlobPutManifest) GetUploaderPubkey() []byte {
	if x != nil {
		return x.UploaderPubkey
	}
	return nil
}

func (x *BlobPutManifest) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *BlobPutManifest) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type BlobPutManifestResult struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Accepted bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Reason   string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	// Which chunks this provider still needs, so an interrupted upload
	// resumes rather than restarts.
	MissingChunks []uint32 `protobuf:"varint,3,rep,packed,name=missing_chunks,json=missingChunks,proto3" json:"missing_chunks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlobPutManifestResult) Reset() {
	*x = BlobPutManifestResult{}
	mi := &file_hashgram_p2p_v1_blob_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlobPutManifestResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlobPutManifestResult) ProtoMessage() {}

func (x *BlobPutManifestResult) ProtoReflect() protoreflect.Message {
	mi := &file_hashgram_p2p_v1_blob_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlobPutManifestResult.ProtoReflect.Descriptor instead.
func (*BlobPutManifestResult) Descriptor() ([]byte, []int) {
	return file_hashgram_p2p_v1_blob_proto_rawDescGZIP(), []int{8}
}

func (x *BlobPutManifestResult) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *BlobPutManifestResult) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *BlobPutManifestResult) GetMissingChunks() []uint32 {
	if x != nil {
		return x.MissingChunks
	}
	return nil
}

type BlobPutChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cid           []byte                 `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	Index         uint32                 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlobPutChunk) Reset() {
	*x = BlobPutChunk{}
	mi := &file_hashgram_p2p_v1_blob_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlobPutChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlobPutChunk) ProtoMessage() {}

func (x *BlobPutChunk) ProtoReflect() protoreflect.Message {
	mi := &file_hashgram_p2p_v1_blob_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlobPutChunk.ProtoReflect.Descriptor instead.
func (*BlobPutChunk) Descriptor() ([]byte, []int) {
	return file_hashgram_p2p_v1_blob_proto_rawDescGZIP(), []int{9}
}

func (x *BlobPutChunk) GetCid() []byte {
	if x != nil {
		return x.Cid
	}
	return nil
}

func (x *BlobPutChunk) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *BlobPutChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type BlobPutChunkResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlobPutChunkResult) Reset() {
	*x = BlobPutChunkResult{}
	mi := &file_hashgram_p2p_v1_blob_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlobPutChunkResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlobPutChunkResult) ProtoMessage() {}

func (x *BlobPutChunkResult) ProtoReflect() protoreflect.Message {
	mi := &file_hashgram_p2p_v1_blob_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlobPutChunkResult.ProtoReflect.Descriptor instead.
func (*BlobPutChunkResult) Descriptor() ([]byte, []int) {
	return file_hashgram_p2p_v1_blob_proto_rawDescGZIP(), []int{10}
}

func (x *BlobPutChunkResult) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *BlobPutChunkResult) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// Replication health, as a node reports it for a blob it holds.
type BlobHealth struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Cid            []byte                 `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	TargetReplicas uint32                 `protobuf:"varint,2,opt,name=target_replicas,json=targetReplicas,proto3" json:"target_replicas,omitempty"`
	KnownReplicas  uint32                 `protobuf:"varint,3,opt,name=known_replicas,json=knownReplicas,proto3" json:"known_replicas,omitempty"`
	// "HEALTHY", "DEGRADED", "LOST".
	Status        string   `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Providers     []string `protobuf:"bytes,5,rep,name=providers,proto3" json:"providers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlobHealth) Reset() {
	*x = BlobHealth{}
	mi := &file_hashgram_p2p_v1_blob_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlobHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlobHealth) ProtoMessage() {}

func (x *BlobHealth) ProtoReflect() protoreflect.Message {
	mi := &file_hashgram_p2p_v1_blob_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlobHealth.ProtoReflect.Descriptor instead.
func (*BlobHealth) Descriptor() ([]byte, []int) {
	return file_hashgram_p2p_v1_blob_proto_rawDescGZIP(), []int{11}
}

func (x *BlobHealth) GetCid() []byte {
	if x != nil {
		return x.Cid
	}
	return nil
}

func (x *BlobHealth) GetTargetReplicas() uint32 {
	if x != nil {
		return x.TargetReplicas
	}
	return 0
}

func (x *BlobHealth) GetKnownReplicas() uint32 {
	if x != nil {
		return x.KnownReplicas
	}
	return 0
}

func (x *BlobHealth) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *BlobHealth) GetProviders() []string {
	if x != nil {
		return x.Providers
	}
	return nil
}

var File_hashgram_p2p_v1_blob_proto protoreflect.FileDescriptor

const file_hashgram_p2p_v1_blob_proto_rawDesc = "" +
	"\n" +
	"\x1ahashgram/p2p/v1/blob.proto\x12\x0fhashgram.p2p.v1\"\xa5\x01\n" +
	"\fBlobManifest\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x04R\x04size\x12\x1d\n" +
	"\n" +
	"chunk_size\x18\x03 \x01(\rR\tchunkSize\x12\x16\n" +
	"\x06chunks\x18\x04 \x03(\fR\x06chunks\x12\x12\n" +
	"\x04mime\x18\x05 \x01(\tR\x04mime\x12\x1c\n" +
	"\tencrypted\x18\x06 \x01(\bR\tencrypted\"#\n" +
	"\x0fBlobGetManifest\x12\x10\n" +
	"\x03cid\x18\x01 \x01(\fR\x03cid\"e\n" +
	"\x12BlobManifestResult\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x129\n" +
	"\bmanifest\x18\x02 \x01(\v2\x1d.hashgram.p2p.v1.BlobManifestR\bmanifest\"6\n" +
	"\fBlobGetChunk\x12\x10\n" +
	"\x03cid\x18\x01 \x01(\fR\x03cid\x12\x14\n" +
	"\x05index\x18\x02 \x01(\rR\x05index\"5\n" +
	"\tBlobChunk\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"\x1b\n" +
	"\aBlobHas\x12\x10\n" +
	"\x03cid\x18\x01 \x01(\fR\x03cid\"|\n" +
	"\rBlobHasResult\x12!\n" +
	"\fhas_manifest\x18\x01 \x01(\bR\vhasManifest\x12%\n" +
	"\x0echunks_present\x18\x02 \x01(\rR\rchunksPresent\x12!\n" +
	"\fchunks_total\x18\x03 \x01(\rR\vchunksTotal\"\xc3\x01\n" +
	"\x0fBlobPutManifest\x12\x10\n" +
	"\x03cid\x18\x01 \x01(\fR\x03cid\x129\n" +
	"\bmanifest\x18\x02 \x01(\v2\x1d.hashgram.p2p.v1.BlobManifestR\bmanifest\x12'\n" +
	"\x0fuploader_pubkey\x18\x03 \x01(\fR\x0euploaderPubkey\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x04R\ttimestamp\x12\x1c\n" +
	"\tsignature\x18\x05 \x01(\fR\tsignature\"r\n" +
	"\x15BlobPutManifestResult\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12%\n" +
	"\x0emissing_chunks\x18\x03 \x03(\rR\rmissingChunks\"J\n" +
	"\fBlobPutChunk\x12\x10\n" +
	"\x03cid\x18\x01 \x01(\fR\x03cid\x12\x14\n" +
	"\x05index\x18\x02 \x01(\rR\x05index\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"H\n" +
	"\x12BlobPutChunkResult\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\xa4\x01\n" +
	"\n" +
	"BlobHealth\x12\x10\n" +
	"\x03cid\x18\x01 \x01(\fR\x03cid\x12'\n" +
	"\x0ftarget_replicas\x18\x02 \x01(\rR\x0etargetReplicas\x12%\n" +
	"\x0eknown_replicas\x18\x03 \x01(\rR\rknownReplicas\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1c\n" +
	"\tproviders\x18\x05 \x03(\tR\tprovidersB.Z,github.com/hashgram/hashgram/pkg/p2ppb;p2ppbb\x06proto3"

var (
	file_hashgram_p2p_v1_blob_proto_rawDescOnce sync.Once
	file_hashgram_p2p_v1_blob_proto_rawDescData []byte
)

func file_hashgram_p2p_v1_blob_proto_rawDescGZIP() []byte {
	file_hashgram_p2p_v1_blob_proto_rawDescOnce.Do(func() {
		file_hashgram_p2p_v1_blob_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hashgram_p2p_v1_blob_proto_rawDesc), len(file_hashgram_p2p_v1_blob_proto_rawDesc)))
	})
	return file_hashgram_p2p_v1_blob_proto_rawDescData
}

var file_hashgram_p2p_v1_blob_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_hashgram_p2p_v1_blob_proto_goTypes = []any{
	(*BlobManifest)(nil),          // 0: hashgram.p2p.v1.BlobManifest
	(*BlobGetManifest)(nil),       // 1: hashgram.p2p.v1.BlobGetManifest
	(*BlobManifestResult)(nil),    // 2: hashgram.p2p.v1.BlobManifestResult
	(*BlobGetChunk)(nil),          // 3: hashgram.p2p.v1.BlobGetChunk
	(*BlobChunk)(nil),             // 4: hashgram.p2p.v1.BlobChunk
	(*BlobHas)(nil),               // 5: hashgram.p2p.v1.BlobHas
	(*BlobHasResult)(nil),         // 6: hashgram.p2p.v1.BlobHasResult
	(*BlobPutManifest)(nil),       // 7: hashgram.p2p.v1.BlobPutManifest
	(*BlobPutManifestResult)(nil), // 8: hashgram.p2p.v1.BlobPutManifestResult
	(*BlobPutChunk)(nil),          // 9: hashgram.p2p.v1.BlobPutChunk
	(*BlobPutChunkResult)(nil),    // 10: hashgram.p2p.v1.BlobPutChunkResult
	(*BlobHealth)(nil),            // 11: hashgram.p2p.v1.BlobHealth
}
var file_hashgram_p2p_v1_blob_proto_depIdxs = []int32{
	0, // 0: hashgram.p2p.v1.BlobManifestResult.manifest:type_name -> hashgram.p2p.v1.BlobManifest
	0, // 1: hashgram.p2p.v1.BlobPutManifest.manifest:type_name -> hashgram.p2p.v1.BlobManifest
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_hashgram_p2p_v1_blob_proto_init() }
func file_hashgram_p2p_v1_blob_proto_init() {
	if File_hashgram_p2p_v1_blob_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hashgram_p2p_v1_blob_proto_rawDesc), len(file_hashgram_p2p_v1_blob_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hashgram_p2p_v1_blob_proto_goTypes,
		DependencyIndexes: file_hashgram_p2p_v1_blob_proto_depIdxs,
		MessageInfos:      file_hashgram_p2p_v1_blob_proto_msgTypes,
	}.Build()
	File_hashgram_p2p_v1_blob_proto = out.File
	file_hashgram_p2p_v1_blob_proto_goTypes = nil
	file_hashgram_p2p_v1_blob_proto_depIdxs = nil
}
