// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: hashgram/p2p/v1/envelope.proto

package p2ppb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// What kind of MLS message the ciphertext is. Needed so the receiving device
// knows which OpenMLS entry point to hand it to; it says nothing about the
// content.
type EnvelopeKind int32

const (
	EnvelopeKind_ENVELOPE_KIND_UNSPECIFIED EnvelopeKind = 0
	// An MLS Welcome, inviting the recipient device into a group.
	EnvelopeKind_ENVELOPE_KIND_MLS_WELCOME EnvelopeKind = 1
	// An MLS PrivateMessage carrying application data or a commit.
	EnvelopeKind_ENVELOPE_KIND_MLS_MESSAGE EnvelopeKind = 2
	// A group info / external join hint. Reserved.
	EnvelopeKind_ENVELOPE_KIND_MLS_GROUP_INFO EnvelopeKind = 3
)

// Enum value maps for EnvelopeKind.
var (
	EnvelopeKind_name = map[int32]string{
		0: "ENVELOPE_KIND_UNSPECIFIED",
		1: "ENVELOPE_KIND_MLS_WELCOME",
		2: "ENVELOPE_KIND_MLS_MESSAGE",
		3: "ENVELOPE_KIND_MLS_GROUP_INFO",
	}
	EnvelopeKind_value = map[string]int32{
		"ENVELOPE_KIND_UNSPECIFIED":    0,
		"ENVELOPE_KIND_MLS_WELCOME":    1,
		"ENVELOPE_KIND_MLS_MESSAGE":    2,
		"ENVELOPE_KIND_MLS_GROUP_INFO": 3,
	}
)

func (x EnvelopeKind) Enum() *EnvelopeKind {
	p := new(EnvelopeKind)
	*p = x
	return p
}

func (x EnvelopeKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EnvelopeKind) Descriptor() protoreflect.EnumDescriptor {
	return file_hashgram_p2p_v1_envelope_proto_enumTypes[0].Descriptor()
}

func (EnvelopeKind) Type() protoreflect.EnumType {
	return &file_hashgram_p2p_v1_envelope_proto_enumTypes[0]
}

func (x EnvelopeKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EnvelopeKind.Descriptor instead.
func (EnvelopeKind) EnumDescriptor() ([]byte, []int) {
	return file_hashgram_p2p_v1_envelope_proto_rawDescGZIP(), []int{0}
}

type Envelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Network this envelope belongs to. A store node refuses envelopes for a
	// network other than its own, so a fork cannot use Mainnet mailboxes.
	NetworkId string `protobuf:"bytes,1,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`
	// Envelope format version. 1.
	Version uint32 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	// BLAKE3 of the canonical encoding of every other field. Used for
	// deduplication and acknowledgement.
	Id []byte `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	// The mailbox: BLAKE3 of the recipient device's public key. A device
	// fetches its own mailbox by proving it holds the key.
	Mailbox []byte       `protobuf:"bytes,4,opt,name=mailbox,proto3" json:"mailbox,omitempty"`
	Kind    EnvelopeKind `protobuf:"varint,5,opt,name=kind,proto3,enum=hashgram.p2p.v1.EnvelopeKind" json:"kind,omitempty"`
	// The MLS message bytes, opaque to the node.
	Ciphertext []byte `protobuf:"bytes,6,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
	// Unix seconds when the sender created it.
	CreatedAt uint64 `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Unix seconds after which a store node drops it unread. Bounded by the
	// node's retention policy; a longer request is clamped, not honoured.
	ExpiresAt     uint64 `protobuf:"varint,8,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_hashgram_p2p_v1_envelope_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_hashgram_p2p_v1_envelope_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_hashgram_p2p_v1_envelope_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetNetworkId() string {
	if x != nil {
		return x.NetworkId
	}
	return ""
}

func (x *Envelope) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Envelope) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Envelope) GetMailbox() []byte {
	if x != nil {
		return x.Mailbox
	}
	return nil
}

func (x *Envelope) GetKind() EnvelopeKind {
	if x != nil {
		return x.Kind
	}
	return EnvelopeKind_ENVELOPE_KIND_UNSPECIFIED
}

func (x *Envelope) GetCiphertext() []byte {
	if x != nil {
		return x.Ciphertext
	}
	return nil
}

func (x *Envelope) GetCreatedAt() uint64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Envelope) GetExpiresAt() uint64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

// Store an envelope for later delivery.
type MailboxPut struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Envelope      *Envelope              `protobuf:"bytes,1,opt,name=envelope,proto3" json:"envelope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MailboxPut) Reset() {
	*x = MailboxPut{}
	mi := &file_hashgram_p2p_v1_envelope_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MailboxPut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MailboxPut) ProtoMessage() {}

func (x *MailboxPut) ProtoReflect() protoreflect.Message {
	mi := &file_hashgram_p2p_v1_envelope_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MailboxPut.ProtoReflect.Descriptor instead.
func (*MailboxPut) Descriptor() ([]byte, []int) {
	return file_hashgram_p2p_v1_envelope_proto_rawDescGZIP(), []int{1}
}

func (x *MailboxPut) GetEnvelope() *Envelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

type MailboxPutResult struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Stored bool                   `protobuf:"varint,1,opt,name=stored,proto3" json:"stored,omitempty"`
	// Why not, when not: quota, expiry too far, wrong network, oversized.
	Reason string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	// What the node actually kept as the expiry, after clamping.
	ExpiresAt     uint64 `protobuf:"varint,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MailboxPutResult) Reset() {
	*x = MailboxPutResult{}
	mi := &file_hashgram_p2p_v1_envelope_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MailboxPutResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MailboxPutResult) ProtoMessage() {}

func (x *MailboxPutResult) ProtoReflect() protoreflect.Message {
	mi := &file_hashgram_p2p_v1_envelope_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MailboxPutResult.ProtoReflect.Descriptor instead.
func (*MailboxPutResult) Descriptor() ([]byte, []int) {
	return file_hashgram_p2p_v1_envelope_proto_rawDescGZIP(), []int{2}
}

func (x *MailboxPutResult) GetStored() bool {
	if x != nil {
		return x.Stored
	}
	return false
}

func (x *MailboxPutResult) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *MailboxPutResult) GetExpiresAt() uint64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

// Fetch envelopes from a mailbox.
//
// Signed by the device key whose hash is the mailbox, so only the owning
// device can read its queue. The timestamp bounds replay: a fetch signed more
// than a few minutes ago is refused.
type MailboxFetch struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Mailbox []byte                 `protobuf:"bytes,1,opt,name=mailbox,proto3" json:"mailbox,omitempty"`
	// Raw ed25519 device public key. The node checks BLAKE3(key) == mailbox.
	DevicePubkey []byte `protobuf:"bytes,2,opt,name=device_pubkey,json=devicePubkey,proto3" json:"device_pubkey,omitempty"`
	// Resume point from a previous MailboxFetchResult. Empty for the start.
	Cursor []byte `protobuf:"bytes,3,opt,name=cursor,proto3" json:"cursor,omitempty"`
	// Maximum envelopes to return. Clamped by the node.
	Limit uint32 `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	// Unix seconds at signing.
	Timestamp uint64 `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Signature over the canonical encoding of mailbox, cursor, limit and
	// timestamp under the "mailbox-fetch" purpose.
	Signature     []byte `protobuf:"bytes,6,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MailboxFetch) Reset() {
	*x = MailboxFetch{}
	mi := &file_hashgram_p2p_v1_envelope_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MailboxFetch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MailboxFetch) ProtoMessage() {}

func (x *MailboxFetch) ProtoReflect() protoreflect.Message {
	mi := &file_hashgram_p2p_v1_envelope_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MailboxFetch.ProtoReflect.Descriptor instead.
func (*MailboxFetch) Descriptor() ([]byte, []int) {
	return file_hashgram_p2p_v1_envelope_proto_rawDescGZIP(), []int{3}
}

func (x *MailboxFetch) GetMailbox() []byte {
	if x != nil {
		return x.Mailbox
	}
	return nil
}

func (x *MailboxFetch) GetDevicePubkey() []byte {
	if x != nil {
		return x.DevicePubkey
	}
	return nil
}

func (x *MailboxFetch) GetCursor() []byte {
	if x != nil {
		return x.Cursor
	}
	return nil
}

func (x *MailboxFetch) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *MailboxFetch) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *MailboxFetch) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type MailboxFetchResult struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Envelopes []*Envelope            `protobuf:"bytes,1,rep,name=envelopes,proto3" json:"envelopes,omitempty"`
	// Pass back as MailboxFetch.cursor to continue. Empty when drained.
	Cursor []byte `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	// How many remain after this page, as a hint for the client's progress UI.
	Remaining     uint64 `protobuf:"varint,3,opt,name=remaining,proto3" json:"remaining,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MailboxFetchResult) Reset() {
	*x = MailboxFetchResult{}
	mi := &file_hashgram_p2p_v1_envelope_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MailboxFetchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MailboxFetchResult) ProtoMessage() {}

func (x *MailboxFetchResult) ProtoReflect() protoreflect.Message {
	mi := &file_hashgram_p2p_v1_envelope_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MailboxFetchResult.ProtoReflect.Descriptor instead.
func (*MailboxFetchResult) Descriptor() ([]byte, []int) {
	return file_hashgram_p2p_v1_envelope_proto_rawDescGZIP(), []int{4}
}

func (x *MailboxFetchResult) GetEnvelopes() []*Envelope {
	if x != nil {
		return x.Envelopes
	}
	return nil
}

func (x *MailboxFetchResult) GetCursor() []byte {
	if x != nil {
		return x.Cursor
	}
	return nil
}

func (x *MailboxFetchResult) GetRemaining() uint64 {
	if x != nil {
		return x.Remaining
	}
	return 0
}

// Acknowledge envelopes so the node can delete them.
type MailboxAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mailbox       []byte                 `protobuf:"bytes,1,opt,name=mailbox,proto3" json:"mailbox,omitempty"`
	DevicePubkey  []byte                 `protobuf:"bytes,2,opt,name=device_pubkey,json=devicePubkey,proto3" json:"device_pubkey,omitempty"`
	EnvelopeIds   [][]byte               `protobuf:"bytes,3,rep,name=envelope_ids,json=envelopeIds,proto3" json:"envelope_ids,omitempty"`
	Timestamp     uint64                 `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Signature     []byte                 `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MailboxAck) Reset() {
	*x = MailboxAck{}
	mi := &file_hashgram_p2p_v1_envelope_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MailboxAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MailboxAck) ProtoMessage() {}

func (x *MailboxAck) ProtoReflect() protoreflect.Message {
	mi := &file_hashgram_p2p_v1_envelope_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MailboxAck.ProtoReflect.Descriptor instead.
func (*MailboxAck) Descriptor() ([]byte, []int) {
	return file_hashgram_p2p_v1_envelope_proto_rawDescGZIP(), []int{5}
}

func (x *MailboxAck) GetMailbox() []byte {
	if x != nil {
		return x.Mailbox
	}
	return nil
}

func (x *MailboxAck) GetDevicePubkey() []byte {
	if x != nil {
		return x.DevicePubkey
	}
	return nil
}

func (x *MailboxAck) GetEnvelopeIds() [][]byte {
	if x != nil {
		return x.EnvelopeIds
	}
	return nil
}

func (x *MailboxAck) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *MailboxAck) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type MailboxAckResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deleted       uint32                 `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MailboxAckResult) Reset() {
	*x = MailboxAckResult{}
	mi := &file_hashgram_p2p_v1_envelope_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MailboxAckResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MailboxAckResult) ProtoMessage() {}

func (x *MailboxAckResult) ProtoReflect() protoreflect.Message {
	mi := &file_hashgram_p2p_v1_envelope_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MailboxAckResult.ProtoReflect.Descriptor instead.
func (*MailboxAckResult) Descriptor() ([]byte, []int) {
	return file_hashgram_p2p_v1_envelope_proto_rawDescGZIP(), []int{6}
}

func (x *MailboxAckResult) GetDeleted() uint32 {
	if x != nil {
		return x.Deleted
	}
	return 0
}

// An MLS KeyPackage published by a device so others can add it to groups.
//
// Signed by the device key so a store node cannot substitute its own. The
// key package itself is also self-authenticating under MLS; the outer
// signature is what lets the node refuse a forgery before storing it.
type KeyPackagePublish struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	NetworkId    string                 `protobuf:"bytes,1,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`
	DevicePubkey []byte                 `protobuf:"bytes,2,opt,name=device_pubkey,json=devicePubkey,proto3" json:"device_pubkey,omitempty"`
	// Serialised MLS KeyPackage.
	KeyPackage []byte `protobuf:"bytes,3,opt,name=key_package,json=keyPackage,proto3" json:"key_package,omitempty"`
	CreatedAt  uint64 `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ExpiresAt  uint64 `protobuf:"varint,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Signature  []byte `protobuf:"bytes,6,opt,name=signature,proto3" json:"signature,omitempty"`
	// A last-resort key package may be handed out repeatedly (MLS marks it
	// so and the device keeps its private key). Ordinary ones are handed out
	// once and deleted, like one-time prekeys; devices publish a batch and
	// replenish when the store reports the queue is low.
	LastResort    bool `protobuf:"varint,7,opt,name=last_resort,json=lastResort,proto3" json:"last_resort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyPackagePublish) Reset() {
	*x = KeyPackagePublish{}
	mi := &file_hashgram_p2p_v1_envelope_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyPackagePublish) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyPackagePublish) ProtoMessage() {}

func (x *KeyPackagePublish) ProtoReflect() protoreflect.Message {
	mi := &file_hashgram_p2p_v1_envelope_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyPackagePublish.ProtoReflect.Descriptor instead.
func (*KeyPackagePublish) Descriptor() ([]byte, []int) {
	return file_hashgram_p2p_v1_envelope_proto_rawDescGZIP(), []int{7}
}

func (x *KeyPackagePublish) GetNetworkId() string {
	if x != nil {
		return x.NetworkId
	}
	return ""
}

func (x *KeyPackagePublish) GetDevicePubkey() []byte {
	if x != nil {
		return x.DevicePubkey
	}
	return nil
}

func (x *KeyPackagePublish) GetKeyPackage() []byte {
	if x != nil {
		return x.KeyPackage
	}
	return nil
}

func (x *KeyPackagePublish) GetCreatedAt() uint64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *KeyPackagePublish) GetExpiresAt() uint64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *KeyPackagePublish) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *KeyPackagePublish) GetLastResort() bool {
	if x != nil {
		return x.LastResort
	}
	return false
}

type KeyPackagePublishResult struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Stored bool                   `protobuf:"varint,1,opt,name=stored,proto3" json:"stored,omitempty"`
	Reason string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	// One-time key packages the node now holds for this device.
	Remaining     uint32 `protobuf:"varint,3,opt,name=remaining,proto3" json:"remaining,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyPackagePublishResult) Reset() {
	*x = KeyPackagePublishResult{}
	mi := &file_hashgram_p2p_v1_envelope_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyPackagePublishResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyPackagePublishResult) ProtoMessage() {}

func (x *KeyPackagePublishResult) ProtoReflect() protoreflect.Message {
	mi := &file_hashgram_p2p_v1_envelope_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyPackagePublishResult.ProtoReflect.Descriptor instead.
func (*KeyPackagePublishResult) Descriptor() ([]byte, []int) {
	return file_hashgram_p2p_v1_envelope_proto_rawDescGZIP(), []int{8}
}

func (x *KeyPackagePublishResult) GetStored() bool {
	if x != nil {
		return x.Stored
	}
	return false
}

func (x *KeyPackagePublishResult) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *KeyPackagePublishResult) GetRemaining() uint32 {
	if x != nil {
		return x.Remaining
	}
	return 0
}

// Fetch a key package for a device.
type KeyPackageFetch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DevicePubkey  []byte                 `protobuf:"bytes,1,opt,name=device_pubkey,json=devicePubkey,proto3" json:"device_pubkey,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyPackageFetch) Reset() {
	*x = KeyPackageFetch{}
	mi := &file_hashgram_p2p_v1_envelope_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyPackageFetch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyPackageFetch) ProtoMessage() {}

func (x *KeyPackageFetch) ProtoReflect() protoreflect.Message {
	mi := &file_hashgram_p2p_v1_envelope_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyPackageFetch.ProtoReflect.Descriptor instead.
func (*KeyPackageFetch) Descriptor() ([]byte, []int) {
	return file_hashgram_p2p_v1_envelope_proto_rawDescGZIP(), []int{9}
}

func (x *KeyPackageFetch) GetDevicePubkey() []byte {
	if x != nil {
		return x.DevicePubkey
	}
	return nil
}

type KeyPackageFetchResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	KeyPackage    *KeyPackagePublish     `protobuf:"bytes,2,opt,name=key_package,json=keyPackage,proto3" json:"key_package,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyPackageFetchResult) Reset() {
	*x = KeyPackageFetchResult{}
	mi := &file_hashgram_p2p_v1_envelope_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyPackageFetchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyPackageFetchResult) ProtoMessage() {}

func (x *KeyPackageFetchResult) ProtoReflect() protoreflect.Message {
	mi := &file_hashgram_p2p_v1_envelope_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyPackageFetchResult.ProtoReflect.Descriptor instead.
func (*KeyPackageFetchResult) Descriptor() ([]byte, []int) {
	return file_hashgram_p2p_v1_envelope_proto_rawDescGZIP(), []int{10}
}

func (x *KeyPackageFetchResult) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *KeyPackageFetchResult) GetKeyPackage() *KeyPackagePublish {
	if x != nil {
		return x.KeyPackage
	}
	return nil
}

// A client-signed service receipt, the evidence behind relay, media and
// call rewards. Mirrors `hashgram.serviceproof.v1.ServiceReceipt` field for
// field so a node can forward it to the chain unchanged; it lives here so
// clients need only the P2P definitions.
type ServiceReceipt struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The provider's operator address.
	Provider string `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	// hashgram.serviceproof.v1.ServiceRole: 2 relay, 3 call, 4 media.
	Role int32 `protobuf:"varint,2,opt,name=role,proto3" json:"role,omitempty"`
	// Raw ed25519 device public key of the client.
	ClientPubkey []byte `protobuf:"bytes,3,opt,name=client_pubkey,json=clientPubkey,proto3" json:"client_pubkey,omitempty"`
	// hashgram.serviceproof.v1.KeyType: 2 for ed25519.
	ClientKeyType int32 `protobuf:"varint,4,opt,name=client_key_type,json=clientKeyType,proto3" json:"client_key_type,omitempty"`
	// The open epoch on chain when the receipt was signed.
	Epoch uint64 `protobuf:"varint,5,opt,name=epoch,proto3" json:"epoch,omitempty"`
	// Unique per (provider, client).
	Nonce uint64 `protobuf:"varint,6,opt,name=nonce,proto3" json:"nonce,omitempty"`
	// Bytes relayed or retrieved, or call seconds.
	Units uint64 `protobuf:"varint,7,opt,name=units,proto3" json:"units,omitempty"`
	// Block height after which the chain refuses it.
	ExpiryHeight int64 `protobuf:"varint,8,opt,name=expiry_height,json=expiryHeight,proto3" json:"expiry_height,omitempty"`
	// Signature over the domain-separated digest of the canonical encoding
	// under the "service-receipt" purpose.
	ClientSignature []byte `protobuf:"bytes,9,opt,name=client_signature,json=clientSignature,proto3" json:"client_signature,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ServiceReceipt) Reset() {
	*x = ServiceReceipt{}
	mi := &file_hashgram_p2p_v1_envelope_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceReceipt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceReceipt) ProtoMessage() {}

func (x *ServiceReceipt) ProtoReflect() protoreflect.Message {
	mi := &file_hashgram_p2p_v1_envelope_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceReceipt.ProtoReflect.Descriptor instead.
func (*ServiceReceipt) Descriptor() ([]byte, []int) {
	return file_hashgram_p2p_v1_envelope_proto_rawDescGZIP(), []int{11}
}

func (x *ServiceReceipt) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *ServiceReceipt) GetRole() int32 {
	if x != nil {
		return x.Role
	}
	return 0
}

func (x *ServiceReceipt) GetClientPubkey() []byte {
	if x != nil {
		return x.ClientPubkey
	}
	return nil
}

func (x *ServiceReceipt) GetClientKeyType() int32 {
	if x != nil {
		return x.ClientKeyType
	}
	return 0
}

func (x *ServiceReceipt) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *ServiceReceipt) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *ServiceReceipt) GetUnits() uint64 {
	if x != nil {
		return x.Units
	}
	return 0
}

func (x *ServiceReceipt) GetExpiryHeight() int64 {
	if x != nil {
		return x.ExpiryHeight
	}
	return 0
}

func (x *ServiceReceipt) GetClientSignature() []byte {
	if x != nil {
		return x.ClientSignature
	}
	return nil
}

// A client hands a receipt to the provider it was served by. The provider
// batches receipts and submits them on chain.
type ReceiptDeliver struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Receipt       *ServiceReceipt        `protobuf:"bytes,1,opt,name=receipt,proto3" json:"receipt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReceiptDeliver) Reset() {
	*x = ReceiptDeliver{}
	mi := &file_hashgram_p2p_v1_envelope_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiptDeliver) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiptDeliver) ProtoMessage() {}

func (x *ReceiptDeliver) ProtoReflect() protoreflect.Message {
	mi := &file_hashgram_p2p_v1_envelope_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiptDeliver.ProtoReflect.Descriptor instead.
func (*ReceiptDeliver) Descriptor() ([]byte, []int) {
	return file_hashgram_p2p_v1_envelope_proto_rawDescGZIP(), []int{12}
}

func (x *ReceiptDeliver) GetReceipt() *ServiceReceipt {
	if x != nil {
		return x.Receipt
	}
	return nil
}

type ReceiptDeliverResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReceiptDeliverResult) Reset() {
	*x = ReceiptDeliverResult{}
	mi := &file_hashgram_p2p_v1_envelope_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiptDeliverResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiptDeliverResult) ProtoMessage() {}

func (x *ReceiptDeliverResult) ProtoReflect() protoreflect.Message {
	mi := &file_hashgram_p2p_v1_envelope_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiptDeliverResult.ProtoReflect.Descriptor instead.
func (*ReceiptDeliverResult) Descriptor() ([]byte, []int) {
	return file_hashgram_p2p_v1_envelope_proto_rawDescGZIP(), []int{13}
}

func (x *ReceiptDeliverResult) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *ReceiptDeliverResult) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_hashgram_p2p_v1_envelope_proto protoreflect.FileDescriptor

const file_hashgram_p2p_v1_envelope_proto_rawDesc = "" +
	"\n" +
	"\x1ehashgram/p2p/v1/envelope.proto\x12\x0fhashgram.p2p.v1\"\xfe\x01\n" +
	"\bEnvelope\x12\x1d\n" +
	"\n" +
	"network_id\x18\x01 \x01(\tR\tnetworkId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\rR\aversion\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\fR\x02id\x12\x18\n" +
	"\amailbox\x18\x04 \x01(\fR\amailbox\x121\n" +
	"\x04kind\x18\x05 \x01(\x0e2\x1d.hashgram.p2p.v1.EnvelopeKindR\x04kind\x12\x1e\n" +
	"\n" +
	"ciphertext\x18\x06 \x01(\fR\n" +
	"ciphertext\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x04R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"expires_at\x18\b \x01(\x04R\texpiresAt\"C\n" +
	"\n" +
	"MailboxPut\x125\n" +
	"\benvelope\x18\x01 \x01(\v2\x19.hashgram.p2p.v1.EnvelopeR\benvelope\"a\n" +
	"\x10MailboxPutResult\x12\x16\n" +
	"\x06stored\x18\x01 \x01(\bR\x06stored\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\x04R\texpiresAt\"\xb7\x01\n" +
	"\fMailboxFetch\x12\x18\n" +
	"\amailbox\x18\x01 \x01(\fR\amailbox\x12#\n" +
	"\rdevice_pubkey\x18\x02 \x01(\fR\fdevicePubkey\x12\x16\n" +
	"\x06cursor\x18\x03 \x01(\fR\x06cursor\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\rR\x05limit\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x04R\ttimestamp\x12\x1c\n" +
	"\tsignature\x18\x06 \x01(\fR\tsignature\"\x83\x01\n" +
	"\x12MailboxFetchResult\x127\n" +
	"\tenvelopes\x18\x01 \x03(\v2\x19.hashgram.p2p.v1.EnvelopeR\tenvelopes\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\fR\x06cursor\x12\x1c\n" +
	"\tremaining\x18\x03 \x01(\x04R\tremaining\"\xaa\x01\n" +
	"\n" +
	"MailboxAck\x12\x18\n" +
	"\amailbox\x18\x01 \x01(\fR\amailbox\x12#\n" +
	"\rdevice_pubkey\x18\x02 \x01(\fR\fdevicePubkey\x12!\n" +
	"\fenvelope_ids\x18\x03 \x03(\fR\venvelopeIds\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x04R\ttimestamp\x12\x1c\n" +
	"\tsignature\x18\x05 \x01(\fR\tsignature\",\n" +
	"\x10MailboxAckResult\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\rR\adeleted\"\xf5\x01\n" +
	"\x11KeyPackagePublish\x12\x1d\n" +
	"\n" +
	"network_id\x18\x01 \x01(\tR\tnetworkId\x12#\n" +
	"\rdevice_pubkey\x18\x02 \x01(\fR\fdevicePubkey\x12\x1f\n" +
	"\vkey_package\x18\x03 \x01(\fR\n" +
	"keyPackage\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\x04R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\x04R\texpiresAt\x12\x1c\n" +
	"\tsignature\x18\x06 \x01(\fR\tsignature\x12\x1f\n" +
	"\vlast_resort\x18\a \x01(\bR\n" +
	"lastResort\"g\n" +
	"\x17KeyPackagePublishResult\x12\x16\n" +
	"\x06stored\x18\x01 \x01(\bR\x06stored\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x1c\n" +
	"\tremaining\x18\x03 \x01(\rR\tremaining\"6\n" +
	"\x0fKeyPackageFetch\x12#\n" +
	"\rdevice_pubkey\x18\x01 \x01(\fR\fdevicePubkey\"r\n" +
	"\x15KeyPackageFetchResult\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12C\n" +
	"\vkey_package\x18\x02 \x01(\v2\".hashgram.p2p.v1.KeyPackagePublishR\n" +
	"keyPackage\"\x9f\x02\n" +
	"\x0eServiceReceipt\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x12\n" +
	"\x04role\x18\x02 \x01(\x05R\x04role\x12#\n" +
	"\rclient_pubkey\x18\x03 \x01(\fR\fclientPubkey\x12&\n" +
	"\x0fclient_key_type\x18\x04 \x01(\x05R\rclientKeyType\x12\x14\n" +
	"\x05epoch\x18\x05 \x01(\x04R\x05epoch\x12\x14\n" +
	"\x05nonce\x18\x06 \x01(\x04R\x05nonce\x12\x14\n" +
	"\x05units\x18\a \x01(\x04R\x05units\x12#\n" +
	"\rexpiry_height\x18\b \x01(\x03R\fexpiryHeight\x12)\n" +
	"\x10client_signature\x18\t \x01(\fR\x0fclientSignature\"K\n" +
	"\x0eReceiptDeliver\x129\n" +
	"\areceipt\x18\x01 \x01(\v2\x1f.hashgram.p2p.v1.ServiceReceiptR\areceipt\"J\n" +
	"\x14ReceiptDeliverResult\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason*\x8d\x01\n" +
	"\fEnvelopeKind\x12\x1d\n" +
	"\x19ENVELOPE_KIND_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19ENVELOPE_KIND_MLS_WELCOME\x10\x01\x12\x1d\n" +
	"\x19ENVELOPE_KIND_MLS_MESSAGE\x10\x02\x12 \n" +
	"\x1cENVELOPE_KIND_MLS_GROUP_INFO\x10\x03B.Z,github.com/hashgram/hashgram/pkg/p2ppb;p2ppbb\x06proto3"

var (
	file_hashgram_p2p_v1_envelope_proto_rawDescOnce sync.Once
	file_hashgram_p2p_v1_envelope_proto_rawDescData []byte
)

func file_hashgram_p2p_v1_envelope_proto_rawDescGZIP() []byte {
	file_hashgram_p2p_v1_envelope_proto_rawDescOnce.Do(func() {
		file_hashgram_p2p_v1_envelope_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hashgram_p2p_v1_envelope_proto_rawDesc), len(file_hashgram_p2p_v1_envelope_proto_rawDesc)))
	})
	return file_hashgram_p2p_v1_envelope_proto_rawDescData
}

var file_hashgram_p2p_v1_envelope_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_hashgram_p2p_v1_envelope_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_hashgram_p2p_v1_envelope_proto_goTypes = []any{
	(EnvelopeKind)(0),               // 0: hashgram.p2p.v1.EnvelopeKind
	(*Envelope)(nil),                // 1: hashgram.p2p.v1.Envelope
	(*MailboxPut)(nil),              // 2: hashgram.p2p.v1.MailboxPut
	(*MailboxPutResult)(nil),        // 3: hashgram.p2p.v1.MailboxPutResult
	(*MailboxFetch)(nil),            // 4: hashgram.p2p.v1.MailboxFetch
	(*MailboxFetchResult)(nil),      // 5: hashgram.p2p.v1.MailboxFetchResult
	(*MailboxAck)(nil),              // 6: hashgram.p2p.v1.MailboxAck
	(*MailboxAckResult)(nil),        // 7: hashgram.p2p.v1.MailboxAckResult
	(*KeyPackagePublish)(nil),       // 8: hashgram.p2p.v1.KeyPackagePublish
	(*KeyPackagePublishResult)(nil), // 9: hashgram.p2p.v1.KeyPackagePublishResult
	(*KeyPackageFetch)(nil),         // 10: hashgram.p2p.v1.KeyPackageFetch
	(*KeyPackageFetchResult)(nil),   // 11: hashgram.p2p.v1.KeyPackageFetchResult
	(*ServiceReceipt)(nil),          // 12: hashgram.p2p.v1.ServiceReceipt
	(*ReceiptDeliver)(nil),          // 13: hashgram.p2p.v1.ReceiptDeliver
	(*ReceiptDeliverResult)(nil),    // 14: hashgram.p2p.v1.ReceiptDeliverResult
}
var file_hashgram_p2p_v1_envelope_proto_depIdxs = []int32{
	0,  // 0: hashgram.p2p.v1.Envelope.kind:type_name -> hashgram.p2p.v1.EnvelopeKind
	1,  // 1: hashgram.p2p.v1.MailboxPut.envelope:type_name -> hashgram.p2p.v1.Envelope
	1,  // 2: hashgram.p2p.v1.MailboxFetchResult.envelopes:type_name -> hashgram.p2p.v1.Envelope
	8,  // 3: hashgram.p2p.v1.KeyPackageFetchResult.key_package:type_name -> hashgram.p2p.v1.KeyPackagePublish
	12, // 4: hashgram.p2p.v1.ReceiptDeliver.receipt:type_name -> hashgram.p2p.v1.ServiceReceipt
	5,  // [5:5] is the sub-list for method output_type
	5,  // [5:5] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_hashgram_p2p_v1_envelope_proto_init() }
func file_hashgram_p2p_v1_envelope_proto_init() {
	if File_hashgram_p2p_v1_envelope_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hashgram_p2p_v1_envelope_proto_rawDesc), len(file_hashgram_p2p_v1_envelope_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hashgram_p2p_v1_envelope_proto_goTypes,
		DependencyIndexes: file_hashgram_p2p_v1_envelope_proto_depIdxs,
		EnumInfos:         file_hashgram_p2p_v1_envelope_proto_enumTypes,
		MessageInfos:      file_hashgram_p2p_v1_envelope_proto_msgTypes,
	}.Build()
	File_hashgram_p2p_v1_envelope_proto = out.File
	file_hashgram_p2p_v1_envelope_proto_goTypes = nil
	file_hashgram_p2p_v1_envelope_proto_depIdxs = nil
}
