// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: hashgram/p2p/v1/handshake.proto

package p2ppb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The Hashgram peer handshake.
//
// Runs on every new libp2p connection before any application protocol is
// served. CometBFT's own handshake compares chain ids only; this one compares
// all five identity parts, including the genesis hash, so a fork that copied
// the chain id is refused at the transport layer rather than tolerated until
// consensus rejects its blocks.
//
// Deliberately carries no addresses, no service list and no free-form
// version string. Everything in it is compared against a local constant, so
// there is nothing a hostile peer can put here that changes behaviour beyond
// causing its own rejection. Service announcements are a separate, signed
// message exchanged only after this succeeds.
type Handshake struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Four-byte network magic, "HGM1" for Mainnet.
	NetworkMagic []byte `protobuf:"bytes,1,opt,name=network_magic,json=networkMagic,proto3" json:"network_magic,omitempty"`
	// Application-level network id, "hashgram-mainnet".
	NetworkId string `protobuf:"bytes,2,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`
	// CometBFT chain id, "hashgram-1".
	ChainId string `protobuf:"bytes,3,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	// Lowercase hex SHA-256 of the genesis file.
	GenesisHash string `protobuf:"bytes,4,opt,name=genesis_hash,json=genesisHash,proto3" json:"genesis_hash,omitempty"`
	// Wire-compatibility generation.
	ProtocolMajorVersion uint32 `protobuf:"varint,5,opt,name=protocol_major_version,json=protocolMajorVersion,proto3" json:"protocol_major_version,omitempty"`
	// Roles this node serves, informational. Verified separately through a
	// signed NodeAnnounce; a peer claiming "store" here is not yet believed.
	Roles []string `protobuf:"bytes,6,rep,name=roles,proto3" json:"roles,omitempty"`
	// The node's provider operator address on chain, if it is a registered
	// useful-service provider. A client that was served signs receipts for
	// this address; the chain, not the client, checks the provider is real.
	OperatorAddress string `protobuf:"bytes,7,opt,name=operator_address,json=operatorAddress,proto3" json:"operator_address,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Handshake) Reset() {
	*x = Handshake{}
	mi := &file_hashgram_p2p_v1_handshake_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Handshake) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Handshake) ProtoMessage() {}

func (x *Handshake) ProtoReflect() protoreflect.Message {
	mi := &file_hashgram_p2p_v1_handshake_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Handshake.ProtoReflect.Descriptor instead.
func (*Handshake) Descriptor() ([]byte, []int) {
	return file_hashgram_p2p_v1_handshake_proto_rawDescGZIP(), []int{0}
}

func (x *Handshake) GetNetworkMagic() []byte {
	if x != nil {
		return x.NetworkMagic
	}
	return nil
}

func (x *Handshake) GetNetworkId() string {
	if x != nil {
		return x.NetworkId
	}
	return ""
}

func (x *Handshake) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

func (x *Handshake) GetGenesisHash() string {
	if x != nil {
		return x.GenesisHash
	}
	return ""
}

func (x *Handshake) GetProtocolMajorVersion() uint32 {
	if x != nil {
		return x.ProtocolMajorVersion
	}
	return 0
}

func (x *Handshake) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *Handshake) GetOperatorAddress() string {
	if x != nil {
		return x.OperatorAddress
	}
	return ""
}

// The answer to a Handshake.
//
// A rejecting peer says why, so an operator on a fork learns which part
// disagreed rather than seeing "connection closed".
type HandshakeAck struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Accepted bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	// Empty when accepted. A human-readable reason otherwise.
	Reason string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	// The responder's own identity, so the initiator can verify it too. Set
	// even on rejection: telling a fork what network it reached costs nothing
	// and helps its operator.
	Identity      *Handshake `protobuf:"bytes,3,opt,name=identity,proto3" json:"identity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandshakeAck) Reset() {
	*x = HandshakeAck{}
	mi := &file_hashgram_p2p_v1_handshake_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeAck) ProtoMessage() {}

func (x *HandshakeAck) ProtoReflect() protoreflect.Message {
	mi := &file_hashgram_p2p_v1_handshake_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeAck.ProtoReflect.Descriptor instead.
func (*HandshakeAck) Descriptor() ([]byte, []int) {
	return file_hashgram_p2p_v1_handshake_proto_rawDescGZIP(), []int{1}
}

func (x *HandshakeAck) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *HandshakeAck) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *HandshakeAck) GetIdentity() *Handshake {
	if x != nil {
		return x.Identity
	}
	return nil
}

var File_hashgram_p2p_v1_handshake_proto protoreflect.FileDescriptor

const file_hashgram_p2p_v1_handshake_proto_rawDesc = "" +
	"\n" +
	"\x1fhashgram/p2p/v1/handshake.proto\x12\x0fhashgram.p2p.v1\"\x84\x02\n" +
	"\tHandshake\x12#\n" +
	"\rnetwork_magic\x18\x01 \x01(\fR\fnetworkMagic\x12\x1d\n" +
	"\n" +
	"network_id\x18\x02 \x01(\tR\tnetworkId\x12\x19\n" +
	"\bchain_id\x18\x03 \x01(\tR\achainId\x12!\n" +
	"\fgenesis_hash\x18\x04 \x01(\tR\vgenesisHash\x124\n" +
	"\x16protocol_major_version\x18\x05 \x01(\rR\x14protocolMajorVersion\x12\x14\n" +
	"\x05roles\x18\x06 \x03(\tR\x05roles\x12)\n" +
	"\x10operator_address\x18\a \x01(\tR\x0foperatorAddress\"z\n" +
	"\fHandshakeAck\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x126\n" +
	"\bidentity\x18\x03 \x01(\v2\x1a.hashgram.p2p.v1.HandshakeR\bidentityB.Z,github.com/hashgram/hashgram/pkg/p2ppb;p2ppbb\x06proto3"

var (
	file_hashgram_p2p_v1_handshake_proto_rawDescOnce sync.Once
	file_hashgram_p2p_v1_handshake_proto_rawDescData []byte
)

func file_hashgram_p2p_v1_handshake_proto_rawDescGZIP() []byte {
	file_hashgram_p2p_v1_handshake_proto_rawDescOnce.Do(func() {
		file_hashgram_p2p_v1_handshake_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hashgram_p2p_v1_handshake_proto_rawDesc), len(file_hashgram_p2p_v1_handshake_proto_rawDesc)))
	})
	return file_hashgram_p2p_v1_handshake_proto_rawDescData
}

var file_hashgram_p2p_v1_handshake_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_hashgram_p2p_v1_handshake_proto_goTypes = []any{
	(*Handshake)(nil),    // 0: hashgram.p2p.v1.Handshake
	(*HandshakeAck)(nil), // 1: hashgram.p2p.v1.HandshakeAck
}
var file_hashgram_p2p_v1_handshake_proto_depIdxs = []int32{
	0, // 0: hashgram.p2p.v1.HandshakeAck.identity:type_name -> hashgram.p2p.v1.Handshake
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_hashgram_p2p_v1_handshake_proto_init() }
func file_hashgram_p2p_v1_handshake_proto_init() {
	if File_hashgram_p2p_v1_handshake_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hashgram_p2p_v1_handshake_proto_rawDesc), len(file_hashgram_p2p_v1_handshake_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hashgram_p2p_v1_handshake_proto_goTypes,
		DependencyIndexes: file_hashgram_p2p_v1_handshake_proto_depIdxs,
		MessageInfos:      file_hashgram_p2p_v1_handshake_proto_msgTypes,
	}.Build()
	File_hashgram_p2p_v1_handshake_proto = out.File
	file_hashgram_p2p_v1_handshake_proto_goTypes = nil
	file_hashgram_p2p_v1_handshake_proto_depIdxs = nil
}
