// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: hashgram/p2p/v1/social.proto

package p2ppb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Media referenced by an event. The bytes live in blob storage, never in
// the event and never on chain.
type MediaReference struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Content identifier: BLAKE3 of the canonical blob manifest.
	Cid []byte `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	// MIME type as the author declares it. Clients sniff and do not trust it.
	Mime string `protobuf:"bytes,2,opt,name=mime,proto3" json:"mime,omitempty"`
	// Total size in bytes.
	Size uint64 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	// "image", "video", "audio", "file".
	Kind       string `protobuf:"bytes,4,opt,name=kind,proto3" json:"kind,omitempty"`
	Width      uint32 `protobuf:"varint,5,opt,name=width,proto3" json:"width,omitempty"`
	Height     uint32 `protobuf:"varint,6,opt,name=height,proto3" json:"height,omitempty"`
	DurationMs uint32 `protobuf:"varint,7,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	// Optional poster or thumbnail blob.
	ThumbnailCid []byte `protobuf:"bytes,8,opt,name=thumbnail_cid,json=thumbnailCid,proto3" json:"thumbnail_cid,omitempty"`
	// A BLAKE3 keyed hash of the plaintext, present only for public media, so
	// a safety attestation can name content independently of its chunking.
	ContentHash   []byte `protobuf:"bytes,9,opt,name=content_hash,json=contentHash,proto3" json:"content_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaReference) Reset() {
	*x = MediaReference{}
	mi := &file_hashgram_p2p_v1_social_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaReference) ProtoMessage() {}

func (x *MediaReference) ProtoReflect() protoreflect.Message {
	mi := &file_hashgram_p2p_v1_social_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaReference.ProtoReflect.Descriptor instead.
func (*MediaReference) Descriptor() ([]byte, []int) {
	return file_hashgram_p2p_v1_social_proto_rawDescGZIP(), []int{0}
}

func (x *MediaReference) GetCid() []byte {
	if x != nil {
		return x.Cid
	}
	return nil
}

func (x *MediaReference) GetMime() string {
	if x != nil {
		return x.Mime
	}
	return ""
}

func (x *MediaReference) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *MediaReference) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *MediaReference) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *MediaReference) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *MediaReference) GetDurationMs() uint32 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *MediaReference) GetThumbnailCid() []byte {
	if x != nil {
		return x.ThumbnailCid
	}
	return nil
}

func (x *MediaReference) GetContentHash() []byte {
	if x != nil {
		return x.ContentHash
	}
	return nil
}

// The event envelope. Field order is the canonical signing order.
type SocialEvent struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	NetworkId string                 `protobuf:"bytes,1,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`
	// Event format version. 1.
	Version uint32 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	// BLAKE3 of the signing preimage. Derived, not chosen.
	Id []byte `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	// One of the EVENT_* families below, as its wire string.
	Type string `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	// Author's Hashgram address, hash1...
	Author string `protobuf:"bytes,5,opt,name=author,proto3" json:"author,omitempty"`
	// Raw ed25519 public key of the signing device. Must be an authorised,
	// unrevoked device of the author on chain at the time of validation.
	DevicePubkey []byte `protobuf:"bytes,6,opt,name=device_pubkey,json=devicePubkey,proto3" json:"device_pubkey,omitempty"`
	// Unix seconds as the author's device claims. Nodes refuse events too far
	// in the future.
	Timestamp uint64 `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Per-author monotonically increasing counter. Two events with the same
	// (author, sequence) and different ids are evidence of a misbehaving
	// device and both are kept as evidence.
	Sequence uint64 `protobuf:"varint,8,opt,name=sequence,proto3" json:"sequence,omitempty"`
	// Id of the author's previous event, forming a per-author hash chain.
	// Empty for sequence 0.
	PreviousEvent []byte `protobuf:"bytes,9,opt,name=previous_event,json=previousEvent,proto3" json:"previous_event,omitempty"`
	// Canonical encoding of the typed payload below.
	Payload []byte            `protobuf:"bytes,10,opt,name=payload,proto3" json:"payload,omitempty"`
	Media   []*MediaReference `protobuf:"bytes,11,rep,name=media,proto3" json:"media,omitempty"`
	// ed25519 signature by device_pubkey over the domain-separated digest of
	// every field above under the "social-event" purpose.
	Signature     []byte `protobuf:"bytes,12,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SocialEvent) Reset() {
	*x = SocialEvent{}
	mi := &file_hashgram_p2p_v1_social_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SocialEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SocialEvent) ProtoMessage() {}

func (x *SocialEvent) ProtoReflect() protoreflect.Message {
	mi := &file_hashgram_p2p_v1_social_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SocialEvent.ProtoReflect.Descriptor instead.
func (*SocialEvent) Descriptor() ([]byte, []int) {
	return file_hashgram_p2p_v1_social_proto_rawDescGZIP(), []int{1}
}

func (x *SocialEvent) GetNetworkId() string {
	if x != nil {
		return x.NetworkId
	}
	return ""
}

func (x *SocialEvent) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *SocialEvent) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *SocialEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *SocialEvent) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *SocialEvent) GetDevicePubkey() []byte {
	if x != nil {
		return x.DevicePubkey
	}
	return nil
}

func (x *SocialEvent) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *SocialEvent) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *SocialEvent) GetPreviousEvent() []byte {
	if x != nil {
		return x.PreviousEvent
	}
	return nil
}

func (x *SocialEvent) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SocialEvent) GetMedia() []*MediaReference {
	if x != nil {
		return x.Media
	}
	return nil
}

func (x *SocialEvent) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type ProfileUpdate struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	DisplayName string                 `protobuf:"bytes,1,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Bio         string                 `protobuf:"bytes,2,opt,name=bio,proto3" json:"bio,omitempty"`
	AvatarCid   []byte                 `protobuf:"bytes,3,opt,name=avatar_cid,json=avatarCid,proto3" json:"avatar_cid,omitempty"`
	BannerCid   []byte                 `protobuf:"bytes,4,opt,name=banner_cid,json=bannerCid,proto3" json:"banner_cid,omitempty"`
	Website     string                 `protobuf:"bytes,5,opt,name=website,proto3" json:"website,omitempty"`
	// Creator metadata, free-form small key/values a client may show.
	Attributes    map[string]string `protobuf:"bytes,6,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfileUpdate) Reset() {
	*x = ProfileUpdate{}
	mi := &file_hashgram_p2p_v1_social_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileUpdate) ProtoMessage() {}

func (x *ProfileUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_hashgram_p2p_v1_social_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileUpdate.ProtoReflect.Descriptor instead.
func (*ProfileUpdate) Descriptor() ([]byte, []int) {
	return file_hashgram_p2p_v1_social_proto_rawDescGZIP(), []int{2}
}

func (x *ProfileUpdate) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *ProfileUpdate) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *ProfileUpdate) GetAvatarCid() []byte {
	if x != nil {
		return x.AvatarCid
	}
	return nil
}

func (x *ProfileUpdate) GetBannerCid() []byte {
	if x != nil {
		return x.BannerCid
	}
	return nil
}

func (x *ProfileUpdate) GetWebsite() string {
	if x != nil {
		return x.Website
	}
	return ""
}

func (x *ProfileUpdate) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type Follow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        string                 `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Follow) Reset() {
	*x = Follow{}
	mi := &file_hashgram_p2p_v1_social_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Follow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Follow) ProtoMessage() {}

func (x *Follow) ProtoReflect() protoreflect.Message {
	mi := &file_hashgram_p2p_v1_social_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Follow.ProtoReflect.Descriptor instead.
func (*Follow) Descriptor() ([]byte, []int) {
	return file_hashgram_p2p_v1_social_proto_rawDescGZIP(), []int{3}
}

func (x *Follow) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

type Unfollow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        string                 `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Unfollow) Reset() {
	*x = Unfollow{}
	mi := &file_hashgram_p2p_v1_social_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Unfollow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Unfollow) ProtoMessage() {}

func (x *Unfollow) ProtoReflect() protoreflect.Message {
	mi := &file_hashgram_p2p_v1_social_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Unfollow.ProtoReflect.Descriptor instead.
func (*Unfollow) Descriptor() ([]byte, []int) {
	return file_hashgram_p2p_v1_social_proto_rawDescGZIP(), []int{4}
}

func (x *Unfollow) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

type PostCreate struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Text     string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Hashtags []string               `protobuf:"bytes,2,rep,name=hashtags,proto3" json:"hashtags,omitempty"`
	Mentions []string               `protobuf:"bytes,3,rep,name=mentions,proto3" json:"mentions,omitempty"`
	// Channel this post belongs to, if any (id of a CHANNEL_CREATE event).
	Channel []byte `protobuf:"bytes,4,opt,name=channel,proto3" json:"channel,omitempty"`
	// Post this is a reply to, if any.
	ReplyTo []byte `protobuf:"bytes,5,opt,name=reply_to,json=replyTo,proto3" json:"reply_to,omitempty"`
	// Content warning / age metadata the author sets. Clients and safety
	// policies may add to it; they cannot remove it.
	Sensitive     bool   `protobuf:"varint,6,opt,name=sensitive,proto3" json:"sensitive,omitempty"`
	Language      string `protobuf:"bytes,7,opt,name=language,proto3" json:"language,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostCreate) Reset() {
	*x = PostCreate{}
	mi := &file_hashgram_p2p_v1_social_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostCreate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostCreate) ProtoMessage() {}

func (x *PostCreate) ProtoReflect() protoreflect.Message {
	mi := &file_hashgram_p2p_v1_social_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostCreate.ProtoReflect.Descriptor instead.
func (*PostCreate) Descriptor() ([]byte, []int) {
	return file_hashgram_p2p_v1_social_proto_rawDescGZIP(), []int{5}
}

func (x *PostCreate) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *PostCreate) GetHashtags() []string {
	if x != nil {
		return x.Hashtags
	}
	return nil
}

func (x *PostCreate) GetMentions() []string {
	if x != nil {
		return x.Mentions
	}
	return nil
}

func (x *PostCreate) GetChannel() []byte {
	if x != nil {
		return x.Channel
	}
	return nil
}

func (x *PostCreate) GetReplyTo() []byte {
	if x != nil {
		return x.ReplyTo
	}
	return nil
}

func (x *PostCreate) GetSensitive() bool {
	if x != nil {
		return x.Sensitive
	}
	return false
}

func (x *PostCreate) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

type PostEdit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Post          []byte                 `protobuf:"bytes,1,opt,name=post,proto3" json:"post,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Hashtags      []string               `protobuf:"bytes,3,rep,name=hashtags,proto3" json:"hashtags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostEdit) Reset() {
	*x = PostEdit{}
	mi := &file_hashgram_p2p_v1_social_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostEdit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostEdit) ProtoMessage() {}

func (x *PostEdit) ProtoReflect() protoreflect.Message {
	mi := &file_hashgram_p2p_v1_social_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostEdit.ProtoReflect.Descriptor instead.
func (*PostEdit) Descriptor() ([]byte, []int) {
	return file_hashgram_p2p_v1_social_proto_rawDescGZIP(), []int{6}
}

func (x *PostEdit) GetPost() []byte {
	if x != nil {
		return x.Post
	}
	return nil
}

func (x *PostEdit) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *PostEdit) GetHashtags() []string {
	if x != nil {
		return x.Hashtags
	}
	return nil
}

type PostDelete struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Post          []byte                 `protobuf:"bytes,1,opt,name=post,proto3" json:"post,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostDelete) Reset() {
	*x = PostDelete{}
	mi := &file_hashgram_p2p_v1_social_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostDelete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostDelete) ProtoMessage() {}

func (x *PostDelete) ProtoReflect() protoreflect.Message {
	mi := &file_hashgram_p2p_v1_social_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostDelete.ProtoReflect.Descriptor instead.
func (*PostDelete) Descriptor() ([]byte, []int) {
	return file_hashgram_p2p_v1_social_proto_rawDescGZIP(), []int{7}
}

func (x *PostDelete) GetPost() []byte {
	if x != nil {
		return x.Post
	}
	return nil
}

type CommentCreate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Post  []byte                 `protobuf:"bytes,1,opt,name=post,proto3" json:"post,omitempty"`
	Text  string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	// For threaded replies to comments.
	ParentComment []byte `protobuf:"bytes,3,opt,name=parent_comment,json=parentComment,proto3" json:"parent_comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentCreate) Reset() {
	*x = CommentCreate{}
	mi := &file_hashgram_p2p_v1_social_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentCreate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentCreate) ProtoMessage() {}

func (x *CommentCreate) ProtoReflect() protoreflect.Message {
	mi := &file_hashgram_p2p_v1_social_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentCreate.ProtoReflect.Descriptor instead.
func (*CommentCreate) Descriptor() ([]byte, []int) {
	return file_hashgram_p2p_v1_social_proto_rawDescGZIP(), []int{8}
}

func (x *CommentCreate) GetPost() []byte {
	if x != nil {
		return x.Post
	}
	return nil
}

func (x *CommentCreate) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *CommentCreate) GetParentComment() []byte {
	if x != nil {
		return x.ParentComment
	}
	return nil
}

type Reaction struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Target []byte                 `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	// A single emoji or a short reaction code. Empty removes the reaction.
	Reaction      string `protobuf:"bytes,2,opt,name=reaction,proto3" json:"reaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reaction) Reset() {
	*x = Reaction{}
	mi := &file_hashgram_p2p_v1_social_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reaction) ProtoMessage() {}

func (x *Reaction) ProtoReflect() protoreflect.Message {
	mi := &file_hashgram_p2p_v1_social_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reaction.ProtoReflect.Descriptor instead.
func (*Reaction) Descriptor() ([]byte, []int) {
	return file_hashgram_p2p_v1_social_proto_rawDescGZIP(), []int{9}
}

func (x *Reaction) GetTarget() []byte {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *Reaction) GetReaction() string {
	if x != nil {
		return x.Reaction
	}
	return ""
}

type Repost struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Post          []byte                 `protobuf:"bytes,1,opt,name=post,proto3" json:"post,omitempty"`
	Comment       string                 `protobuf:"bytes,2,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Repost) Reset() {
	*x = Repost{}
	mi := &file_hashgram_p2p_v1_social_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Repost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Repost) ProtoMessage() {}

func (x *Repost) ProtoReflect() protoreflect.Message {
	mi := &file_hashgram_p2p_v1_social_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Repost.ProtoReflect.Descriptor instead.
func (*Repost) Descriptor() ([]byte, []int) {
	return file_hashgram_p2p_v1_social_proto_rawDescGZIP(), []int{10}
}

func (x *Repost) GetPost() []byte {
	if x != nil {
		return x.Post
	}
	return nil
}

func (x *Repost) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type ChannelCreate struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Name        string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	AvatarCid   []byte                 `protobuf:"bytes,3,opt,name=avatar_cid,json=avatarCid,proto3" json:"avatar_cid,omitempty"`
	// Whether anyone may post, or only the creator.
	OpenPosting   bool `protobuf:"varint,4,opt,name=open_posting,json=openPosting,proto3" json:"open_posting,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelCreate) Reset() {
	*x = ChannelCreate{}
	mi := &file_hashgram_p2p_v1_social_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelCreate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelCreate) ProtoMessage() {}

func (x *ChannelCreate) ProtoReflect() protoreflect.Message {
	mi := &file_hashgram_p2p_v1_social_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelCreate.ProtoReflect.Descriptor instead.
func (*ChannelCreate) Descriptor() ([]byte, []int) {
	return file_hashgram_p2p_v1_social_proto_rawDescGZIP(), []int{11}
}

func (x *ChannelCreate) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ChannelCreate) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ChannelCreate) GetAvatarCid() []byte {
	if x != nil {
		return x.AvatarCid
	}
	return nil
}

func (x *ChannelCreate) GetOpenPosting() bool {
	if x != nil {
		return x.OpenPosting
	}
	return false
}

// A reel is a first-class short video.
type ReelCreate struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Caption  string                 `protobuf:"bytes,1,opt,name=caption,proto3" json:"caption,omitempty"`
	Hashtags []string               `protobuf:"bytes,2,rep,name=hashtags,proto3" json:"hashtags,omitempty"`
	Mentions []string               `protobuf:"bytes,3,rep,name=mentions,proto3" json:"mentions,omitempty"`
	// Index into SocialEvent.media of the video.
	VideoIndex uint32 `protobuf:"varint,4,opt,name=video_index,json=videoIndex,proto3" json:"video_index,omitempty"`
	// Sound / music credit, free-form.
	AudioCredit string `protobuf:"bytes,5,opt,name=audio_credit,json=audioCredit,proto3" json:"audio_credit,omitempty"`
	Sensitive   bool   `protobuf:"varint,6,opt,name=sensitive,proto3" json:"sensitive,omitempty"`
	// Minimum age the author declares, 0 for none.
	MinAge        uint32 `protobuf:"varint,7,opt,name=min_age,json=minAge,proto3" json:"min_age,omitempty"`
	Language      string `protobuf:"bytes,8,opt,name=language,proto3" json:"language,omitempty"`
	AllowComments bool   `protobuf:"varint,9,opt,name=allow_comments,json=allowComments,proto3" json:"allow_comments,omitempty"`
	AllowRemix    bool   `protobuf:"varint,10,opt,name=allow_remix,json=allowRemix,proto3" json:"allow_remix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReelCreate) Reset() {
	*x = ReelCreate{}
	mi := &file_hashgram_p2p_v1_social_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReelCreate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReelCreate) ProtoMessage() {}

func (x *ReelCreate) ProtoReflect() protoreflect.Message {
	mi := &file_hashgram_p2p_v1_social_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReelCreate.ProtoReflect.Descriptor instead.
func (*ReelCreate) Descriptor() ([]byte, []int) {
	return file_hashgram_p2p_v1_social_proto_rawDescGZIP(), []int{12}
}

func (x *ReelCreate) GetCaption() string {
	if x != nil {
		return x.Caption
	}
	return ""
}

func (x *ReelCreate) GetHashtags() []string {
	if x != nil {
		return x.Hashtags
	}
	return nil
}

func (x *ReelCreate) GetMentions() []string {
	if x != nil {
		return x.Mentions
	}
	return nil
}

func (x *ReelCreate) GetVideoIndex() uint32 {
	if x != nil {
		return x.VideoIndex
	}
	return 0
}

func (x *ReelCreate) GetAudioCredit() string {
	if x != nil {
		return x.AudioCredit
	}
	return ""
}

func (x *ReelCreate) GetSensitive() bool {
	if x != nil {
		return x.Sensitive
	}
	return false
}

func (x *ReelCreate) GetMinAge() uint32 {
	if x != nil {
		return x.MinAge
	}
	return 0
}

func (x *ReelCreate) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *ReelCreate) GetAllowComments() bool {
	if x != nil {
		return x.AllowComments
	}
	return false
}

func (x *ReelCreate) GetAllowRemix() bool {
	if x != nil {
		return x.AllowRemix
	}
	return false
}

type StoryCreate struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Caption string                 `protobuf:"bytes,1,opt,name=caption,proto3" json:"caption,omitempty"`
	// Unix seconds after which clients stop showing it. Bounded to 48 hours.
	ExpiresAt     uint64 `protobuf:"varint,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Sensitive     bool   `protobuf:"varint,3,opt,name=sensitive,proto3" json:"sensitive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoryCreate) Reset() {
	*x = StoryCreate{}
	mi := &file_hashgram_p2p_v1_social_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoryCreate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoryCreate) ProtoMessage() {}

func (x *StoryCreate) ProtoReflect() protoreflect.Message {
	mi := &file_hashgram_p2p_v1_social_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoryCreate.ProtoReflect.Descriptor instead.
func (*StoryCreate) Descriptor() ([]byte, []int) {
	return file_hashgram_p2p_v1_social_proto_rawDescGZIP(), []int{13}
}

func (x *StoryCreate) GetCaption() string {
	if x != nil {
		return x.Caption
	}
	return ""
}

func (x *StoryCreate) GetExpiresAt() uint64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *StoryCreate) GetSensitive() bool {
	if x != nil {
		return x.Sensitive
	}
	return false
}

// Gossip announcement that a node holds an event, for peers to fetch by id.
// The full event is also gossiped when small; this covers the large case.
type EventAnnounce struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Author        string                 `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventAnnounce) Reset() {
	*x = EventAnnounce{}
	mi := &file_hashgram_p2p_v1_social_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventAnnounce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventAnnounce) ProtoMessage() {}

func (x *EventAnnounce) ProtoReflect() protoreflect.Message {
	mi := &file_hashgram_p2p_v1_social_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventAnnounce.ProtoReflect.Descriptor instead.
func (*EventAnnounce) Descriptor() ([]byte, []int) {
	return file_hashgram_p2p_v1_social_proto_rawDescGZIP(), []int{14}
}

func (x *EventAnnounce) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *EventAnnounce) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *EventAnnounce) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

// Fetch events by id or by author range.
type EventFetch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           [][]byte               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	Author        string                 `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	FromSequence  uint64                 `protobuf:"varint,3,opt,name=from_sequence,json=fromSequence,proto3" json:"from_sequence,omitempty"`
	Limit         uint32                 `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventFetch) Reset() {
	*x = EventFetch{}
	mi := &file_hashgram_p2p_v1_social_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventFetch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventFetch) ProtoMessage() {}

func (x *EventFetch) ProtoReflect() protoreflect.Message {
	mi := &file_hashgram_p2p_v1_social_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventFetch.ProtoReflect.Descriptor instead.
func (*EventFetch) Descriptor() ([]byte, []int) {
	return file_hashgram_p2p_v1_social_proto_rawDescGZIP(), []int{15}
}

func (x *EventFetch) GetIds() [][]byte {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *EventFetch) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *EventFetch) GetFromSequence() uint64 {
	if x != nil {
		return x.FromSequence
	}
	return 0
}

func (x *EventFetch) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type EventFetchResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*SocialEvent         `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventFetchResult) Reset() {
	*x = EventFetchResult{}
	mi := &file_hashgram_p2p_v1_social_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventFetchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventFetchResult) ProtoMessage() {}

func (x *EventFetchResult) ProtoReflect() protoreflect.Message {
	mi := &file_hashgram_p2p_v1_social_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventFetchResult.ProtoReflect.Descriptor instead.
func (*EventFetchResult) Descriptor() ([]byte, []int) {
	return file_hashgram_p2p_v1_social_proto_rawDescGZIP(), []int{16}
}

func (x *EventFetchResult) GetEvents() []*SocialEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

// Publish an event through a node (client-facing). The node validates it
// fully before gossiping.
type EventPublish struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *SocialEvent           `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventPublish) Reset() {
	*x = EventPublish{}
	mi := &file_hashgram_p2p_v1_social_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventPublish) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventPublish) ProtoMessage() {}

func (x *EventPublish) ProtoReflect() protoreflect.Message {
	mi := &file_hashgram_p2p_v1_social_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventPublish.ProtoReflect.Descriptor instead.
func (*EventPublish) Descriptor() ([]byte, []int) {
	return file_hashgram_p2p_v1_social_proto_rawDescGZIP(), []int{17}
}

func (x *EventPublish) GetEvent() *SocialEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

type EventPublishResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventPublishResult) Reset() {
	*x = EventPublishResult{}
	mi := &file_hashgram_p2p_v1_social_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventPublishResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventPublishResult) ProtoMessage() {}

func (x *EventPublishResult) ProtoReflect() protoreflect.Message {
	mi := &file_hashgram_p2p_v1_social_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventPublishResult.ProtoReflect.Descriptor instead.
func (*EventPublishResult) Descriptor() ([]byte, []int) {
	return file_hashgram_p2p_v1_social_proto_rawDescGZIP(), []int{18}
}

func (x *EventPublishResult) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *EventPublishResult) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_hashgram_p2p_v1_social_proto protoreflect.FileDescriptor

const file_hashgram_p2p_v1_social_proto_rawDesc = "" +
	"\n" +
	"\x1chashgram/p2p/v1/social.proto\x12\x0fhashgram.p2p.v1\"\xf5\x01\n" +
	"\x0eMediaReference\x12\x10\n" +
	"\x03cid\x18\x01 \x01(\fR\x03cid\x12\x12\n" +
	"\x04mime\x18\x02 \x01(\tR\x04mime\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x04R\x04size\x12\x12\n" +
	"\x04kind\x18\x04 \x01(\tR\x04kind\x12\x14\n" +
	"\x05width\x18\x05 \x01(\rR\x05width\x12\x16\n" +
	"\x06height\x18\x06 \x01(\rR\x06height\x12\x1f\n" +
	"\vduration_ms\x18\a \x01(\rR\n" +
	"durationMs\x12#\n" +
	"\rthumbnail_cid\x18\b \x01(\fR\fthumbnailCid\x12!\n" +
	"\fcontent_hash\x18\t \x01(\fR\vcontentHash\"\xf7\x02\n" +
	"\vSocialEvent\x12\x1d\n" +
	"\n" +
	"network_id\x18\x01 \x01(\tR\tnetworkId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\rR\aversion\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\fR\x02id\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x16\n" +
	"\x06author\x18\x05 \x01(\tR\x06author\x12#\n" +
	"\rdevice_pubkey\x18\x06 \x01(\fR\fdevicePubkey\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\x04R\ttimestamp\x12\x1a\n" +
	"\bsequence\x18\b \x01(\x04R\bsequence\x12%\n" +
	"\x0eprevious_event\x18\t \x01(\fR\rpreviousEvent\x12\x18\n" +
	"\apayload\x18\n" +
	" \x01(\fR\apayload\x125\n" +
	"\x05media\x18\v \x03(\v2\x1f.hashgram.p2p.v1.MediaReferenceR\x05media\x12\x1c\n" +
	"\tsignature\x18\f \x01(\fR\tsignature\"\xab\x02\n" +
	"\rProfileUpdate\x12!\n" +
	"\fdisplay_name\x18\x01 \x01(\tR\vdisplayName\x12\x10\n" +
	"\x03bio\x18\x02 \x01(\tR\x03bio\x12\x1d\n" +
	"\n" +
	"avatar_cid\x18\x03 \x01(\fR\tavatarCid\x12\x1d\n" +
	"\n" +
	"banner_cid\x18\x04 \x01(\fR\tbannerCid\x12\x18\n" +
	"\awebsite\x18\x05 \x01(\tR\awebsite\x12N\n" +
	"\n" +
	"attributes\x18\x06 \x03(\v2..hashgram.p2p.v1.ProfileUpdate.AttributesEntryR\n" +
	"attributes\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\" \n" +
	"\x06Follow\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\"\"\n" +
	"\bUnfollow\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\"\xc7\x01\n" +
	"\n" +
	"PostCreate\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x1a\n" +
	"\bhashtags\x18\x02 \x03(\tR\bhashtags\x12\x1a\n" +
	"\bmentions\x18\x03 \x03(\tR\bmentions\x12\x18\n" +
	"\achannel\x18\x04 \x01(\fR\achannel\x12\x19\n" +
	"\breply_to\x18\x05 \x01(\fR\areplyTo\x12\x1c\n" +
	"\tsensitive\x18\x06 \x01(\bR\tsensitive\x12\x1a\n" +
	"\blanguage\x18\a \x01(\tR\blanguage\"N\n" +
	"\bPostEdit\x12\x12\n" +
	"\x04post\x18\x01 \x01(\fR\x04post\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x1a\n" +
	"\bhashtags\x18\x03 \x03(\tR\bhashtags\" \n" +
	"\n" +
	"PostDelete\x12\x12\n" +
	"\x04post\x18\x01 \x01(\fR\x04post\"^\n" +
	"\rCommentCreate\x12\x12\n" +
	"\x04post\x18\x01 \x01(\fR\x04post\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12%\n" +
	"\x0eparent_comment\x18\x03 \x01(\fR\rparentComment\">\n" +
	"\bReaction\x12\x16\n" +
	"\x06target\x18\x01 \x01(\fR\x06target\x12\x1a\n" +
	"\breaction\x18\x02 \x01(\tR\breaction\"6\n" +
	"\x06Repost\x12\x12\n" +
	"\x04post\x18\x01 \x01(\fR\x04post\x12\x18\n" +
	"\acomment\x18\x02 \x01(\tR\acomment\"\x87\x01\n" +
	"\rChannelCreate\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"avatar_cid\x18\x03 \x01(\fR\tavatarCid\x12!\n" +
	"\fopen_posting\x18\x04 \x01(\bR\vopenPosting\"\xbd\x02\n" +
	"\n" +
	"ReelCreate\x12\x18\n" +
	"\acaption\x18\x01 \x01(\tR\acaption\x12\x1a\n" +
	"\bhashtags\x18\x02 \x03(\tR\bhashtags\x12\x1a\n" +
	"\bmentions\x18\x03 \x03(\tR\bmentions\x12\x1f\n" +
	"\vvideo_index\x18\x04 \x01(\rR\n" +
	"videoIndex\x12!\n" +
	"\faudio_credit\x18\x05 \x01(\tR\vaudioCredit\x12\x1c\n" +
	"\tsensitive\x18\x06 \x01(\bR\tsensitive\x12\x17\n" +
	"\amin_age\x18\a \x01(\rR\x06minAge\x12\x1a\n" +
	"\blanguage\x18\b \x01(\tR\blanguage\x12%\n" +
	"\x0eallow_comments\x18\t \x01(\bR\rallowComments\x12\x1f\n" +
	"\vallow_remix\x18\n" +
	" \x01(\bR\n" +
	"allowRemix\"d\n" +
	"\vStoryCreate\x12\x18\n" +
	"\acaption\x18\x01 \x01(\tR\acaption\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\x04R\texpiresAt\x12\x1c\n" +
	"\tsensitive\x18\x03 \x01(\bR\tsensitive\"K\n" +
	"\rEventAnnounce\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12\x16\n" +
	"\x06author\x18\x02 \x01(\tR\x06author\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\"q\n" +
	"\n" +
	"EventFetch\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\fR\x03ids\x12\x16\n" +
	"\x06author\x18\x02 \x01(\tR\x06author\x12#\n" +
	"\rfrom_sequence\x18\x03 \x01(\x04R\ffromSequence\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\rR\x05limit\"H\n" +
	"\x10EventFetchResult\x124\n" +
	"\x06events\x18\x01 \x03(\v2\x1c.hashgram.p2p.v1.SocialEventR\x06events\"B\n" +
	"\fEventPublish\x122\n" +
	"\x05event\x18\x01 \x01(\v2\x1c.hashgram.p2p.v1.SocialEventR\x05event\"H\n" +
	"\x12EventPublishResult\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reasonB.Z,github.com/hashgram/hashgram/pkg/p2ppb;p2ppbb\x06proto3"

var (
	file_hashgram_p2p_v1_social_proto_rawDescOnce sync.Once
	file_hashgram_p2p_v1_social_proto_rawDescData []byte
)

func file_hashgram_p2p_v1_social_proto_rawDescGZIP() []byte {
	file_hashgram_p2p_v1_social_proto_rawDescOnce.Do(func() {
		file_hashgram_p2p_v1_social_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hashgram_p2p_v1_social_proto_rawDesc), len(file_hashgram_p2p_v1_social_proto_rawDesc)))
	})
	return file_hashgram_p2p_v1_social_proto_rawDescData
}

var file_hashgram_p2p_v1_social_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_hashgram_p2p_v1_social_proto_goTypes = []any{
	(*MediaReference)(nil),     // 0: hashgram.p2p.v1.MediaReference
	(*SocialEvent)(nil),        // 1: hashgram.p2p.v1.SocialEvent
	(*ProfileUpdate)(nil),      // 2: hashgram.p2p.v1.ProfileUpdate
	(*Follow)(nil),             // 3: hashgram.p2p.v1.Follow
	(*Unfollow)(nil),           // 4: hashgram.p2p.v1.Unfollow
	(*PostCreate)(nil),         // 5: hashgram.p2p.v1.PostCreate
	(*PostEdit)(nil),           // 6: hashgram.p2p.v1.PostEdit
	(*PostDelete)(nil),         // 7: hashgram.p2p.v1.PostDelete
	(*CommentCreate)(nil),      // 8: hashgram.p2p.v1.CommentCreate
	(*Reaction)(nil),           // 9: hashgram.p2p.v1.Reaction
	(*Repost)(nil),             // 10: hashgram.p2p.v1.Repost
	(*ChannelCreate)(nil),      // 11: hashgram.p2p.v1.ChannelCreate
	(*ReelCreate)(nil),         // 12: hashgram.p2p.v1.ReelCreate
	(*StoryCreate)(nil),        // 13: hashgram.p2p.v1.StoryCreate
	(*EventAnnounce)(nil),      // 14: hashgram.p2p.v1.EventAnnounce
	(*EventFetch)(nil),         // 15: hashgram.p2p.v1.EventFetch
	(*EventFetchResult)(nil),   // 16: hashgram.p2p.v1.EventFetchResult
	(*EventPublish)(nil),       // 17: hashgram.p2p.v1.EventPublish
	(*EventPublishResult)(nil), // 18: hashgram.p2p.v1.EventPublishResult
	nil,                        // 19: hashgram.p2p.v1.ProfileUpdate.AttributesEntry
}
var file_hashgram_p2p_v1_social_proto_depIdxs = []int32{
	0,  // 0: hashgram.p2p.v1.SocialEvent.media:type_name -> hashgram.p2p.v1.MediaReference
	19, // 1: hashgram.p2p.v1.ProfileUpdate.attributes:type_name -> hashgram.p2p.v1.ProfileUpdate.AttributesEntry
	1,  // 2: hashgram.p2p.v1.EventFetchResult.events:type_name -> hashgram.p2p.v1.SocialEvent
	1,  // 3: hashgram.p2p.v1.EventPublish.event:type_name -> hashgram.p2p.v1.SocialEvent
	4,  // [4:4] is the sub-list for method output_type
	4,  // [4:4] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_hashgram_p2p_v1_social_proto_init() }
func file_hashgram_p2p_v1_social_proto_init() {
	if File_hashgram_p2p_v1_social_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hashgram_p2p_v1_social_proto_rawDesc), len(file_hashgram_p2p_v1_social_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hashgram_p2p_v1_social_proto_goTypes,
		DependencyIndexes: file_hashgram_p2p_v1_social_proto_depIdxs,
		MessageInfos:      file_hashgram_p2p_v1_social_proto_msgTypes,
	}.Build()
	File_hashgram_p2p_v1_social_proto = out.File
	file_hashgram_p2p_v1_social_proto_goTypes = nil
	file_hashgram_p2p_v1_social_proto_depIdxs = nil
}
