// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: hashgram/founder/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is the request for Query/Params.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e2bcf653e3445bb, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is the response for Query/Params.
type QueryParamsResponse struct {
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	// max_fee_basis_points is the compile-time ceiling on fee_basis_points in
	// the binary serving this query. Reported so that a client can see the cap
	// exists rather than having to read the source.
	MaxFeeBasisPoints uint32 `protobuf:"varint,2,opt,name=max_fee_basis_points,json=maxFeeBasisPoints,proto3" json:"max_fee_basis_points,omitempty"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e2bcf653e3445bb, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *QueryParamsResponse) GetMaxFeeBasisPoints() uint32 {
	if m != nil {
		return m.MaxFeeBasisPoints
	}
	return 0
}

// QueryRevenueRequest is the request for Query/Revenue.
type QueryRevenueRequest struct {
}

func (m *QueryRevenueRequest) Reset()         { *m = QueryRevenueRequest{} }
func (m *QueryRevenueRequest) String() string { return proto.CompactTextString(m) }
func (*QueryRevenueRequest) ProtoMessage()    {}
func (*QueryRevenueRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e2bcf653e3445bb, []int{2}
}
func (m *QueryRevenueRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryRevenueRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryRevenueRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryRevenueRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRevenueRequest.Merge(m, src)
}
func (m *QueryRevenueRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryRevenueRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRevenueRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRevenueRequest proto.InternalMessageInfo

// QueryRevenueResponse is the response for Query/Revenue.
type QueryRevenueResponse struct {
	// total_accrued is every coin ever credited to the Founder.
	TotalAccrued github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,1,rep,name=total_accrued,json=totalAccrued,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"total_accrued"`
	// total_paid is every coin ever pushed to a beneficiary.
	TotalPaid github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,2,rep,name=total_paid,json=totalPaid,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"total_paid"`
	// pending is what is sitting in the founder module account right now,
	// accrued but not yet paid out.
	Pending github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,3,rep,name=pending,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"pending"`
	// module_account is the address holding `pending`. Its balance is also
	// visible through a plain bank query, so this figure is cross-checkable.
	ModuleAccount         string `protobuf:"bytes,4,opt,name=module_account,json=moduleAccount,proto3" json:"module_account,omitempty"`
	LastPayoutHeight      int64  `protobuf:"varint,5,opt,name=last_payout_height,json=lastPayoutHeight,proto3" json:"last_payout_height,omitempty"`
	LastPayoutBeneficiary string `protobuf:"bytes,6,opt,name=last_payout_beneficiary,json=lastPayoutBeneficiary,proto3" json:"last_payout_beneficiary,omitempty"`
}

func (m *QueryRevenueResponse) Reset()         { *m = QueryRevenueResponse{} }
func (m *QueryRevenueResponse) String() string { return proto.CompactTextString(m) }
func (*QueryRevenueResponse) ProtoMessage()    {}
func (*QueryRevenueResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e2bcf653e3445bb, []int{3}
}
func (m *QueryRevenueResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryRevenueResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryRevenueResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryRevenueResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRevenueResponse.Merge(m, src)
}
func (m *QueryRevenueResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryRevenueResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRevenueResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRevenueResponse proto.InternalMessageInfo

func (m *QueryRevenueResponse) GetTotalAccrued() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.TotalAccrued
	}
	return nil
}

func (m *QueryRevenueResponse) GetTotalPaid() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.TotalPaid
	}
	return nil
}

func (m *QueryRevenueResponse) GetPending() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.Pending
	}
	return nil
}

func (m *QueryRevenueResponse) GetModuleAccount() string {
	if m != nil {
		return m.ModuleAccount
	}
	return ""
}

func (m *QueryRevenueResponse) GetLastPayoutHeight() int64 {
	if m != nil {
		return m.LastPayoutHeight
	}
	return 0
}

func (m *QueryRevenueResponse) GetLastPayoutBeneficiary() string {
	if m != nil {
		return m.LastPayoutBeneficiary
	}
	return ""
}

// QueryBeneficiaryHistoryRequest is the request for Query/BeneficiaryHistory.
type QueryBeneficiaryHistoryRequest struct {
}

func (m *QueryBeneficiaryHistoryRequest) Reset()         { *m = QueryBeneficiaryHistoryRequest{} }
func (m *QueryBeneficiaryHistoryRequest) String() string { return proto.CompactTextString(m) }
func (*QueryBeneficiaryHistoryRequest) ProtoMessage()    {}
func (*QueryBeneficiaryHistoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e2bcf653e3445bb, []int{4}
}
func (m *QueryBeneficiaryHistoryRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryBeneficiaryHistoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryBeneficiaryHistoryRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryBeneficiaryHistoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryBeneficiaryHistoryRequest.Merge(m, src)
}
func (m *QueryBeneficiaryHistoryRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryBeneficiaryHistoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryBeneficiaryHistoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryBeneficiaryHistoryRequest proto.InternalMessageInfo

// QueryBeneficiaryHistoryResponse is the response for Query/BeneficiaryHistory.
type QueryBeneficiaryHistoryResponse struct {
	Changes []BeneficiaryChange `protobuf:"bytes,1,rep,name=changes,proto3" json:"changes"`
}

func (m *QueryBeneficiaryHistoryResponse) Reset()         { *m = QueryBeneficiaryHistoryResponse{} }
func (m *QueryBeneficiaryHistoryResponse) String() string { return proto.CompactTextString(m) }
func (*QueryBeneficiaryHistoryResponse) ProtoMessage()    {}
func (*QueryBeneficiaryHistoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e2bcf653e3445bb, []int{5}
}
func (m *QueryBeneficiaryHistoryResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryBeneficiaryHistoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryBeneficiaryHistoryResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryBeneficiaryHistoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryBeneficiaryHistoryResponse.Merge(m, src)
}
func (m *QueryBeneficiaryHistoryResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryBeneficiaryHistoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryBeneficiaryHistoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryBeneficiaryHistoryResponse proto.InternalMessageInfo

func (m *QueryBeneficiaryHistoryResponse) GetChanges() []BeneficiaryChange {
	if m != nil {
		return m.Changes
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "hashgram.founder.v1.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "hashgram.founder.v1.QueryParamsResponse")
	proto.RegisterType((*QueryRevenueRequest)(nil), "hashgram.founder.v1.QueryRevenueRequest")
	proto.RegisterType((*QueryRevenueResponse)(nil), "hashgram.founder.v1.QueryRevenueResponse")
	proto.RegisterType((*QueryBeneficiaryHistoryRequest)(nil), "hashgram.founder.v1.QueryBeneficiaryHistoryRequest")
	proto.RegisterType((*QueryBeneficiaryHistoryResponse)(nil), "hashgram.founder.v1.QueryBeneficiaryHistoryResponse")
}

func init() { proto.RegisterFile("hashgram/founder/v1/query.proto", fileDescriptor_4e2bcf653e3445bb) }

var fileDescriptor_4e2bcf653e3445bb = []byte{
	// 696 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x54, 0x41, 0x4f, 0x13, 0x4d,
	0x18, 0xee, 0x50, 0x28, 0x61, 0xf8, 0xf8, 0xf2, 0x31, 0x94, 0x7c, 0x4b, 0xc1, 0x6d, 0xad, 0x46,
	0x57, 0x02, 0xbb, 0x16, 0xf4, 0xe0, 0xc9, 0x50, 0x12, 0xc2, 0xb1, 0xd6, 0x9b, 0x97, 0xcd, 0xb4,
	0x3b, 0xec, 0x8e, 0x76, 0x67, 0x96, 0x9d, 0xd9, 0x86, 0xde, 0xd4, 0xf8, 0x03, 0x4c, 0xfc, 0x13,
	0x46, 0x2f, 0x9a, 0xf8, 0x17, 0x4c, 0x38, 0x12, 0xbd, 0x78, 0x52, 0x03, 0x26, 0xfe, 0x0d, 0xb3,
	0xb3, 0x53, 0x28, 0x61, 0x11, 0x3d, 0x70, 0x69, 0x67, 0xde, 0xf7, 0x79, 0xdf, 0xe7, 0x99, 0xb7,
	0xef, 0x53, 0x58, 0x0d, 0xb0, 0x08, 0xfc, 0x18, 0x87, 0xce, 0x0e, 0x4f, 0x98, 0x47, 0x62, 0xa7,
	0xdf, 0x70, 0x76, 0x13, 0x12, 0x0f, 0xec, 0x28, 0xe6, 0x92, 0xa3, 0xb9, 0x21, 0xc0, 0xd6, 0x00,
	0xbb, 0xdf, 0xa8, 0xcc, 0xe2, 0x90, 0x32, 0xee, 0xa8, 0xcf, 0x0c, 0x57, 0x31, 0xbb, 0x5c, 0x84,
	0x5c, 0x38, 0x1d, 0x2c, 0x88, 0xd3, 0x6f, 0x74, 0x88, 0xc4, 0x0d, 0xa7, 0xcb, 0x29, 0xd3, 0xf9,
	0x85, 0x2c, 0xef, 0xaa, 0x9b, 0x93, 0x5d, 0x74, 0xaa, 0xec, 0x73, 0x9f, 0x67, 0xf1, 0xf4, 0xa4,
	0xa3, 0x4b, 0x3e, 0xe7, 0x7e, 0x8f, 0x38, 0x38, 0xa2, 0x0e, 0x66, 0x8c, 0x4b, 0x2c, 0x29, 0x67,
	0xc3, 0x9a, 0xab, 0x79, 0xba, 0x87, 0x0a, 0x15, 0xa4, 0x5e, 0x86, 0xe8, 0x41, 0xfa, 0x90, 0x16,
	0x8e, 0x71, 0x28, 0xda, 0x64, 0x37, 0x21, 0x42, 0xd6, 0x9f, 0x01, 0x38, 0x77, 0x2a, 0x2c, 0x22,
	0xce, 0x04, 0x41, 0xf7, 0x60, 0x29, 0x52, 0x11, 0x03, 0xd4, 0x80, 0x35, 0xbd, 0xb6, 0x68, 0xe7,
	0x3c, 0xdc, 0xce, 0x8a, 0x9a, 0xe3, 0xfb, 0x5f, 0xab, 0x85, 0xb6, 0x2e, 0x40, 0x0e, 0x2c, 0x87,
	0x78, 0xcf, 0xdd, 0x21, 0xc4, 0xed, 0x60, 0x41, 0x85, 0x1b, 0x71, 0xca, 0xa4, 0x30, 0xc6, 0x6a,
	0xc0, 0x9a, 0x69, 0xcf, 0x86, 0x78, 0x6f, 0x8b, 0x90, 0x66, 0x9a, 0x69, 0xa9, 0x44, 0x7d, 0x5e,
	0x4b, 0x68, 0x93, 0x3e, 0x61, 0x09, 0x19, 0x4a, 0x7b, 0x3b, 0x0e, 0xcb, 0xa7, 0xe3, 0x5a, 0x5b,
	0x02, 0x67, 0x24, 0x97, 0xb8, 0xe7, 0xe2, 0x6e, 0x37, 0x4e, 0x88, 0x67, 0x80, 0x5a, 0xd1, 0x9a,
	0x5e, 0x5b, 0xb0, 0xf5, 0x18, 0xd3, 0x99, 0xdb, 0x7a, 0xe6, 0xf6, 0x26, 0xa7, 0xac, 0x79, 0x37,
	0x15, 0xf8, 0xe6, 0x5b, 0xd5, 0xf2, 0xa9, 0x0c, 0x92, 0x8e, 0xdd, 0xe5, 0xa1, 0x9e, 0xb9, 0xfe,
	0x5a, 0x15, 0xde, 0x13, 0x47, 0x0e, 0x22, 0x22, 0x54, 0x81, 0x78, 0xfd, 0xf3, 0xdd, 0x32, 0x68,
	0xff, 0xa3, 0x68, 0x36, 0x32, 0x16, 0xc4, 0x21, 0xcc, 0x68, 0x23, 0x4c, 0x3d, 0x63, 0xec, 0x92,
	0x38, 0xa7, 0x14, 0x47, 0x0b, 0x53, 0x0f, 0x3d, 0x86, 0x93, 0x11, 0x61, 0x1e, 0x65, 0xbe, 0x51,
	0xbc, 0x24, 0xb6, 0x21, 0x01, 0xba, 0x0f, 0xff, 0x0d, 0xb9, 0x97, 0xf4, 0x48, 0x3a, 0x54, 0x9e,
	0x30, 0x69, 0x8c, 0xd7, 0x80, 0x35, 0xd5, 0x34, 0x3e, 0x7d, 0x58, 0x2d, 0x6b, 0xd6, 0x0d, 0xcf,
	0x8b, 0x89, 0x10, 0x0f, 0x65, 0x4c, 0x99, 0xdf, 0x9e, 0xc9, 0xf0, 0x1b, 0x19, 0x1c, 0xad, 0x40,
	0xd4, 0xc3, 0x42, 0xba, 0x11, 0x1e, 0xf0, 0x44, 0xba, 0x01, 0xa1, 0x7e, 0x20, 0x8d, 0x89, 0x1a,
	0xb0, 0x8a, 0xed, 0xff, 0xd2, 0x4c, 0x4b, 0x25, 0xb6, 0x55, 0x1c, 0xb5, 0xe0, 0xff, 0xa3, 0xe8,
	0x0e, 0x61, 0x64, 0x87, 0x76, 0x29, 0x8e, 0x07, 0x46, 0xe9, 0x02, 0xde, 0xf9, 0x93, 0x66, 0xcd,
	0x93, 0xb2, 0x7a, 0x0d, 0x9a, 0x6a, 0x59, 0x46, 0x62, 0xdb, 0x54, 0x48, 0x9e, 0xae, 0x4f, 0xb6,
	0x4f, 0x14, 0x56, 0xcf, 0x45, 0xe8, 0xcd, 0xda, 0x82, 0x93, 0xdd, 0x00, 0x33, 0x9f, 0x08, 0xbd,
	0x53, 0x37, 0x72, 0xd7, 0x7e, 0xa4, 0xc3, 0xa6, 0x82, 0x6b, 0x07, 0x0c, 0x8b, 0xd7, 0x3e, 0x16,
	0xe1, 0x84, 0xe2, 0x42, 0x4f, 0x01, 0x2c, 0x65, 0x2e, 0x41, 0x37, 0x73, 0x7b, 0x9d, 0xf5, 0x64,
	0xc5, 0xba, 0x18, 0x98, 0xe9, 0xad, 0x5f, 0x7b, 0xfe, 0xf9, 0xc7, 0xab, 0xb1, 0x2b, 0x68, 0xd1,
	0xc9, 0xf3, 0xbf, 0xf6, 0xe3, 0x0b, 0x00, 0x27, 0xb5, 0x85, 0xd0, 0x6f, 0x5a, 0x9f, 0x76, 0x5f,
	0xe5, 0xd6, 0x1f, 0x20, 0xb5, 0x8a, 0xeb, 0x4a, 0x85, 0x89, 0x96, 0x72, 0x55, 0xc4, 0x9a, 0xfa,
	0x3d, 0x80, 0xe8, 0xec, 0xe8, 0xd1, 0xfa, 0xf9, 0x3c, 0xe7, 0xfe, 0x94, 0x95, 0x3b, 0x7f, 0x57,
	0xa4, 0x75, 0xde, 0x56, 0x3a, 0x97, 0x91, 0x95, 0xab, 0x73, 0x64, 0x07, 0xdd, 0x20, 0xab, 0x6c,
	0x6e, 0xed, 0x1f, 0x9a, 0xe0, 0xe0, 0xd0, 0x04, 0xdf, 0x0f, 0x4d, 0xf0, 0xf2, 0xc8, 0x2c, 0x1c,
	0x1c, 0x99, 0x85, 0x2f, 0x47, 0x66, 0xe1, 0xd1, 0xca, 0x88, 0xcf, 0x8e, 0xbb, 0x1d, 0x1f, 0xf6,
	0x8e, 0x1b, 0x2b, 0xc7, 0x75, 0x4a, 0xea, 0x2f, 0x78, 0xfd, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x11, 0xdd, 0x35, 0x90, 0x5f, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Params returns the beneficiary and revenue share configuration.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Revenue returns accrued, paid and currently-pending Founder revenue.
	Revenue(ctx context.Context, in *QueryRevenueRequest, opts ...grpc.CallOption) (*QueryRevenueResponse, error)
	// BeneficiaryHistory returns every governance-approved beneficiary change.
	BeneficiaryHistory(ctx context.Context, in *QueryBeneficiaryHistoryRequest, opts ...grpc.CallOption) (*QueryBeneficiaryHistoryResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/hashgram.founder.v1.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Revenue(ctx context.Context, in *QueryRevenueRequest, opts ...grpc.CallOption) (*QueryRevenueResponse, error) {
	out := new(QueryRevenueResponse)
	err := c.cc.Invoke(ctx, "/hashgram.founder.v1.Query/Revenue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) BeneficiaryHistory(ctx context.Context, in *QueryBeneficiaryHistoryRequest, opts ...grpc.CallOption) (*QueryBeneficiaryHistoryResponse, error) {
	out := new(QueryBeneficiaryHistoryResponse)
	err := c.cc.Invoke(ctx, "/hashgram.founder.v1.Query/BeneficiaryHistory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Params returns the beneficiary and revenue share configuration.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Revenue returns accrued, paid and currently-pending Founder revenue.
	Revenue(context.Context, *QueryRevenueRequest) (*QueryRevenueResponse, error)
	// BeneficiaryHistory returns every governance-approved beneficiary change.
	BeneficiaryHistory(context.Context, *QueryBeneficiaryHistoryRequest) (*QueryBeneficiaryHistoryResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) Revenue(ctx context.Context, req *QueryRevenueRequest) (*QueryRevenueResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Revenue not implemented")
}
func (*UnimplementedQueryServer) BeneficiaryHistory(ctx context.Context, req *QueryBeneficiaryHistoryRequest) (*QueryBeneficiaryHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BeneficiaryHistory not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hashgram.founder.v1.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Revenue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRevenueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Revenue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hashgram.founder.v1.Query/Revenue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Revenue(ctx, req.(*QueryRevenueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_BeneficiaryHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryBeneficiaryHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).BeneficiaryHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hashgram.founder.v1.Query/BeneficiaryHistory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).BeneficiaryHistory(ctx, req.(*QueryBeneficiaryHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "hashgram.founder.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "Revenue",
			Handler:    _Query_Revenue_Handler,
		},
		{
			MethodName: "BeneficiaryHistory",
			Handler:    _Query_BeneficiaryHistory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hashgram/founder/v1/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MaxFeeBasisPoints != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.MaxFeeBasisPoints))
		i--
		dAtA[i] = 0x10
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryRevenueRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryRevenueRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryRevenueRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryRevenueResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryRevenueResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryRevenueResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.LastPayoutBeneficiary) > 0 {
		i -= len(m.LastPayoutBeneficiary)
		copy(dAtA[i:], m.LastPayoutBeneficiary)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.LastPayoutBeneficiary)))
		i--
		dAtA[i] = 0x32
	}
	if m.LastPayoutHeight != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.LastPayoutHeight))
		i--
		dAtA[i] = 0x28
	}
	if len(m.ModuleAccount) > 0 {
		i -= len(m.ModuleAccount)
		copy(dAtA[i:], m.ModuleAccount)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.ModuleAccount)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Pending) > 0 {
		for iNdEx := len(m.Pending) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Pending[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.TotalPaid) > 0 {
		for iNdEx := len(m.TotalPaid) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.TotalPaid[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.TotalAccrued) > 0 {
		for iNdEx := len(m.TotalAccrued) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.TotalAccrued[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryBeneficiaryHistoryRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryBeneficiaryHistoryRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryBeneficiaryHistoryRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryBeneficiaryHistoryResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryBeneficiaryHistoryResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryBeneficiaryHistoryResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Changes) > 0 {
		for iNdEx := len(m.Changes) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Changes[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	if m.MaxFeeBasisPoints != 0 {
		n += 1 + sovQuery(uint64(m.MaxFeeBasisPoints))
	}
	return n
}

func (m *QueryRevenueRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryRevenueResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.TotalAccrued) > 0 {
		for _, e := range m.TotalAccrued {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if len(m.TotalPaid) > 0 {
		for _, e := range m.TotalPaid {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if len(m.Pending) > 0 {
		for _, e := range m.Pending {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	l = len(m.ModuleAccount)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.LastPayoutHeight != 0 {
		n += 1 + sovQuery(uint64(m.LastPayoutHeight))
	}
	l = len(m.LastPayoutBeneficiary)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryBeneficiaryHistoryRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryBeneficiaryHistoryResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Changes) > 0 {
		for _, e := range m.Changes {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxFeeBasisPoints", wireType)
			}
			m.MaxFeeBasisPoints = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxFeeBasisPoints |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryRevenueRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryRevenueRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryRevenueRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryRevenueResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryRevenueResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryRevenueResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalAccrued", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TotalAccrued = append(m.TotalAccrued, types.Coin{})
			if err := m.TotalAccrued[len(m.TotalAccrued)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalPaid", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TotalPaid = append(m.TotalPaid, types.Coin{})
			if err := m.TotalPaid[len(m.TotalPaid)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pending", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Pending = append(m.Pending, types.Coin{})
			if err := m.Pending[len(m.Pending)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ModuleAccount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ModuleAccount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastPayoutHeight", wireType)
			}
			m.LastPayoutHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LastPayoutHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastPayoutBeneficiary", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LastPayoutBeneficiary = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryBeneficiaryHistoryRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryBeneficiaryHistoryRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryBeneficiaryHistoryRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryBeneficiaryHistoryResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryBeneficiaryHistoryResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryBeneficiaryHistoryResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Changes", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Changes = append(m.Changes, BeneficiaryChange{})
			if err := m.Changes[len(m.Changes)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
