// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: hashgram/founder/v1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgUpdateParams changes the Founder revenue configuration.
type MsgUpdateParams struct {
	// authority must be the governance module account.
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	// params is the full replacement parameter set.
	//
	// fee_basis_points is validated against a compile-time ceiling, so this
	// message cannot raise the Founder share above 1%.
	Params Params `protobuf:"bytes,2,opt,name=params,proto3" json:"params"`
}

func (m *MsgUpdateParams) Reset()         { *m = MsgUpdateParams{} }
func (m *MsgUpdateParams) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateParams) ProtoMessage()    {}
func (*MsgUpdateParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_a87c077b09b3ec9b, []int{0}
}
func (m *MsgUpdateParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateParams.Merge(m, src)
}
func (m *MsgUpdateParams) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateParams) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateParams.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateParams proto.InternalMessageInfo

func (m *MsgUpdateParams) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgUpdateParams) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

// MsgUpdateParamsResponse is the response type.
type MsgUpdateParamsResponse struct {
}

func (m *MsgUpdateParamsResponse) Reset()         { *m = MsgUpdateParamsResponse{} }
func (m *MsgUpdateParamsResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateParamsResponse) ProtoMessage()    {}
func (*MsgUpdateParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a87c077b09b3ec9b, []int{1}
}
func (m *MsgUpdateParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateParamsResponse.Merge(m, src)
}
func (m *MsgUpdateParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateParamsResponse proto.InternalMessageInfo

// MsgClaimFounderRevenue pushes accrued revenue to the beneficiary.
type MsgClaimFounderRevenue struct {
	// sender is whoever is paying the gas to trigger the payout. It has no
	// influence on the destination.
	Sender string `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
}

func (m *MsgClaimFounderRevenue) Reset()         { *m = MsgClaimFounderRevenue{} }
func (m *MsgClaimFounderRevenue) String() string { return proto.CompactTextString(m) }
func (*MsgClaimFounderRevenue) ProtoMessage()    {}
func (*MsgClaimFounderRevenue) Descriptor() ([]byte, []int) {
	return fileDescriptor_a87c077b09b3ec9b, []int{2}
}
func (m *MsgClaimFounderRevenue) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgClaimFounderRevenue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgClaimFounderRevenue.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgClaimFounderRevenue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgClaimFounderRevenue.Merge(m, src)
}
func (m *MsgClaimFounderRevenue) XXX_Size() int {
	return m.Size()
}
func (m *MsgClaimFounderRevenue) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgClaimFounderRevenue.DiscardUnknown(m)
}

var xxx_messageInfo_MsgClaimFounderRevenue proto.InternalMessageInfo

func (m *MsgClaimFounderRevenue) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

// MsgClaimFounderRevenueResponse reports what was paid and to whom.
type MsgClaimFounderRevenueResponse struct {
	// paid is the amount transferred.
	Paid github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,1,rep,name=paid,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"paid"`
	// beneficiary is the address that was paid.
	Beneficiary string `protobuf:"bytes,2,opt,name=beneficiary,proto3" json:"beneficiary,omitempty"`
}

func (m *MsgClaimFounderRevenueResponse) Reset()         { *m = MsgClaimFounderRevenueResponse{} }
func (m *MsgClaimFounderRevenueResponse) String() string { return proto.CompactTextString(m) }
func (*MsgClaimFounderRevenueResponse) ProtoMessage()    {}
func (*MsgClaimFounderRevenueResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a87c077b09b3ec9b, []int{3}
}
func (m *MsgClaimFounderRevenueResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgClaimFounderRevenueResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgClaimFounderRevenueResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgClaimFounderRevenueResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgClaimFounderRevenueResponse.Merge(m, src)
}
func (m *MsgClaimFounderRevenueResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgClaimFounderRevenueResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgClaimFounderRevenueResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgClaimFounderRevenueResponse proto.InternalMessageInfo

func (m *MsgClaimFounderRevenueResponse) GetPaid() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.Paid
	}
	return nil
}

func (m *MsgClaimFounderRevenueResponse) GetBeneficiary() string {
	if m != nil {
		return m.Beneficiary
	}
	return ""
}

func init() {
	proto.RegisterType((*MsgUpdateParams)(nil), "hashgram.founder.v1.MsgUpdateParams")
	proto.RegisterType((*MsgUpdateParamsResponse)(nil), "hashgram.founder.v1.MsgUpdateParamsResponse")
	proto.RegisterType((*MsgClaimFounderRevenue)(nil), "hashgram.founder.v1.MsgClaimFounderRevenue")
	proto.RegisterType((*MsgClaimFounderRevenueResponse)(nil), "hashgram.founder.v1.MsgClaimFounderRevenueResponse")
}

func init() { proto.RegisterFile("hashgram/founder/v1/tx.proto", fileDescriptor_a87c077b09b3ec9b) }

var fileDescriptor_a87c077b09b3ec9b = []byte{
	// 516 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0xbf, 0x6f, 0x13, 0x31,
	0x18, 0x8d, 0x69, 0x89, 0x54, 0x07, 0x09, 0x71, 0xad, 0x68, 0x72, 0xa0, 0x4b, 0x88, 0x18, 0xa2,
	0xd0, 0x9e, 0x49, 0x2a, 0x90, 0xc8, 0x46, 0x2a, 0x75, 0x8b, 0x84, 0x0e, 0xb1, 0xb0, 0x20, 0x5f,
	0xce, 0x75, 0x2c, 0xb8, 0xf3, 0xe9, 0x3e, 0x27, 0x34, 0x62, 0x41, 0x8c, 0x4c, 0xfc, 0x19, 0x88,
	0x29, 0x03, 0x03, 0x33, 0x53, 0xc7, 0x8a, 0x89, 0x09, 0x50, 0x32, 0x44, 0xfc, 0x17, 0xe8, 0x7c,
	0xce, 0xb5, 0x94, 0xe3, 0xd7, 0x72, 0x67, 0xfb, 0x3d, 0xbf, 0xef, 0xf9, 0x7b, 0x36, 0xbe, 0x3e,
	0xa2, 0x30, 0xe2, 0x09, 0x0d, 0xc9, 0xa1, 0x1c, 0x47, 0x01, 0x4b, 0xc8, 0xa4, 0x43, 0xd4, 0x91,
	0x1b, 0x27, 0x52, 0x49, 0x6b, 0x73, 0x85, 0xba, 0x06, 0x75, 0x27, 0x1d, 0xfb, 0x0a, 0x0d, 0x45,
	0x24, 0x89, 0xfe, 0x66, 0x3c, 0xdb, 0x19, 0x4a, 0x08, 0x25, 0x10, 0x9f, 0x02, 0x23, 0x93, 0x8e,
	0xcf, 0x14, 0xed, 0x90, 0xa1, 0x14, 0x91, 0xc1, 0xb7, 0x0d, 0x1e, 0x02, 0x4f, 0xf5, 0x43, 0xe0,
	0x06, 0xa8, 0x65, 0xc0, 0x13, 0x3d, 0x23, 0xd9, 0xc4, 0x40, 0x5b, 0x5c, 0x72, 0x99, 0xad, 0xa7,
	0x23, 0xb3, 0x7a, 0xa3, 0xc8, 0xef, 0xca, 0x9c, 0xa6, 0x34, 0x3f, 0x20, 0x7c, 0x79, 0x00, 0xfc,
	0x51, 0x1c, 0x50, 0xc5, 0x1e, 0xd0, 0x84, 0x86, 0x60, 0xdd, 0xc5, 0x1b, 0x74, 0xac, 0x46, 0x32,
	0x11, 0x6a, 0x5a, 0x45, 0x0d, 0xd4, 0xda, 0xe8, 0x57, 0x3f, 0xbd, 0xdf, 0xdd, 0x32, 0x15, 0xef,
	0x07, 0x41, 0xc2, 0x00, 0x1e, 0xaa, 0x44, 0x44, 0xdc, 0x3b, 0xa5, 0x5a, 0xf7, 0x70, 0x39, 0xd6,
	0x0a, 0xd5, 0x0b, 0x0d, 0xd4, 0xaa, 0x74, 0xaf, 0xb9, 0x05, 0x1d, 0x71, 0xb3, 0x22, 0xfd, 0xf5,
	0xe3, 0x2f, 0xf5, 0x92, 0x67, 0x36, 0xf4, 0xba, 0xaf, 0x96, 0xb3, 0xf6, 0xa9, 0xd4, 0xeb, 0xe5,
	0xac, 0x5d, 0xcf, 0xcd, 0xe7, 0xfe, 0x0e, 0x32, 0x95, 0x4c, 0xa1, 0x59, 0xc3, 0xdb, 0xe7, 0x9c,
	0x7b, 0x0c, 0x62, 0x19, 0x01, 0x6b, 0xbe, 0xc0, 0x57, 0x07, 0xc0, 0xf7, 0x9f, 0x51, 0x11, 0x9a,
	0x3d, 0x1e, 0x9b, 0xb0, 0x68, 0xcc, 0xac, 0xdb, 0xb8, 0x0c, 0x2c, 0x5d, 0xf8, 0xeb, 0xc1, 0x0c,
	0xaf, 0x47, 0x52, 0x6b, 0x66, 0xf2, 0x8b, 0xaf, 0x82, 0x12, 0xcd, 0x8f, 0x08, 0x3b, 0xc5, 0xd0,
	0xca, 0x9f, 0x15, 0xe0, 0xf5, 0x98, 0x8a, 0xa0, 0x8a, 0x1a, 0x6b, 0xad, 0x4a, 0xb7, 0xe6, 0x1a,
	0x03, 0xe9, 0x8d, 0x70, 0xcd, 0x8d, 0x70, 0xf7, 0xa5, 0x88, 0xfa, 0x77, 0xd2, 0x2e, 0xbd, 0xfb,
	0x5a, 0x6f, 0x71, 0xa1, 0x46, 0x63, 0xdf, 0x1d, 0xca, 0xd0, 0x04, 0x6f, 0x7e, 0xbb, 0x10, 0x3c,
	0x25, 0x6a, 0x1a, 0x33, 0xd0, 0x1b, 0xe0, 0xed, 0x72, 0xd6, 0x46, 0x9e, 0x56, 0xb7, 0x7a, 0xb8,
	0xe2, 0xb3, 0x88, 0x1d, 0x8a, 0xa1, 0xa0, 0xc9, 0x54, 0x87, 0xf2, 0xa7, 0x03, 0x9f, 0x25, 0x77,
	0xbf, 0x23, 0xbc, 0x36, 0x00, 0x6e, 0xf9, 0xf8, 0xd2, 0x4f, 0x77, 0xe3, 0x66, 0x61, 0xa6, 0xe7,
	0x72, 0xb0, 0x77, 0xfe, 0x85, 0x95, 0x77, 0xe3, 0x39, 0xde, 0x2c, 0x8a, 0xea, 0xd6, 0xef, 0x44,
	0x0a, 0xc8, 0xf6, 0xde, 0x7f, 0x90, 0x57, 0x85, 0xed, 0x8b, 0x2f, 0xd3, 0x6e, 0xf5, 0x0f, 0x8e,
	0xe7, 0x0e, 0x3a, 0x99, 0x3b, 0xe8, 0xdb, 0xdc, 0x41, 0x6f, 0x16, 0x4e, 0xe9, 0x64, 0xe1, 0x94,
	0x3e, 0x2f, 0x9c, 0xd2, 0xe3, 0x9d, 0x33, 0x6d, 0xcf, 0x63, 0xcf, 0x07, 0x47, 0xf9, 0xb3, 0xd2,
	0x01, 0xf8, 0x65, 0xfd, 0xa4, 0xf6, 0x7e, 0x04, 0x00, 0x00, 0xff, 0xff, 0x79, 0x24, 0x1e, 0xc1,
	0x27, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// UpdateParams changes the Founder revenue configuration.
	//
	// The only valid authority is the governance module account. There is no
	// founder key, admin key or operator key that can call this.
	UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error)
	// ClaimFounderRevenue pushes accrued revenue to the configured beneficiary.
	//
	// Deliberately permissionless: any address may send it, and the funds always
	// go to the configured beneficiary regardless of who sent it. This is what
	// makes "the Founder private key is never needed on a Hashgram server" true
	// in practice rather than only in principle. The sender pays the gas.
	ClaimFounderRevenue(ctx context.Context, in *MsgClaimFounderRevenue, opts ...grpc.CallOption) (*MsgClaimFounderRevenueResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error) {
	out := new(MsgUpdateParamsResponse)
	err := c.cc.Invoke(ctx, "/hashgram.founder.v1.Msg/UpdateParams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) ClaimFounderRevenue(ctx context.Context, in *MsgClaimFounderRevenue, opts ...grpc.CallOption) (*MsgClaimFounderRevenueResponse, error) {
	out := new(MsgClaimFounderRevenueResponse)
	err := c.cc.Invoke(ctx, "/hashgram.founder.v1.Msg/ClaimFounderRevenue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// UpdateParams changes the Founder revenue configuration.
	//
	// The only valid authority is the governance module account. There is no
	// founder key, admin key or operator key that can call this.
	UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error)
	// ClaimFounderRevenue pushes accrued revenue to the configured beneficiary.
	//
	// Deliberately permissionless: any address may send it, and the funds always
	// go to the configured beneficiary regardless of who sent it. This is what
	// makes "the Founder private key is never needed on a Hashgram server" true
	// in practice rather than only in principle. The sender pays the gas.
	ClaimFounderRevenue(context.Context, *MsgClaimFounderRevenue) (*MsgClaimFounderRevenueResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) UpdateParams(ctx context.Context, req *MsgUpdateParams) (*MsgUpdateParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateParams not implemented")
}
func (*UnimplementedMsgServer) ClaimFounderRevenue(ctx context.Context, req *MsgClaimFounderRevenue) (*MsgClaimFounderRevenueResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClaimFounderRevenue not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_UpdateParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hashgram.founder.v1.Msg/UpdateParams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateParams(ctx, req.(*MsgUpdateParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_ClaimFounderRevenue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgClaimFounderRevenue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ClaimFounderRevenue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hashgram.founder.v1.Msg/ClaimFounderRevenue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ClaimFounderRevenue(ctx, req.(*MsgClaimFounderRevenue))
	}
	return interceptor(ctx, in, info, handler)
}

var Msg_serviceDesc = _Msg_serviceDesc
var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "hashgram.founder.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateParams",
			Handler:    _Msg_UpdateParams_Handler,
		},
		{
			MethodName: "ClaimFounderRevenue",
			Handler:    _Msg_ClaimFounderRevenue_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hashgram/founder/v1/tx.proto",
}

func (m *MsgUpdateParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgClaimFounderRevenue) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgClaimFounderRevenue) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgClaimFounderRevenue) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Sender) > 0 {
		i -= len(m.Sender)
		copy(dAtA[i:], m.Sender)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Sender)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgClaimFounderRevenueResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgClaimFounderRevenueResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgClaimFounderRevenueResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Beneficiary) > 0 {
		i -= len(m.Beneficiary)
		copy(dAtA[i:], m.Beneficiary)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Beneficiary)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Paid) > 0 {
		for iNdEx := len(m.Paid) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Paid[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgUpdateParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.Params.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgUpdateParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgClaimFounderRevenue) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Sender)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgClaimFounderRevenueResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Paid) > 0 {
		for _, e := range m.Paid {
			l = e.Size()
			n += 1 + l + sovTx(uint64(l))
		}
	}
	l = len(m.Beneficiary)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgUpdateParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgClaimFounderRevenue) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgClaimFounderRevenue: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgClaimFounderRevenue: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgClaimFounderRevenueResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgClaimFounderRevenueResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgClaimFounderRevenueResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Paid", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Paid = append(m.Paid, types.Coin{})
			if err := m.Paid[len(m.Paid)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Beneficiary", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Beneficiary = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
