// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: hashgram/treasury/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryReservesRequest struct {
}

func (m *QueryReservesRequest) Reset()         { *m = QueryReservesRequest{} }
func (m *QueryReservesRequest) String() string { return proto.CompactTextString(m) }
func (*QueryReservesRequest) ProtoMessage()    {}
func (*QueryReservesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f00a508135c632e, []int{0}
}
func (m *QueryReservesRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryReservesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryReservesRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryReservesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryReservesRequest.Merge(m, src)
}
func (m *QueryReservesRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryReservesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryReservesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryReservesRequest proto.InternalMessageInfo

type QueryReservesResponse struct {
	Reserves []ReserveInfo `protobuf:"bytes,1,rep,name=reserves,proto3" json:"reserves"`
}

func (m *QueryReservesResponse) Reset()         { *m = QueryReservesResponse{} }
func (m *QueryReservesResponse) String() string { return proto.CompactTextString(m) }
func (*QueryReservesResponse) ProtoMessage()    {}
func (*QueryReservesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f00a508135c632e, []int{1}
}
func (m *QueryReservesResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryReservesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryReservesResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryReservesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryReservesResponse.Merge(m, src)
}
func (m *QueryReservesResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryReservesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryReservesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryReservesResponse proto.InternalMessageInfo

func (m *QueryReservesResponse) GetReserves() []ReserveInfo {
	if m != nil {
		return m.Reserves
	}
	return nil
}

// ReserveInfo pairs a reserve's record with its live on-chain balance.
//
// The balance comes from the bank rather than from a counter, so it cannot
// drift away from reality, and it is cross-checkable with a plain bank query
// against the reported address.
type ReserveInfo struct {
	Reserve Reserve                                  `protobuf:"bytes,1,opt,name=reserve,proto3" json:"reserve"`
	Address string                                   `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Balance github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,3,rep,name=balance,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"balance"`
}

func (m *ReserveInfo) Reset()         { *m = ReserveInfo{} }
func (m *ReserveInfo) String() string { return proto.CompactTextString(m) }
func (*ReserveInfo) ProtoMessage()    {}
func (*ReserveInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f00a508135c632e, []int{2}
}
func (m *ReserveInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ReserveInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ReserveInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ReserveInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReserveInfo.Merge(m, src)
}
func (m *ReserveInfo) XXX_Size() int {
	return m.Size()
}
func (m *ReserveInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ReserveInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ReserveInfo proto.InternalMessageInfo

func (m *ReserveInfo) GetReserve() Reserve {
	if m != nil {
		return m.Reserve
	}
	return Reserve{}
}

func (m *ReserveInfo) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *ReserveInfo) GetBalance() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.Balance
	}
	return nil
}

type QueryReserveRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (m *QueryReserveRequest) Reset()         { *m = QueryReserveRequest{} }
func (m *QueryReserveRequest) String() string { return proto.CompactTextString(m) }
func (*QueryReserveRequest) ProtoMessage()    {}
func (*QueryReserveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f00a508135c632e, []int{3}
}
func (m *QueryReserveRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryReserveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryReserveRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryReserveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryReserveRequest.Merge(m, src)
}
func (m *QueryReserveRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryReserveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryReserveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryReserveRequest proto.InternalMessageInfo

func (m *QueryReserveRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type QueryReserveResponse struct {
	Found   bool        `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Reserve ReserveInfo `protobuf:"bytes,2,opt,name=reserve,proto3" json:"reserve"`
}

func (m *QueryReserveResponse) Reset()         { *m = QueryReserveResponse{} }
func (m *QueryReserveResponse) String() string { return proto.CompactTextString(m) }
func (*QueryReserveResponse) ProtoMessage()    {}
func (*QueryReserveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f00a508135c632e, []int{4}
}
func (m *QueryReserveResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryReserveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryReserveResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryReserveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryReserveResponse.Merge(m, src)
}
func (m *QueryReserveResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryReserveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryReserveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryReserveResponse proto.InternalMessageInfo

func (m *QueryReserveResponse) GetFound() bool {
	if m != nil {
		return m.Found
	}
	return false
}

func (m *QueryReserveResponse) GetReserve() ReserveInfo {
	if m != nil {
		return m.Reserve
	}
	return ReserveInfo{}
}

type QueryDisbursementsRequest struct {
	// reserve optionally filters to one allocation.
	Reserve string `protobuf:"bytes,1,opt,name=reserve,proto3" json:"reserve,omitempty"`
}

func (m *QueryDisbursementsRequest) Reset()         { *m = QueryDisbursementsRequest{} }
func (m *QueryDisbursementsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryDisbursementsRequest) ProtoMessage()    {}
func (*QueryDisbursementsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f00a508135c632e, []int{5}
}
func (m *QueryDisbursementsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryDisbursementsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryDisbursementsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryDisbursementsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDisbursementsRequest.Merge(m, src)
}
func (m *QueryDisbursementsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryDisbursementsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDisbursementsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDisbursementsRequest proto.InternalMessageInfo

func (m *QueryDisbursementsRequest) GetReserve() string {
	if m != nil {
		return m.Reserve
	}
	return ""
}

type QueryDisbursementsResponse struct {
	Disbursements []Disbursement `protobuf:"bytes,1,rep,name=disbursements,proto3" json:"disbursements"`
}

func (m *QueryDisbursementsResponse) Reset()         { *m = QueryDisbursementsResponse{} }
func (m *QueryDisbursementsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryDisbursementsResponse) ProtoMessage()    {}
func (*QueryDisbursementsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f00a508135c632e, []int{6}
}
func (m *QueryDisbursementsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryDisbursementsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryDisbursementsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryDisbursementsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDisbursementsResponse.Merge(m, src)
}
func (m *QueryDisbursementsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryDisbursementsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDisbursementsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDisbursementsResponse proto.InternalMessageInfo

func (m *QueryDisbursementsResponse) GetDisbursements() []Disbursement {
	if m != nil {
		return m.Disbursements
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryReservesRequest)(nil), "hashgram.treasury.v1.QueryReservesRequest")
	proto.RegisterType((*QueryReservesResponse)(nil), "hashgram.treasury.v1.QueryReservesResponse")
	proto.RegisterType((*ReserveInfo)(nil), "hashgram.treasury.v1.ReserveInfo")
	proto.RegisterType((*QueryReserveRequest)(nil), "hashgram.treasury.v1.QueryReserveRequest")
	proto.RegisterType((*QueryReserveResponse)(nil), "hashgram.treasury.v1.QueryReserveResponse")
	proto.RegisterType((*QueryDisbursementsRequest)(nil), "hashgram.treasury.v1.QueryDisbursementsRequest")
	proto.RegisterType((*QueryDisbursementsResponse)(nil), "hashgram.treasury.v1.QueryDisbursementsResponse")
}

func init() { proto.RegisterFile("hashgram/treasury/v1/query.proto", fileDescriptor_5f00a508135c632e) }

var fileDescriptor_5f00a508135c632e = []byte{
	// 612 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0xcf, 0x8f, 0x12, 0x31,
	0x14, 0xa6, 0xfb, 0x43, 0x96, 0x92, 0x3d, 0x58, 0xd1, 0x0c, 0x44, 0x67, 0x71, 0x56, 0x37, 0x2c,
	0x2b, 0x53, 0xc1, 0xec, 0xd1, 0xc3, 0xb2, 0x26, 0xc6, 0x8b, 0x89, 0xe3, 0xcd, 0x98, 0x98, 0x0e,
	0x74, 0x87, 0x51, 0xa6, 0x65, 0xa7, 0x33, 0x44, 0x62, 0xbc, 0x78, 0x35, 0x31, 0x26, 0xfe, 0x01,
	0x5e, 0x8d, 0x27, 0x0f, 0xfe, 0x11, 0x1c, 0x37, 0x7a, 0xf1, 0xa4, 0x06, 0x4c, 0xbc, 0xf8, 0x47,
	0x18, 0x3a, 0x2d, 0x3f, 0xcc, 0x04, 0xb9, 0x40, 0xdb, 0xf7, 0x7d, 0xef, 0x7d, 0x7d, 0xdf, 0xeb,
	0xc0, 0x72, 0x87, 0x88, 0x8e, 0x17, 0x92, 0x00, 0x47, 0x21, 0x25, 0x22, 0x0e, 0x07, 0xb8, 0x5f,
	0xc7, 0xa7, 0x31, 0x0d, 0x07, 0x76, 0x2f, 0xe4, 0x11, 0x47, 0x05, 0x8d, 0xb0, 0x35, 0xc2, 0xee,
	0xd7, 0x4b, 0xe7, 0x49, 0xe0, 0x33, 0x8e, 0xe5, 0x6f, 0x02, 0x2c, 0x99, 0x2d, 0x2e, 0x02, 0x2e,
	0xb0, 0x4b, 0x04, 0xc5, 0xfd, 0xba, 0x4b, 0x23, 0x52, 0xc7, 0x2d, 0xee, 0x33, 0x15, 0x2f, 0x26,
	0xf1, 0x27, 0x72, 0x87, 0x93, 0x8d, 0x0a, 0x15, 0x3c, 0xee, 0xf1, 0xe4, 0x7c, 0xb2, 0x52, 0xa7,
	0x97, 0x3d, 0xce, 0xbd, 0x2e, 0xc5, 0xa4, 0xe7, 0x63, 0xc2, 0x18, 0x8f, 0x48, 0xe4, 0x73, 0xa6,
	0x39, 0xbb, 0xa9, 0xca, 0xa7, 0x1a, 0x25, 0xc8, 0xba, 0x04, 0x0b, 0x0f, 0x26, 0x77, 0x71, 0xa8,
	0xa0, 0x61, 0x9f, 0x0a, 0x87, 0x9e, 0xc6, 0x54, 0x44, 0xd6, 0x63, 0x78, 0xf1, 0x9f, 0x73, 0xd1,
	0xe3, 0x4c, 0x50, 0x74, 0x0c, 0xb7, 0x42, 0x75, 0x66, 0x80, 0xf2, 0x7a, 0x25, 0xdf, 0xb8, 0x6a,
	0xa7, 0x35, 0xc0, 0x56, 0xcc, 0x7b, 0xec, 0x84, 0x37, 0x37, 0x86, 0xdf, 0x77, 0x32, 0xce, 0x94,
	0x68, 0xfd, 0x01, 0x30, 0x3f, 0x17, 0x47, 0xb7, 0x61, 0x56, 0xc5, 0x0c, 0x50, 0x06, 0x95, 0x7c,
	0xe3, 0xca, 0xd2, 0x9c, 0x2a, 0x9f, 0xe6, 0xa0, 0x06, 0xcc, 0x92, 0x76, 0x3b, 0xa4, 0x42, 0x18,
	0x6b, 0x65, 0x50, 0xc9, 0x35, 0x8d, 0x2f, 0x9f, 0x6b, 0x05, 0xd5, 0xc0, 0xa3, 0x24, 0xf2, 0x30,
	0x0a, 0x7d, 0xe6, 0x39, 0x1a, 0x88, 0x9e, 0xc2, 0xac, 0x4b, 0xba, 0x84, 0xb5, 0xa8, 0xb1, 0x2e,
	0xaf, 0x51, 0xb4, 0x15, 0x61, 0x62, 0x8f, 0xad, 0xec, 0xb1, 0x8f, 0xb9, 0xcf, 0x9a, 0x87, 0x93,
	0x72, 0x1f, 0x7f, 0xec, 0x54, 0x3c, 0x3f, 0xea, 0xc4, 0xae, 0xdd, 0xe2, 0x81, 0xb2, 0x47, 0xfd,
	0xd5, 0x44, 0xfb, 0x19, 0x8e, 0x06, 0x3d, 0x2a, 0x24, 0x41, 0x7c, 0xf8, 0xfd, 0xa9, 0x0a, 0x1c,
	0x5d, 0xc0, 0xda, 0x87, 0x17, 0xe6, 0x9b, 0xa9, 0x7a, 0x8c, 0x10, 0xdc, 0x60, 0x24, 0x48, 0xae,
	0x9c, 0x73, 0xe4, 0xda, 0xe2, 0x8b, 0x7e, 0x4c, 0xdb, 0x5e, 0x80, 0x9b, 0x27, 0x3c, 0x66, 0x6d,
	0x09, 0xde, 0x72, 0x92, 0x0d, 0x3a, 0x9a, 0xf5, 0x6d, 0x4d, 0xf6, 0x6d, 0x65, 0x2f, 0x34, 0xcf,
	0x3a, 0x84, 0x45, 0x59, 0xf0, 0x8e, 0x2f, 0xdc, 0x38, 0x14, 0x34, 0xa0, 0x2c, 0xd2, 0x53, 0x80,
	0x8c, 0x45, 0x5f, 0x72, 0x33, 0x5a, 0x17, 0x96, 0xd2, 0x68, 0x4a, 0xed, 0x7d, 0xb8, 0xdd, 0x9e,
	0x0f, 0xa8, 0x49, 0xb1, 0xd2, 0xd5, 0xcd, 0xe7, 0x50, 0xf2, 0x16, 0xe9, 0x8d, 0xe1, 0x3a, 0xdc,
	0x94, 0xe5, 0xd0, 0x6b, 0x00, 0xb7, 0xf4, 0x4c, 0xa2, 0x6a, 0x7a, 0xbe, 0xb4, 0x81, 0x2e, 0x1d,
	0xac, 0x84, 0x4d, 0xf4, 0x5b, 0x7b, 0xaf, 0xbe, 0xfe, 0x7a, 0xb7, 0x56, 0x46, 0x26, 0x4e, 0x7d,
	0x43, 0x7a, 0x8e, 0xd1, 0x1b, 0x00, 0xb3, 0x8a, 0x8c, 0xf6, 0xff, 0x5f, 0x40, 0x6b, 0xa9, 0xae,
	0x02, 0x55, 0x52, 0x6e, 0x48, 0x29, 0x7b, 0xe8, 0xda, 0x52, 0x29, 0xf8, 0xc5, 0x64, 0x7a, 0x5e,
	0xa2, 0xf7, 0x00, 0x6e, 0x2f, 0x58, 0x82, 0xf0, 0x92, 0x5a, 0x69, 0x9e, 0x97, 0x6e, 0xae, 0x4e,
	0x50, 0x12, 0x0f, 0xa4, 0xc4, 0xeb, 0x68, 0x37, 0x5d, 0xe2, 0x82, 0x95, 0xcd, 0xbb, 0xc3, 0x91,
	0x09, 0xce, 0x46, 0x26, 0xf8, 0x39, 0x32, 0xc1, 0xdb, 0xb1, 0x99, 0x39, 0x1b, 0x9b, 0x99, 0x6f,
	0x63, 0x33, 0xf3, 0xa8, 0x36, 0xf7, 0xba, 0xa6, 0x89, 0xa6, 0x8b, 0xe7, 0xb3, 0x9c, 0xf2, 0xa1,
	0xb9, 0xe7, 0xe4, 0x07, 0xec, 0xd6, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x73, 0xa5, 0xbf, 0xae,
	0xa1, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Reserves returns every named allocation with its live balance.
	Reserves(ctx context.Context, in *QueryReservesRequest, opts ...grpc.CallOption) (*QueryReservesResponse, error)
	// Reserve returns one named allocation.
	Reserve(ctx context.Context, in *QueryReserveRequest, opts ...grpc.CallOption) (*QueryReserveResponse, error)
	// Disbursements returns the governance spend history.
	Disbursements(ctx context.Context, in *QueryDisbursementsRequest, opts ...grpc.CallOption) (*QueryDisbursementsResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Reserves(ctx context.Context, in *QueryReservesRequest, opts ...grpc.CallOption) (*QueryReservesResponse, error) {
	out := new(QueryReservesResponse)
	err := c.cc.Invoke(ctx, "/hashgram.treasury.v1.Query/Reserves", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Reserve(ctx context.Context, in *QueryReserveRequest, opts ...grpc.CallOption) (*QueryReserveResponse, error) {
	out := new(QueryReserveResponse)
	err := c.cc.Invoke(ctx, "/hashgram.treasury.v1.Query/Reserve", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Disbursements(ctx context.Context, in *QueryDisbursementsRequest, opts ...grpc.CallOption) (*QueryDisbursementsResponse, error) {
	out := new(QueryDisbursementsResponse)
	err := c.cc.Invoke(ctx, "/hashgram.treasury.v1.Query/Disbursements", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Reserves returns every named allocation with its live balance.
	Reserves(context.Context, *QueryReservesRequest) (*QueryReservesResponse, error)
	// Reserve returns one named allocation.
	Reserve(context.Context, *QueryReserveRequest) (*QueryReserveResponse, error)
	// Disbursements returns the governance spend history.
	Disbursements(context.Context, *QueryDisbursementsRequest) (*QueryDisbursementsResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Reserves(ctx context.Context, req *QueryReservesRequest) (*QueryReservesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Reserves not implemented")
}
func (*UnimplementedQueryServer) Reserve(ctx context.Context, req *QueryReserveRequest) (*QueryReserveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Reserve not implemented")
}
func (*UnimplementedQueryServer) Disbursements(ctx context.Context, req *QueryDisbursementsRequest) (*QueryDisbursementsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Disbursements not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Reserves_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryReservesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Reserves(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hashgram.treasury.v1.Query/Reserves",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Reserves(ctx, req.(*QueryReservesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Reserve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryReserveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Reserve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hashgram.treasury.v1.Query/Reserve",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Reserve(ctx, req.(*QueryReserveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Disbursements_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryDisbursementsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Disbursements(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hashgram.treasury.v1.Query/Disbursements",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Disbursements(ctx, req.(*QueryDisbursementsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "hashgram.treasury.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Reserves",
			Handler:    _Query_Reserves_Handler,
		},
		{
			MethodName: "Reserve",
			Handler:    _Query_Reserve_Handler,
		},
		{
			MethodName: "Disbursements",
			Handler:    _Query_Disbursements_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hashgram/treasury/v1/query.proto",
}

func (m *QueryReservesRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryReservesRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryReservesRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryReservesResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryReservesResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryReservesResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Reserves) > 0 {
		for iNdEx := len(m.Reserves) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Reserves[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *ReserveInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ReserveInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ReserveInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Balance) > 0 {
		for iNdEx := len(m.Balance) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Balance[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0x12
	}
	{
		size, err := m.Reserve.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryReserveRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryReserveRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryReserveRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryReserveResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryReserveResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryReserveResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Reserve.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if m.Found {
		i--
		if m.Found {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryDisbursementsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryDisbursementsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryDisbursementsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Reserve) > 0 {
		i -= len(m.Reserve)
		copy(dAtA[i:], m.Reserve)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Reserve)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryDisbursementsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryDisbursementsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryDisbursementsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Disbursements) > 0 {
		for iNdEx := len(m.Disbursements) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Disbursements[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryReservesRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryReservesResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Reserves) > 0 {
		for _, e := range m.Reserves {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *ReserveInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Reserve.Size()
	n += 1 + l + sovQuery(uint64(l))
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if len(m.Balance) > 0 {
		for _, e := range m.Balance {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *QueryReserveRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryReserveResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Found {
		n += 2
	}
	l = m.Reserve.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryDisbursementsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Reserve)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryDisbursementsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Disbursements) > 0 {
		for _, e := range m.Disbursements {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryReservesRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryReservesRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryReservesRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryReservesResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryReservesResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryReservesResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reserves", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Reserves = append(m.Reserves, ReserveInfo{})
			if err := m.Reserves[len(m.Reserves)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ReserveInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ReserveInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ReserveInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reserve", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Reserve.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Balance", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Balance = append(m.Balance, types.Coin{})
			if err := m.Balance[len(m.Balance)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryReserveRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryReserveRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryReserveRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryReserveResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryReserveResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryReserveResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Found", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Found = bool(v != 0)
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reserve", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Reserve.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryDisbursementsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryDisbursementsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryDisbursementsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reserve", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Reserve = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryDisbursementsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryDisbursementsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryDisbursementsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Disbursements", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Disbursements = append(m.Disbursements, Disbursement{})
			if err := m.Disbursements[len(m.Disbursements)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
