// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: hashgram/serviceproof/v1/provider.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// ServiceRole is a kind of useful service a node can provide.
//
// Users call this "Hashgram Mining". Technically it is Proof of Useful
// Service: there is no pointless hashing, and nothing is rewarded for merely
// existing. Every role below is rewarded only against evidence that survives
// an adversarial reading.
type ServiceRole int32

const (
	SERVICE_ROLE_UNSPECIFIED ServiceRole = 0
	// SERVICE_ROLE_STORAGE stores encrypted blobs and answers retrieval
	// requests. Rewarded on verified byte-hours: bytes actually assigned to
	// this provider, held across epochs, scaled by challenge success. Declared
	// but unused disk earns nothing.
	SERVICE_ROLE_STORAGE ServiceRole = 1
	// SERVICE_ROLE_RELAY forwards encrypted envelopes for clients. Rewarded on
	// receipts signed by the clients that were served, never on the provider's
	// own counters.
	SERVICE_ROLE_RELAY ServiceRole = 2
	// SERVICE_ROLE_CALL provides TURN/SFU call infrastructure. Rewarded on
	// client-signed session receipts.
	SERVICE_ROLE_CALL ServiceRole = 3
	// SERVICE_ROLE_MEDIA serves media manifests and chunks. Rewarded on
	// client-signed retrieval receipts.
	SERVICE_ROLE_MEDIA ServiceRole = 4
)

var ServiceRole_name = map[int32]string{
	0: "SERVICE_ROLE_UNSPECIFIED",
	1: "SERVICE_ROLE_STORAGE",
	2: "SERVICE_ROLE_RELAY",
	3: "SERVICE_ROLE_CALL",
	4: "SERVICE_ROLE_MEDIA",
}

var ServiceRole_value = map[string]int32{
	"SERVICE_ROLE_UNSPECIFIED": 0,
	"SERVICE_ROLE_STORAGE":     1,
	"SERVICE_ROLE_RELAY":       2,
	"SERVICE_ROLE_CALL":        3,
	"SERVICE_ROLE_MEDIA":       4,
}

func (x ServiceRole) String() string {
	return proto.EnumName(ServiceRole_name, int32(x))
}

func (ServiceRole) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a4686e522843ca4d, []int{0}
}

// Provider is a registered useful-service node.
//
// Registration requires a bond. The bond is what makes fraud expensive: a
// provider that fails storage challenges or submits forged receipts loses
// part of it. Without a bond, the cost of being caught would be the cost of
// generating a new keypair.
type Provider struct {
	// operator is the address that registered and controls this provider.
	Operator string `protobuf:"bytes,1,opt,name=operator,proto3" json:"operator,omitempty"`
	// reward_address receives earned rewards. It may differ from the operator,
	// so a node running on a rented server does not need a key that can also
	// move the earnings. See docs/SECURITY.md on key separation.
	RewardAddress string `protobuf:"bytes,2,opt,name=reward_address,json=rewardAddress,proto3" json:"reward_address,omitempty"`
	// node_pubkey is the P2P identity key this provider signs receipts and
	// challenge responses with. Separate from the operator's account key so
	// that a compromised node cannot spend the operator's HASH.
	NodePubkey []byte `protobuf:"bytes,3,opt,name=node_pubkey,json=nodePubkey,proto3" json:"node_pubkey,omitempty"`
	// roles is what this provider offers.
	Roles []ServiceRole `protobuf:"varint,4,rep,packed,name=roles,proto3,enum=hashgram.serviceproof.v1.ServiceRole" json:"roles,omitempty"`
	// bond is the posted stake.
	Bond github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,5,rep,name=bond,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"bond"`
	// declared_storage_bytes is how much disk the operator says they have.
	//
	// It is advertising, not entitlement. It determines how much data the
	// network may assign, and nothing else. An operator who declares a
	// petabyte and is assigned nothing earns nothing.
	DeclaredStorageBytes uint64 `protobuf:"varint,6,opt,name=declared_storage_bytes,json=declaredStorageBytes,proto3" json:"declared_storage_bytes,omitempty"`
	// declared_bandwidth_bps is the advertised relay bandwidth limit. Same
	// status as declared_storage_bytes: it shapes what the network asks of the
	// node, not what the node is paid.
	DeclaredBandwidthBps uint64 `protobuf:"varint,7,opt,name=declared_bandwidth_bps,json=declaredBandwidthBps,proto3" json:"declared_bandwidth_bps,omitempty"`
	// registered_height is when this provider joined.
	RegisteredHeight int64 `protobuf:"varint,8,opt,name=registered_height,json=registeredHeight,proto3" json:"registered_height,omitempty"`
	// fraud_score accumulates on failed challenges and rejected evidence. Above
	// the configured threshold the provider is jailed and slashed.
	FraudScore uint32 `protobuf:"varint,9,opt,name=fraud_score,json=fraudScore,proto3" json:"fraud_score,omitempty"`
	// jailed providers earn nothing and receive no new assignments.
	Jailed bool `protobuf:"varint,10,opt,name=jailed,proto3" json:"jailed,omitempty"`
	// jailed_until_height is when the provider may request unjailing.
	JailedUntilHeight int64 `protobuf:"varint,11,opt,name=jailed_until_height,json=jailedUntilHeight,proto3" json:"jailed_until_height,omitempty"`
	// unbonding_height is set when the operator starts withdrawing. Zero means
	// the provider is active.
	UnbondingHeight int64 `protobuf:"varint,12,opt,name=unbonding_height,json=unbondingHeight,proto3" json:"unbonding_height,omitempty"`
	// moniker is a human-readable label.
	Moniker string `protobuf:"bytes,13,opt,name=moniker,proto3" json:"moniker,omitempty"`
}

func (m *Provider) Reset()         { *m = Provider{} }
func (m *Provider) String() string { return proto.CompactTextString(m) }
func (*Provider) ProtoMessage()    {}
func (*Provider) Descriptor() ([]byte, []int) {
	return fileDescriptor_a4686e522843ca4d, []int{0}
}
func (m *Provider) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Provider) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Provider.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Provider) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Provider.Merge(m, src)
}
func (m *Provider) XXX_Size() int {
	return m.Size()
}
func (m *Provider) XXX_DiscardUnknown() {
	xxx_messageInfo_Provider.DiscardUnknown(m)
}

var xxx_messageInfo_Provider proto.InternalMessageInfo

func (m *Provider) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *Provider) GetRewardAddress() string {
	if m != nil {
		return m.RewardAddress
	}
	return ""
}

func (m *Provider) GetNodePubkey() []byte {
	if m != nil {
		return m.NodePubkey
	}
	return nil
}

func (m *Provider) GetRoles() []ServiceRole {
	if m != nil {
		return m.Roles
	}
	return nil
}

func (m *Provider) GetBond() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.Bond
	}
	return nil
}

func (m *Provider) GetDeclaredStorageBytes() uint64 {
	if m != nil {
		return m.DeclaredStorageBytes
	}
	return 0
}

func (m *Provider) GetDeclaredBandwidthBps() uint64 {
	if m != nil {
		return m.DeclaredBandwidthBps
	}
	return 0
}

func (m *Provider) GetRegisteredHeight() int64 {
	if m != nil {
		return m.RegisteredHeight
	}
	return 0
}

func (m *Provider) GetFraudScore() uint32 {
	if m != nil {
		return m.FraudScore
	}
	return 0
}

func (m *Provider) GetJailed() bool {
	if m != nil {
		return m.Jailed
	}
	return false
}

func (m *Provider) GetJailedUntilHeight() int64 {
	if m != nil {
		return m.JailedUntilHeight
	}
	return 0
}

func (m *Provider) GetUnbondingHeight() int64 {
	if m != nil {
		return m.UnbondingHeight
	}
	return 0
}

func (m *Provider) GetMoniker() string {
	if m != nil {
		return m.Moniker
	}
	return ""
}

// Epoch is one accounting period.
//
// Work is credited during an epoch and settled at its end. Settling in
// batches rather than per receipt is what keeps the reward computation
// deterministic across nodes: every validator computes the same division of
// the same budget over the same credited work.
type Epoch struct {
	// number is the epoch index, starting at 0.
	Number uint64 `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	// start_height is the first block in this epoch.
	StartHeight int64 `protobuf:"varint,2,opt,name=start_height,json=startHeight,proto3" json:"start_height,omitempty"`
	// end_height is the last block in this epoch. Zero while the epoch is open.
	EndHeight int64 `protobuf:"varint,3,opt,name=end_height,json=endHeight,proto3" json:"end_height,omitempty"`
	// budget is the emission allocated to this epoch, computed from the
	// remaining reserve by a deterministic declining schedule.
	Budget github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,4,rep,name=budget,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"budget"`
	// distributed is what was actually paid out of budget.
	//
	// Unpaid budget is not burned or lost: it simply stays in the reserve and
	// is available to later epochs. An early network with few providers
	// therefore does not waste the reserve.
	Distributed github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,5,rep,name=distributed,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"distributed"`
	// settled is true once this epoch's rewards have been computed and paid.
	Settled bool `protobuf:"varint,6,opt,name=settled,proto3" json:"settled,omitempty"`
	// total_credit is the sum of all providers' credited work in this epoch, in
	// abstract credit units. Rewards are budget * provider_credit / total_credit.
	TotalCredit cosmossdk_io_math.Int `protobuf:"bytes,7,opt,name=total_credit,json=totalCredit,proto3,customtype=cosmossdk.io/math.Int" json:"total_credit"`
}

func (m *Epoch) Reset()         { *m = Epoch{} }
func (m *Epoch) String() string { return proto.CompactTextString(m) }
func (*Epoch) ProtoMessage()    {}
func (*Epoch) Descriptor() ([]byte, []int) {
	return fileDescriptor_a4686e522843ca4d, []int{1}
}
func (m *Epoch) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Epoch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Epoch.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Epoch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Epoch.Merge(m, src)
}
func (m *Epoch) XXX_Size() int {
	return m.Size()
}
func (m *Epoch) XXX_DiscardUnknown() {
	xxx_messageInfo_Epoch.DiscardUnknown(m)
}

var xxx_messageInfo_Epoch proto.InternalMessageInfo

func (m *Epoch) GetNumber() uint64 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *Epoch) GetStartHeight() int64 {
	if m != nil {
		return m.StartHeight
	}
	return 0
}

func (m *Epoch) GetEndHeight() int64 {
	if m != nil {
		return m.EndHeight
	}
	return 0
}

func (m *Epoch) GetBudget() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.Budget
	}
	return nil
}

func (m *Epoch) GetDistributed() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.Distributed
	}
	return nil
}

func (m *Epoch) GetSettled() bool {
	if m != nil {
		return m.Settled
	}
	return false
}

// ProviderEpochCredit is one provider's credited work in one epoch.
//
// Credit is deliberately kept as separate per-role figures until settlement,
// so that "this node was paid for relay work it never did" is answerable from
// state rather than from a single opaque number.
type ProviderEpochCredit struct {
	Operator string `protobuf:"bytes,1,opt,name=operator,proto3" json:"operator,omitempty"`
	Epoch    uint64 `protobuf:"varint,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
	// storage_credit is verified byte-hours, scaled.
	StorageCredit cosmossdk_io_math.Int `protobuf:"bytes,3,opt,name=storage_credit,json=storageCredit,proto3,customtype=cosmossdk.io/math.Int" json:"storage_credit"`
	// relay_credit is from client-signed relay receipts.
	RelayCredit cosmossdk_io_math.Int `protobuf:"bytes,4,opt,name=relay_credit,json=relayCredit,proto3,customtype=cosmossdk.io/math.Int" json:"relay_credit"`
	// retrieval_credit is from client-signed retrieval receipts.
	RetrievalCredit cosmossdk_io_math.Int `protobuf:"bytes,5,opt,name=retrieval_credit,json=retrievalCredit,proto3,customtype=cosmossdk.io/math.Int" json:"retrieval_credit"`
	// call_credit is from client-signed call session receipts.
	CallCredit cosmossdk_io_math.Int `protobuf:"bytes,6,opt,name=call_credit,json=callCredit,proto3,customtype=cosmossdk.io/math.Int" json:"call_credit"`
	// challenges_issued and challenges_passed drive the storage success rate.
	ChallengesIssued uint64 `protobuf:"varint,7,opt,name=challenges_issued,json=challengesIssued,proto3" json:"challenges_issued,omitempty"`
	ChallengesPassed uint64 `protobuf:"varint,8,opt,name=challenges_passed,json=challengesPassed,proto3" json:"challenges_passed,omitempty"`
	// distinct_clients is how many different clients signed receipts for this
	// provider. Used with the concentration cap: work concentrated in a single
	// counterparty is discounted, which is what makes two nodes trading fake
	// traffic unprofitable.
	DistinctClients uint64 `protobuf:"varint,9,opt,name=distinct_clients,json=distinctClients,proto3" json:"distinct_clients,omitempty"`
	// paid is what was transferred at settlement.
	Paid github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,10,rep,name=paid,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"paid"`
}

func (m *ProviderEpochCredit) Reset()         { *m = ProviderEpochCredit{} }
func (m *ProviderEpochCredit) String() string { return proto.CompactTextString(m) }
func (*ProviderEpochCredit) ProtoMessage()    {}
func (*ProviderEpochCredit) Descriptor() ([]byte, []int) {
	return fileDescriptor_a4686e522843ca4d, []int{2}
}
func (m *ProviderEpochCredit) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ProviderEpochCredit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ProviderEpochCredit.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ProviderEpochCredit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProviderEpochCredit.Merge(m, src)
}
func (m *ProviderEpochCredit) XXX_Size() int {
	return m.Size()
}
func (m *ProviderEpochCredit) XXX_DiscardUnknown() {
	xxx_messageInfo_ProviderEpochCredit.DiscardUnknown(m)
}

var xxx_messageInfo_ProviderEpochCredit proto.InternalMessageInfo

func (m *ProviderEpochCredit) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *ProviderEpochCredit) GetEpoch() uint64 {
	if m != nil {
		return m.Epoch
	}
	return 0
}

func (m *ProviderEpochCredit) GetChallengesIssued() uint64 {
	if m != nil {
		return m.ChallengesIssued
	}
	return 0
}

func (m *ProviderEpochCredit) GetChallengesPassed() uint64 {
	if m != nil {
		return m.ChallengesPassed
	}
	return 0
}

func (m *ProviderEpochCredit) GetDistinctClients() uint64 {
	if m != nil {
		return m.DistinctClients
	}
	return 0
}

func (m *ProviderEpochCredit) GetPaid() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.Paid
	}
	return nil
}

func init() {
	proto.RegisterEnum("hashgram.serviceproof.v1.ServiceRole", ServiceRole_name, ServiceRole_value)
	proto.RegisterType((*Provider)(nil), "hashgram.serviceproof.v1.Provider")
	proto.RegisterType((*Epoch)(nil), "hashgram.serviceproof.v1.Epoch")
	proto.RegisterType((*ProviderEpochCredit)(nil), "hashgram.serviceproof.v1.ProviderEpochCredit")
}

func init() {
	proto.RegisterFile("hashgram/serviceproof/v1/provider.proto", fileDescriptor_a4686e522843ca4d)
}

var fileDescriptor_a4686e522843ca4d = []byte{
	// 955 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0x4f, 0x6f, 0xdc, 0x44,
	0x14, 0x5f, 0x77, 0xff, 0x34, 0x99, 0xcd, 0x9f, 0x8d, 0x9b, 0x46, 0x6e, 0x04, 0x9b, 0x25, 0x12,
	0x62, 0x69, 0x14, 0x5b, 0x29, 0xe5, 0xc4, 0x01, 0x65, 0xb7, 0x0b, 0xac, 0x58, 0xd2, 0xc8, 0x4b,
	0x2b, 0xc1, 0xc5, 0x1a, 0x7b, 0x5e, 0xed, 0x21, 0x5e, 0x8f, 0x35, 0x33, 0xbb, 0x25, 0xdf, 0x80,
	0x03, 0x07, 0xc4, 0x81, 0x2f, 0xc0, 0x05, 0x38, 0x71, 0xe8, 0x87, 0xe8, 0xb1, 0xea, 0x09, 0x71,
	0x28, 0x28, 0x39, 0xf0, 0x35, 0xd0, 0x8c, 0xc7, 0x9b, 0x2c, 0x08, 0xa1, 0x54, 0xca, 0x65, 0xd7,
	0xef, 0xf7, 0x7e, 0xef, 0xf7, 0x9e, 0xdf, 0x3c, 0x3f, 0x1b, 0xbd, 0x93, 0x60, 0x91, 0xc4, 0x1c,
	0x4f, 0x3c, 0x01, 0x7c, 0x46, 0x23, 0xc8, 0x39, 0x63, 0x4f, 0xbc, 0xd9, 0x81, 0x97, 0x73, 0x36,
	0xa3, 0x04, 0xb8, 0x9b, 0x73, 0x26, 0x99, 0xed, 0x94, 0x44, 0xf7, 0x32, 0xd1, 0x9d, 0x1d, 0x6c,
	0x6f, 0xe0, 0x09, 0xcd, 0x98, 0xa7, 0x7f, 0x0b, 0xf2, 0x76, 0x3b, 0x62, 0x62, 0xc2, 0x84, 0x17,
	0x62, 0x01, 0xde, 0xec, 0x20, 0x04, 0x89, 0x0f, 0xbc, 0x88, 0xd1, 0xcc, 0xf8, 0xef, 0x14, 0xfe,
	0x40, 0x5b, 0x5e, 0x61, 0x18, 0xd7, 0x66, 0xcc, 0x62, 0x56, 0xe0, 0xea, 0xaa, 0x40, 0x77, 0xbf,
	0xad, 0xa3, 0xa5, 0x63, 0x53, 0x90, 0x7d, 0x1f, 0x2d, 0xb1, 0x1c, 0x38, 0x96, 0x8c, 0x3b, 0x56,
	0xc7, 0xea, 0x2e, 0xf7, 0x9c, 0x97, 0xcf, 0xf6, 0x37, 0x8d, 0xcc, 0x21, 0x21, 0x1c, 0x84, 0x18,
	0x4b, 0x4e, 0xb3, 0xd8, 0x9f, 0x33, 0xed, 0x0f, 0xd1, 0x1a, 0x87, 0xa7, 0x98, 0x93, 0x00, 0x17,
	0x0c, 0xe7, 0xc6, 0xff, 0xc4, 0xae, 0x16, 0x7c, 0x03, 0xda, 0x3b, 0xa8, 0x99, 0x31, 0x02, 0x41,
	0x3e, 0x0d, 0x4f, 0xe0, 0xd4, 0xa9, 0x76, 0xac, 0xee, 0x8a, 0x8f, 0x14, 0x74, 0xac, 0x11, 0xfb,
	0x03, 0x54, 0xe7, 0x2c, 0x05, 0xe1, 0xd4, 0x3a, 0xd5, 0xee, 0xda, 0xbd, 0xb7, 0xdd, 0xff, 0x6a,
	0x99, 0x3b, 0x2e, 0x6c, 0x9f, 0xa5, 0xe0, 0x17, 0x31, 0x36, 0x41, 0xb5, 0x90, 0x65, 0xc4, 0xa9,
	0x77, 0xaa, 0xdd, 0xe6, 0xbd, 0x3b, 0xae, 0xa9, 0x48, 0x75, 0xd0, 0x35, 0x1d, 0x74, 0xfb, 0x8c,
	0x66, 0xbd, 0xf7, 0x9f, 0xbf, 0xda, 0xa9, 0xfc, 0xf2, 0xc7, 0x4e, 0x37, 0xa6, 0x32, 0x99, 0x86,
	0x6e, 0xc4, 0x26, 0xa6, 0x83, 0xe6, 0x6f, 0x5f, 0x90, 0x13, 0x4f, 0x9e, 0xe6, 0x20, 0x74, 0x80,
	0xf8, 0xe9, 0xaf, 0x5f, 0xef, 0x5a, 0xbe, 0x56, 0xb7, 0xef, 0xa3, 0x2d, 0x02, 0x51, 0x8a, 0x39,
	0x90, 0x40, 0x48, 0xc6, 0x71, 0x0c, 0x41, 0x78, 0x2a, 0x41, 0x38, 0x8d, 0x8e, 0xd5, 0xad, 0xf9,
	0x9b, 0xa5, 0x77, 0x5c, 0x38, 0x7b, 0xca, 0xb7, 0x10, 0x15, 0xe2, 0x8c, 0x3c, 0xa5, 0x44, 0x26,
	0x41, 0x98, 0x0b, 0xe7, 0xe6, 0x62, 0x54, 0xaf, 0x74, 0xf6, 0x72, 0x61, 0xef, 0xa1, 0x0d, 0x0e,
	0x31, 0x15, 0x12, 0x54, 0x5c, 0x02, 0x34, 0x4e, 0xa4, 0xb3, 0xd4, 0xb1, 0xba, 0x55, 0xbf, 0x75,
	0xe1, 0xf8, 0x44, 0xe3, 0xaa, 0xb9, 0x4f, 0x38, 0x9e, 0x92, 0x40, 0x44, 0x8c, 0x83, 0xb3, 0xdc,
	0xb1, 0xba, 0xab, 0x3e, 0xd2, 0xd0, 0x58, 0x21, 0xf6, 0x16, 0x6a, 0x7c, 0x85, 0x69, 0x0a, 0xc4,
	0x41, 0x1d, 0xab, 0xbb, 0xe4, 0x1b, 0xcb, 0x76, 0xd1, 0xad, 0xe2, 0x2a, 0x98, 0x66, 0x92, 0xa6,
	0x65, 0x9e, 0xa6, 0xce, 0xb3, 0x51, 0xb8, 0x1e, 0x29, 0x8f, 0x49, 0xf4, 0x2e, 0x6a, 0x4d, 0x33,
	0xd5, 0x0b, 0x9a, 0xc5, 0x25, 0x79, 0x45, 0x93, 0xd7, 0xe7, 0xb8, 0xa1, 0x3a, 0xe8, 0xe6, 0x84,
	0x65, 0xf4, 0x04, 0xb8, 0xb3, 0xaa, 0x46, 0xc5, 0x2f, 0xcd, 0xdd, 0x9f, 0xab, 0xa8, 0x3e, 0xc8,
	0x59, 0x94, 0xa8, 0xb2, 0xb2, 0xe9, 0x24, 0x84, 0x62, 0x12, 0x6b, 0xbe, 0xb1, 0xec, 0xb7, 0xd0,
	0x8a, 0x90, 0x98, 0xcb, 0x32, 0xc5, 0x0d, 0x9d, 0xa2, 0xa9, 0x31, 0x23, 0xff, 0x26, 0x42, 0x90,
	0xcd, 0x1b, 0x53, 0xd5, 0x84, 0x65, 0xc8, 0xca, 0x8e, 0x24, 0xa8, 0x11, 0x4e, 0x49, 0x0c, 0x52,
	0x8f, 0xd3, 0x75, 0x8c, 0x84, 0xd1, 0xb7, 0x39, 0x6a, 0x12, 0x2a, 0x24, 0xa7, 0xe1, 0x54, 0xc2,
	0xf5, 0x4d, 0xe0, 0xe5, 0x24, 0xaa, 0xb7, 0x02, 0xa4, 0x54, 0xe7, 0xd9, 0xd0, 0xe7, 0x59, 0x9a,
	0xf6, 0x11, 0x5a, 0x91, 0x4c, 0xe2, 0x34, 0x88, 0x38, 0x10, 0x2a, 0xf5, 0x88, 0x2d, 0xf7, 0xf6,
	0x54, 0xce, 0xdf, 0x5f, 0xed, 0xdc, 0x2e, 0x32, 0x08, 0x72, 0xe2, 0x52, 0xe6, 0x4d, 0xb0, 0x4c,
	0xdc, 0x61, 0x26, 0x5f, 0x3e, 0xdb, 0x47, 0xa6, 0xdc, 0x61, 0x26, 0xfd, 0xa6, 0x16, 0xe8, 0xeb,
	0xf8, 0xdd, 0x1f, 0xea, 0xe8, 0x56, 0xb9, 0x3a, 0xf4, 0x99, 0x15, 0xf8, 0x6b, 0x6e, 0x91, 0x4d,
	0x54, 0x07, 0x25, 0xa2, 0x0f, 0xb4, 0xe6, 0x17, 0x86, 0xed, 0xa3, 0xb5, 0xf2, 0x69, 0x32, 0x55,
	0x57, 0xaf, 0x5e, 0xf5, 0xaa, 0x91, 0x30, 0xf5, 0x1d, 0xa1, 0x15, 0x0e, 0x29, 0x3e, 0x2d, 0x15,
	0x6b, 0xaf, 0xd1, 0x07, 0x2d, 0x60, 0xf4, 0x1e, 0xa3, 0x16, 0x07, 0xc9, 0x29, 0xcc, 0x2e, 0x7a,
	0x5b, 0xbf, 0xba, 0xe6, 0xfa, 0x5c, 0xc4, 0xe8, 0x8e, 0x50, 0x33, 0xc2, 0xe9, 0x5c, 0xb2, 0x71,
	0x75, 0x49, 0xa4, 0xe2, 0x8d, 0xda, 0x1e, 0xda, 0x88, 0x12, 0x9c, 0xa6, 0x90, 0xc5, 0x20, 0x02,
	0x2a, 0xc4, 0x14, 0x88, 0xd9, 0x32, 0xad, 0x0b, 0xc7, 0x50, 0xe3, 0xff, 0x20, 0xe7, 0x58, 0x08,
	0x20, 0x7a, 0xc3, 0x2c, 0x90, 0x8f, 0x35, 0xae, 0x1e, 0x7c, 0x35, 0x80, 0x34, 0x8b, 0x64, 0x10,
	0xa5, 0x14, 0x32, 0x29, 0xf4, 0x9a, 0xa9, 0xf9, 0xeb, 0x25, 0xde, 0x2f, 0x60, 0xb5, 0x8b, 0x73,
	0x4c, 0xd5, 0xa6, 0xb9, 0xa6, 0x5d, 0xac, 0xd4, 0xef, 0x7e, 0x6f, 0xa1, 0xe6, 0xa5, 0x17, 0x81,
	0xfd, 0x06, 0x72, 0xc6, 0x03, 0xff, 0xf1, 0xb0, 0x3f, 0x08, 0xfc, 0x87, 0xa3, 0x41, 0xf0, 0xe8,
	0x68, 0x7c, 0x3c, 0xe8, 0x0f, 0x3f, 0x1a, 0x0e, 0x1e, 0xb4, 0x2a, 0xb6, 0x83, 0x36, 0x17, 0xbc,
	0xe3, 0xcf, 0x1f, 0xfa, 0x87, 0x1f, 0x0f, 0x5a, 0x96, 0xbd, 0x85, 0xec, 0x05, 0x8f, 0x3f, 0x18,
	0x1d, 0x7e, 0xd1, 0xba, 0x61, 0xdf, 0x46, 0x1b, 0x0b, 0x78, 0xff, 0x70, 0x34, 0x6a, 0x55, 0xff,
	0x45, 0xff, 0x6c, 0xf0, 0x60, 0x78, 0xd8, 0xaa, 0x6d, 0xd7, 0xbe, 0xf9, 0xb1, 0x5d, 0xe9, 0x7d,
	0xfa, 0xfc, 0xac, 0x6d, 0xbd, 0x38, 0x6b, 0x5b, 0x7f, 0x9e, 0xb5, 0xad, 0xef, 0xce, 0xdb, 0x95,
	0x17, 0xe7, 0xed, 0xca, 0x6f, 0xe7, 0xed, 0xca, 0x97, 0x07, 0x97, 0xee, 0x71, 0xfe, 0xd1, 0x30,
	0xbf, 0xf8, 0x7a, 0xf1, 0xfb, 0x41, 0xdf, 0x72, 0xd8, 0xd0, 0x2f, 0xef, 0xf7, 0xfe, 0x0e, 0x00,
	0x00, 0xff, 0xff, 0x98, 0xbf, 0x08, 0x38, 0x65, 0x08, 0x00, 0x00,
}

func (m *Provider) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Provider) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Provider) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Moniker) > 0 {
		i -= len(m.Moniker)
		copy(dAtA[i:], m.Moniker)
		i = encodeVarintProvider(dAtA, i, uint64(len(m.Moniker)))
		i--
		dAtA[i] = 0x6a
	}
	if m.UnbondingHeight != 0 {
		i = encodeVarintProvider(dAtA, i, uint64(m.UnbondingHeight))
		i--
		dAtA[i] = 0x60
	}
	if m.JailedUntilHeight != 0 {
		i = encodeVarintProvider(dAtA, i, uint64(m.JailedUntilHeight))
		i--
		dAtA[i] = 0x58
	}
	if m.Jailed {
		i--
		if m.Jailed {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x50
	}
	if m.FraudScore != 0 {
		i = encodeVarintProvider(dAtA, i, uint64(m.FraudScore))
		i--
		dAtA[i] = 0x48
	}
	if m.RegisteredHeight != 0 {
		i = encodeVarintProvider(dAtA, i, uint64(m.RegisteredHeight))
		i--
		dAtA[i] = 0x40
	}
	if m.DeclaredBandwidthBps != 0 {
		i = encodeVarintProvider(dAtA, i, uint64(m.DeclaredBandwidthBps))
		i--
		dAtA[i] = 0x38
	}
	if m.DeclaredStorageBytes != 0 {
		i = encodeVarintProvider(dAtA, i, uint64(m.DeclaredStorageBytes))
		i--
		dAtA[i] = 0x30
	}
	if len(m.Bond) > 0 {
		for iNdEx := len(m.Bond) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Bond[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintProvider(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.Roles) > 0 {
		dAtA2 := make([]byte, len(m.Roles)*10)
		var j1 int
		for _, num := range m.Roles {
			for num >= 1<<7 {
				dAtA2[j1] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j1++
			}
			dAtA2[j1] = uint8(num)
			j1++
		}
		i -= j1
		copy(dAtA[i:], dAtA2[:j1])
		i = encodeVarintProvider(dAtA, i, uint64(j1))
		i--
		dAtA[i] = 0x22
	}
	if len(m.NodePubkey) > 0 {
		i -= len(m.NodePubkey)
		copy(dAtA[i:], m.NodePubkey)
		i = encodeVarintProvider(dAtA, i, uint64(len(m.NodePubkey)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.RewardAddress) > 0 {
		i -= len(m.RewardAddress)
		copy(dAtA[i:], m.RewardAddress)
		i = encodeVarintProvider(dAtA, i, uint64(len(m.RewardAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Operator) > 0 {
		i -= len(m.Operator)
		copy(dAtA[i:], m.Operator)
		i = encodeVarintProvider(dAtA, i, uint64(len(m.Operator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Epoch) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Epoch) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Epoch) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.TotalCredit.Size()
		i -= size
		if _, err := m.TotalCredit.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintProvider(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x3a
	if m.Settled {
		i--
		if m.Settled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x30
	}
	if len(m.Distributed) > 0 {
		for iNdEx := len(m.Distributed) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Distributed[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintProvider(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.Budget) > 0 {
		for iNdEx := len(m.Budget) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Budget[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintProvider(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if m.EndHeight != 0 {
		i = encodeVarintProvider(dAtA, i, uint64(m.EndHeight))
		i--
		dAtA[i] = 0x18
	}
	if m.StartHeight != 0 {
		i = encodeVarintProvider(dAtA, i, uint64(m.StartHeight))
		i--
		dAtA[i] = 0x10
	}
	if m.Number != 0 {
		i = encodeVarintProvider(dAtA, i, uint64(m.Number))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *ProviderEpochCredit) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ProviderEpochCredit) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ProviderEpochCredit) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Paid) > 0 {
		for iNdEx := len(m.Paid) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Paid[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintProvider(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x52
		}
	}
	if m.DistinctClients != 0 {
		i = encodeVarintProvider(dAtA, i, uint64(m.DistinctClients))
		i--
		dAtA[i] = 0x48
	}
	if m.ChallengesPassed != 0 {
		i = encodeVarintProvider(dAtA, i, uint64(m.ChallengesPassed))
		i--
		dAtA[i] = 0x40
	}
	if m.ChallengesIssued != 0 {
		i = encodeVarintProvider(dAtA, i, uint64(m.ChallengesIssued))
		i--
		dAtA[i] = 0x38
	}
	{
		size := m.CallCredit.Size()
		i -= size
		if _, err := m.CallCredit.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintProvider(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	{
		size := m.RetrievalCredit.Size()
		i -= size
		if _, err := m.RetrievalCredit.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintProvider(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	{
		size := m.RelayCredit.Size()
		i -= size
		if _, err := m.RelayCredit.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintProvider(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size := m.StorageCredit.Size()
		i -= size
		if _, err := m.StorageCredit.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintProvider(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if m.Epoch != 0 {
		i = encodeVarintProvider(dAtA, i, uint64(m.Epoch))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Operator) > 0 {
		i -= len(m.Operator)
		copy(dAtA[i:], m.Operator)
		i = encodeVarintProvider(dAtA, i, uint64(len(m.Operator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintProvider(dAtA []byte, offset int, v uint64) int {
	offset -= sovProvider(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Provider) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Operator)
	if l > 0 {
		n += 1 + l + sovProvider(uint64(l))
	}
	l = len(m.RewardAddress)
	if l > 0 {
		n += 1 + l + sovProvider(uint64(l))
	}
	l = len(m.NodePubkey)
	if l > 0 {
		n += 1 + l + sovProvider(uint64(l))
	}
	if len(m.Roles) > 0 {
		l = 0
		for _, e := range m.Roles {
			l += sovProvider(uint64(e))
		}
		n += 1 + sovProvider(uint64(l)) + l
	}
	if len(m.Bond) > 0 {
		for _, e := range m.Bond {
			l = e.Size()
			n += 1 + l + sovProvider(uint64(l))
		}
	}
	if m.DeclaredStorageBytes != 0 {
		n += 1 + sovProvider(uint64(m.DeclaredStorageBytes))
	}
	if m.DeclaredBandwidthBps != 0 {
		n += 1 + sovProvider(uint64(m.DeclaredBandwidthBps))
	}
	if m.RegisteredHeight != 0 {
		n += 1 + sovProvider(uint64(m.RegisteredHeight))
	}
	if m.FraudScore != 0 {
		n += 1 + sovProvider(uint64(m.FraudScore))
	}
	if m.Jailed {
		n += 2
	}
	if m.JailedUntilHeight != 0 {
		n += 1 + sovProvider(uint64(m.JailedUntilHeight))
	}
	if m.UnbondingHeight != 0 {
		n += 1 + sovProvider(uint64(m.UnbondingHeight))
	}
	l = len(m.Moniker)
	if l > 0 {
		n += 1 + l + sovProvider(uint64(l))
	}
	return n
}

func (m *Epoch) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Number != 0 {
		n += 1 + sovProvider(uint64(m.Number))
	}
	if m.StartHeight != 0 {
		n += 1 + sovProvider(uint64(m.StartHeight))
	}
	if m.EndHeight != 0 {
		n += 1 + sovProvider(uint64(m.EndHeight))
	}
	if len(m.Budget) > 0 {
		for _, e := range m.Budget {
			l = e.Size()
			n += 1 + l + sovProvider(uint64(l))
		}
	}
	if len(m.Distributed) > 0 {
		for _, e := range m.Distributed {
			l = e.Size()
			n += 1 + l + sovProvider(uint64(l))
		}
	}
	if m.Settled {
		n += 2
	}
	l = m.TotalCredit.Size()
	n += 1 + l + sovProvider(uint64(l))
	return n
}

func (m *ProviderEpochCredit) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Operator)
	if l > 0 {
		n += 1 + l + sovProvider(uint64(l))
	}
	if m.Epoch != 0 {
		n += 1 + sovProvider(uint64(m.Epoch))
	}
	l = m.StorageCredit.Size()
	n += 1 + l + sovProvider(uint64(l))
	l = m.RelayCredit.Size()
	n += 1 + l + sovProvider(uint64(l))
	l = m.RetrievalCredit.Size()
	n += 1 + l + sovProvider(uint64(l))
	l = m.CallCredit.Size()
	n += 1 + l + sovProvider(uint64(l))
	if m.ChallengesIssued != 0 {
		n += 1 + sovProvider(uint64(m.ChallengesIssued))
	}
	if m.ChallengesPassed != 0 {
		n += 1 + sovProvider(uint64(m.ChallengesPassed))
	}
	if m.DistinctClients != 0 {
		n += 1 + sovProvider(uint64(m.DistinctClients))
	}
	if len(m.Paid) > 0 {
		for _, e := range m.Paid {
			l = e.Size()
			n += 1 + l + sovProvider(uint64(l))
		}
	}
	return n
}

func sovProvider(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozProvider(x uint64) (n int) {
	return sovProvider(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Provider) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowProvider
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Provider: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Provider: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Operator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProvider
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthProvider
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthProvider
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Operator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RewardAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProvider
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthProvider
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthProvider
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RewardAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NodePubkey", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProvider
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthProvider
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthProvider
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NodePubkey = append(m.NodePubkey[:0], dAtA[iNdEx:postIndex]...)
			if m.NodePubkey == nil {
				m.NodePubkey = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType == 0 {
				var v ServiceRole
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowProvider
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= ServiceRole(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.Roles = append(m.Roles, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowProvider
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthProvider
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthProvider
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				if elementCount != 0 && len(m.Roles) == 0 {
					m.Roles = make([]ServiceRole, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v ServiceRole
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowProvider
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= ServiceRole(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.Roles = append(m.Roles, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field Roles", wireType)
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Bond", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProvider
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthProvider
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthProvider
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Bond = append(m.Bond, types.Coin{})
			if err := m.Bond[len(m.Bond)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeclaredStorageBytes", wireType)
			}
			m.DeclaredStorageBytes = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProvider
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DeclaredStorageBytes |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeclaredBandwidthBps", wireType)
			}
			m.DeclaredBandwidthBps = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProvider
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DeclaredBandwidthBps |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RegisteredHeight", wireType)
			}
			m.RegisteredHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProvider
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RegisteredHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FraudScore", wireType)
			}
			m.FraudScore = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProvider
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FraudScore |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Jailed", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProvider
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Jailed = bool(v != 0)
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field JailedUntilHeight", wireType)
			}
			m.JailedUntilHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProvider
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.JailedUntilHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UnbondingHeight", wireType)
			}
			m.UnbondingHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProvider
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UnbondingHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Moniker", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProvider
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthProvider
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthProvider
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Moniker = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipProvider(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthProvider
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Epoch) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowProvider
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Epoch: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Epoch: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Number", wireType)
			}
			m.Number = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProvider
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Number |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartHeight", wireType)
			}
			m.StartHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProvider
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StartHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EndHeight", wireType)
			}
			m.EndHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProvider
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EndHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Budget", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProvider
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthProvider
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthProvider
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Budget = append(m.Budget, types.Coin{})
			if err := m.Budget[len(m.Budget)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Distributed", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProvider
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthProvider
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthProvider
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Distributed = append(m.Distributed, types.Coin{})
			if err := m.Distributed[len(m.Distributed)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Settled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProvider
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Settled = bool(v != 0)
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalCredit", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProvider
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthProvider
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthProvider
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TotalCredit.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipProvider(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthProvider
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ProviderEpochCredit) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowProvider
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ProviderEpochCredit: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ProviderEpochCredit: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Operator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProvider
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthProvider
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthProvider
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Operator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Epoch", wireType)
			}
			m.Epoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProvider
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Epoch |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StorageCredit", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProvider
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthProvider
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthProvider
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.StorageCredit.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RelayCredit", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProvider
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthProvider
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthProvider
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.RelayCredit.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RetrievalCredit", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProvider
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthProvider
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthProvider
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.RetrievalCredit.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CallCredit", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProvider
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthProvider
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthProvider
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.CallCredit.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChallengesIssued", wireType)
			}
			m.ChallengesIssued = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProvider
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ChallengesIssued |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChallengesPassed", wireType)
			}
			m.ChallengesPassed = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProvider
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ChallengesPassed |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DistinctClients", wireType)
			}
			m.DistinctClients = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProvider
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DistinctClients |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Paid", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProvider
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthProvider
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthProvider
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Paid = append(m.Paid, types.Coin{})
			if err := m.Paid[len(m.Paid)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipProvider(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthProvider
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipProvider(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowProvider
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowProvider
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowProvider
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthProvider
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupProvider
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthProvider
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthProvider        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowProvider          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupProvider = fmt.Errorf("proto: unexpected end of group")
)
