// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: hashgram/chat/v1/chat.proto

package chatpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChatKind int32

const (
	ChatKind_CHAT_KIND_UNSPECIFIED ChatKind = 0
	// A text message, possibly with attachments.
	ChatKind_CHAT_KIND_TEXT ChatKind = 1
	// Edit of an earlier message by its author.
	ChatKind_CHAT_KIND_EDIT ChatKind = 2
	// Deletion of an earlier message by its author; clients show a tombstone.
	ChatKind_CHAT_KIND_DELETE ChatKind = 3
	// Reaction to a message. Empty reaction string removes.
	ChatKind_CHAT_KIND_REACTION ChatKind = 4
	// Read receipt up to and including a message id.
	ChatKind_CHAT_KIND_READ ChatKind = 5
	// Delivery receipt for a message id.
	ChatKind_CHAT_KIND_DELIVERED ChatKind = 6
	// Typing indicator; clients treat as ephemeral.
	ChatKind_CHAT_KIND_TYPING ChatKind = 7
	// Group metadata: name, description, avatar. Sent by whoever changes it.
	ChatKind_CHAT_KIND_GROUP_INFO ChatKind = 8
	// Call signalling (offer, answer, ICE candidate, hangup).
	ChatKind_CHAT_KIND_CALL ChatKind = 9
	// Voice message: an attachment that clients render as audio.
	ChatKind_CHAT_KIND_VOICE ChatKind = 10
)

// Enum value maps for ChatKind.
var (
	ChatKind_name = map[int32]string{
		0:  "CHAT_KIND_UNSPECIFIED",
		1:  "CHAT_KIND_TEXT",
		2:  "CHAT_KIND_EDIT",
		3:  "CHAT_KIND_DELETE",
		4:  "CHAT_KIND_REACTION",
		5:  "CHAT_KIND_READ",
		6:  "CHAT_KIND_DELIVERED",
		7:  "CHAT_KIND_TYPING",
		8:  "CHAT_KIND_GROUP_INFO",
		9:  "CHAT_KIND_CALL",
		10: "CHAT_KIND_VOICE",
	}
	ChatKind_value = map[string]int32{
		"CHAT_KIND_UNSPECIFIED": 0,
		"CHAT_KIND_TEXT":        1,
		"CHAT_KIND_EDIT":        2,
		"CHAT_KIND_DELETE":      3,
		"CHAT_KIND_REACTION":    4,
		"CHAT_KIND_READ":        5,
		"CHAT_KIND_DELIVERED":   6,
		"CHAT_KIND_TYPING":      7,
		"CHAT_KIND_GROUP_INFO":  8,
		"CHAT_KIND_CALL":        9,
		"CHAT_KIND_VOICE":       10,
	}
)

func (x ChatKind) Enum() *ChatKind {
	p := new(ChatKind)
	*p = x
	return p
}

func (x ChatKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChatKind) Descriptor() protoreflect.EnumDescriptor {
	return file_hashgram_chat_v1_chat_proto_enumTypes[0].Descriptor()
}

func (ChatKind) Type() protoreflect.EnumType {
	return &file_hashgram_chat_v1_chat_proto_enumTypes[0]
}

func (x ChatKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChatKind.Descriptor instead.
func (ChatKind) EnumDescriptor() ([]byte, []int) {
	return file_hashgram_chat_v1_chat_proto_rawDescGZIP(), []int{0}
}

// A reference to an encrypted blob plus the key to open it. The blob is
// stored on media nodes as ciphertext; only group members hold this key.
type Attachment struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Cid   []byte                 `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	// XChaCha20-Poly1305 key, 32 bytes.
	Key []byte `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	// 24-byte nonce.
	Nonce []byte `protobuf:"bytes,3,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Mime  string `protobuf:"bytes,4,opt,name=mime,proto3" json:"mime,omitempty"`
	// Plaintext size.
	Size uint64 `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`
	Name string `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	// "image", "video", "audio", "file".
	Kind       string `protobuf:"bytes,7,opt,name=kind,proto3" json:"kind,omitempty"`
	Width      uint32 `protobuf:"varint,8,opt,name=width,proto3" json:"width,omitempty"`
	Height     uint32 `protobuf:"varint,9,opt,name=height,proto3" json:"height,omitempty"`
	DurationMs uint32 `protobuf:"varint,10,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	// BLAKE3 of the plaintext, so a recipient can verify after decrypting.
	PlaintextHash []byte `protobuf:"bytes,11,opt,name=plaintext_hash,json=plaintextHash,proto3" json:"plaintext_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Attachment) Reset() {
	*x = Attachment{}
	mi := &file_hashgram_chat_v1_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attachment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attachment) ProtoMessage() {}

func (x *Attachment) ProtoReflect() protoreflect.Message {
	mi := &file_hashgram_chat_v1_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attachment.ProtoReflect.Descriptor instead.
func (*Attachment) Descriptor() ([]byte, []int) {
	return file_hashgram_chat_v1_chat_proto_rawDescGZIP(), []int{0}
}

func (x *Attachment) GetCid() []byte {
	if x != nil {
		return x.Cid
	}
	return nil
}

func (x *Attachment) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *Attachment) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *Attachment) GetMime() string {
	if x != nil {
		return x.Mime
	}
	return ""
}

func (x *Attachment) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Attachment) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Attachment) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Attachment) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Attachment) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Attachment) GetDurationMs() uint32 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *Attachment) GetPlaintextHash() []byte {
	if x != nil {
		return x.PlaintextHash
	}
	return nil
}

type CallSignal struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// "offer", "answer", "ice", "hangup", "busy", "ring".
	Kind string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	// Call id, random 16 bytes, so signals of concurrent calls do not mix.
	CallId []byte `protobuf:"bytes,2,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	// SDP for offer/answer.
	Sdp string `protobuf:"bytes,3,opt,name=sdp,proto3" json:"sdp,omitempty"`
	// ICE candidate for "ice".
	Candidate     string `protobuf:"bytes,4,opt,name=candidate,proto3" json:"candidate,omitempty"`
	SdpMid        string `protobuf:"bytes,5,opt,name=sdp_mid,json=sdpMid,proto3" json:"sdp_mid,omitempty"`
	SdpMlineIndex uint32 `protobuf:"varint,6,opt,name=sdp_mline_index,json=sdpMlineIndex,proto3" json:"sdp_mline_index,omitempty"`
	// Whether video is requested.
	Video         bool `protobuf:"varint,7,opt,name=video,proto3" json:"video,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallSignal) Reset() {
	*x = CallSignal{}
	mi := &file_hashgram_chat_v1_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallSignal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallSignal) ProtoMessage() {}

func (x *CallSignal) ProtoReflect() protoreflect.Message {
	mi := &file_hashgram_chat_v1_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallSignal.ProtoReflect.Descriptor instead.
func (*CallSignal) Descriptor() ([]byte, []int) {
	return file_hashgram_chat_v1_chat_proto_rawDescGZIP(), []int{1}
}

func (x *CallSignal) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *CallSignal) GetCallId() []byte {
	if x != nil {
		return x.CallId
	}
	return nil
}

func (x *CallSignal) GetSdp() string {
	if x != nil {
		return x.Sdp
	}
	return ""
}

func (x *CallSignal) GetCandidate() string {
	if x != nil {
		return x.Candidate
	}
	return ""
}

func (x *CallSignal) GetSdpMid() string {
	if x != nil {
		return x.SdpMid
	}
	return ""
}

func (x *CallSignal) GetSdpMlineIndex() uint32 {
	if x != nil {
		return x.SdpMlineIndex
	}
	return 0
}

func (x *CallSignal) GetVideo() bool {
	if x != nil {
		return x.Video
	}
	return false
}

type GroupInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Avatar        *Attachment            `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupInfo) Reset() {
	*x = GroupInfo{}
	mi := &file_hashgram_chat_v1_chat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupInfo) ProtoMessage() {}

func (x *GroupInfo) ProtoReflect() protoreflect.Message {
	mi := &file_hashgram_chat_v1_chat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupInfo.ProtoReflect.Descriptor instead.
func (*GroupInfo) Descriptor() ([]byte, []int) {
	return file_hashgram_chat_v1_chat_proto_rawDescGZIP(), []int{2}
}

func (x *GroupInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GroupInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GroupInfo) GetAvatar() *Attachment {
	if x != nil {
		return x.Avatar
	}
	return nil
}

type ChatMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Format version. 1.
	Version uint32   `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Kind    ChatKind `protobuf:"varint,2,opt,name=kind,proto3,enum=hashgram.chat.v1.ChatKind" json:"kind,omitempty"`
	// Random 16 bytes chosen by the sender; the identity of this message
	// for edits, deletes, reactions and receipts.
	Id []byte `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	// Unix milliseconds on the sender's clock.
	TimestampMs uint64 `protobuf:"varint,4,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	Text        string `protobuf:"bytes,5,opt,name=text,proto3" json:"text,omitempty"`
	// For REPLY-style text: the message being replied to.
	ReplyTo []byte `protobuf:"bytes,6,opt,name=reply_to,json=replyTo,proto3" json:"reply_to,omitempty"`
	// For EDIT, DELETE, REACTION, READ, DELIVERED: the message referred to.
	Target      []byte        `protobuf:"bytes,7,opt,name=target,proto3" json:"target,omitempty"`
	Reaction    string        `protobuf:"bytes,8,opt,name=reaction,proto3" json:"reaction,omitempty"`
	Attachments []*Attachment `protobuf:"bytes,9,rep,name=attachments,proto3" json:"attachments,omitempty"`
	// If non-zero, clients delete the message this many seconds after
	// reading it (disappearing messages). Enforced by clients; a node never
	// sees it.
	DisappearAfterSecs uint32      `protobuf:"varint,10,opt,name=disappear_after_secs,json=disappearAfterSecs,proto3" json:"disappear_after_secs,omitempty"`
	GroupInfo          *GroupInfo  `protobuf:"bytes,11,opt,name=group_info,json=groupInfo,proto3" json:"group_info,omitempty"`
	Call               *CallSignal `protobuf:"bytes,12,opt,name=call,proto3" json:"call,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_hashgram_chat_v1_chat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_hashgram_chat_v1_chat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_hashgram_chat_v1_chat_proto_rawDescGZIP(), []int{3}
}

func (x *ChatMessage) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ChatMessage) GetKind() ChatKind {
	if x != nil {
		return x.Kind
	}
	return ChatKind_CHAT_KIND_UNSPECIFIED
}

func (x *ChatMessage) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *ChatMessage) GetTimestampMs() uint64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *ChatMessage) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ChatMessage) GetReplyTo() []byte {
	if x != nil {
		return x.ReplyTo
	}
	return nil
}

func (x *ChatMessage) GetTarget() []byte {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *ChatMessage) GetReaction() string {
	if x != nil {
		return x.Reaction
	}
	return ""
}

func (x *ChatMessage) GetAttachments() []*Attachment {
	if x != nil {
		return x.Attachments
	}
	return nil
}

func (x *ChatMessage) GetDisappearAfterSecs() uint32 {
	if x != nil {
		return x.DisappearAfterSecs
	}
	return 0
}

func (x *ChatMessage) GetGroupInfo() *GroupInfo {
	if x != nil {
		return x.GroupInfo
	}
	return nil
}

func (x *ChatMessage) GetCall() *CallSignal {
	if x != nil {
		return x.Call
	}
	return nil
}

var File_hashgram_chat_v1_chat_proto protoreflect.FileDescriptor

const file_hashgram_chat_v1_chat_proto_rawDesc = "" +
	"\n" +
	"\x1bhashgram/chat/v1/chat.proto\x12\x10hashgram.chat.v1\"\x8c\x02\n" +
	"\n" +
	"Attachment\x12\x10\n" +
	"\x03cid\x18\x01 \x01(\fR\x03cid\x12\x10\n" +
	"\x03key\x18\x02 \x01(\fR\x03key\x12\x14\n" +
	"\x05nonce\x18\x03 \x01(\fR\x05nonce\x12\x12\n" +
	"\x04mime\x18\x04 \x01(\tR\x04mime\x12\x12\n" +
	"\x04size\x18\x05 \x01(\x04R\x04size\x12\x12\n" +
	"\x04name\x18\x06 \x01(\tR\x04name\x12\x12\n" +
	"\x04kind\x18\a \x01(\tR\x04kind\x12\x14\n" +
	"\x05width\x18\b \x01(\rR\x05width\x12\x16\n" +
	"\x06height\x18\t \x01(\rR\x06height\x12\x1f\n" +
	"\vduration_ms\x18\n" +
	" \x01(\rR\n" +
	"durationMs\x12%\n" +
	"\x0eplaintext_hash\x18\v \x01(\fR\rplaintextHash\"\xc0\x01\n" +
	"\n" +
	"CallSignal\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x17\n" +
	"\acall_id\x18\x02 \x01(\fR\x06callId\x12\x10\n" +
	"\x03sdp\x18\x03 \x01(\tR\x03sdp\x12\x1c\n" +
	"\tcandidate\x18\x04 \x01(\tR\tcandidate\x12\x17\n" +
	"\asdp_mid\x18\x05 \x01(\tR\x06sdpMid\x12&\n" +
	"\x0fsdp_mline_index\x18\x06 \x01(\rR\rsdpMlineIndex\x12\x14\n" +
	"\x05video\x18\a \x01(\bR\x05video\"w\n" +
	"\tGroupInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x124\n" +
	"\x06avatar\x18\x03 \x01(\v2\x1c.hashgram.chat.v1.AttachmentR\x06avatar\"\xcd\x03\n" +
	"\vChatMessage\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12.\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x1a.hashgram.chat.v1.ChatKindR\x04kind\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\fR\x02id\x12!\n" +
	"\ftimestamp_ms\x18\x04 \x01(\x04R\vtimestampMs\x12\x12\n" +
	"\x04text\x18\x05 \x01(\tR\x04text\x12\x19\n" +
	"\breply_to\x18\x06 \x01(\fR\areplyTo\x12\x16\n" +
	"\x06target\x18\a \x01(\fR\x06target\x12\x1a\n" +
	"\breaction\x18\b \x01(\tR\breaction\x12>\n" +
	"\vattachments\x18\t \x03(\v2\x1c.hashgram.chat.v1.AttachmentR\vattachments\x120\n" +
	"\x14disappear_after_secs\x18\n" +
	" \x01(\rR\x12disappearAfterSecs\x12:\n" +
	"\n" +
	"group_info\x18\v \x01(\v2\x1b.hashgram.chat.v1.GroupInfoR\tgroupInfo\x120\n" +
	"\x04call\x18\f \x01(\v2\x1c.hashgram.chat.v1.CallSignalR\x04call*\x81\x02\n" +
	"\bChatKind\x12\x19\n" +
	"\x15CHAT_KIND_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eCHAT_KIND_TEXT\x10\x01\x12\x12\n" +
	"\x0eCHAT_KIND_EDIT\x10\x02\x12\x14\n" +
	"\x10CHAT_KIND_DELETE\x10\x03\x12\x16\n" +
	"\x12CHAT_KIND_REACTION\x10\x04\x12\x12\n" +
	"\x0eCHAT_KIND_READ\x10\x05\x12\x17\n" +
	"\x13CHAT_KIND_DELIVERED\x10\x06\x12\x14\n" +
	"\x10CHAT_KIND_TYPING\x10\a\x12\x18\n" +
	"\x14CHAT_KIND_GROUP_INFO\x10\b\x12\x12\n" +
	"\x0eCHAT_KIND_CALL\x10\t\x12\x13\n" +
	"\x0fCHAT_KIND_VOICE\x10\n" +
	"B0Z.github.com/hashgram/hashgram/pkg/chatpb;chatpbb\x06proto3"

var (
	file_hashgram_chat_v1_chat_proto_rawDescOnce sync.Once
	file_hashgram_chat_v1_chat_proto_rawDescData []byte
)

func file_hashgram_chat_v1_chat_proto_rawDescGZIP() []byte {
	file_hashgram_chat_v1_chat_proto_rawDescOnce.Do(func() {
		file_hashgram_chat_v1_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hashgram_chat_v1_chat_proto_rawDesc), len(file_hashgram_chat_v1_chat_proto_rawDesc)))
	})
	return file_hashgram_chat_v1_chat_proto_rawDescData
}

var file_hashgram_chat_v1_chat_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_hashgram_chat_v1_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_hashgram_chat_v1_chat_proto_goTypes = []any{
	(ChatKind)(0),       // 0: hashgram.chat.v1.ChatKind
	(*Attachment)(nil),  // 1: hashgram.chat.v1.Attachment
	(*CallSignal)(nil),  // 2: hashgram.chat.v1.CallSignal
	(*GroupInfo)(nil),   // 3: hashgram.chat.v1.GroupInfo
	(*ChatMessage)(nil), // 4: hashgram.chat.v1.ChatMessage
}
var file_hashgram_chat_v1_chat_proto_depIdxs = []int32{
	1, // 0: hashgram.chat.v1.GroupInfo.avatar:type_name -> hashgram.chat.v1.Attachment
	0, // 1: hashgram.chat.v1.ChatMessage.kind:type_name -> hashgram.chat.v1.ChatKind
	1, // 2: hashgram.chat.v1.ChatMessage.attachments:type_name -> hashgram.chat.v1.Attachment
	3, // 3: hashgram.chat.v1.ChatMessage.group_info:type_name -> hashgram.chat.v1.GroupInfo
	2, // 4: hashgram.chat.v1.ChatMessage.call:type_name -> hashgram.chat.v1.CallSignal
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_hashgram_chat_v1_chat_proto_init() }
func file_hashgram_chat_v1_chat_proto_init() {
	if File_hashgram_chat_v1_chat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hashgram_chat_v1_chat_proto_rawDesc), len(file_hashgram_chat_v1_chat_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hashgram_chat_v1_chat_proto_goTypes,
		DependencyIndexes: file_hashgram_chat_v1_chat_proto_depIdxs,
		EnumInfos:         file_hashgram_chat_v1_chat_proto_enumTypes,
		MessageInfos:      file_hashgram_chat_v1_chat_proto_msgTypes,
	}.Build()
	File_hashgram_chat_v1_chat_proto = out.File
	file_hashgram_chat_v1_chat_proto_goTypes = nil
	file_hashgram_chat_v1_chat_proto_depIdxs = nil
}
