package genesis_test

import (
	"encoding/json"
	"os"
	"testing"
	"time"

	"github.com/stretchr/testify/require"

	dbm "github.com/cosmos/cosmos-db"

	"cosmossdk.io/log"
	"cosmossdk.io/math"

	simtestutil "github.com/cosmos/cosmos-sdk/testutil/sims"
	sdk "github.com/cosmos/cosmos-sdk/types"
	authtypes "github.com/cosmos/cosmos-sdk/x/auth/types"
	vestingtypes "github.com/cosmos/cosmos-sdk/x/auth/vesting/types"
	banktypes "github.com/cosmos/cosmos-sdk/x/bank/types"

	"github.com/hashgram/hashgram/app"
	hgparams "github.com/hashgram/hashgram/app/params"
	"github.com/hashgram/hashgram/genesis"
	foundertypes "github.com/hashgram/hashgram/x/founder/types"
	networktypes "github.com/hashgram/hashgram/x/network/types"
	serviceprooftypes "github.com/hashgram/hashgram/x/serviceproof/types"
	treasurytypes "github.com/hashgram/hashgram/x/treasury/types"
	welcometypes "github.com/hashgram/hashgram/x/welcome/types"
)

func TestMain(m *testing.M) {
	hgparams.SetSDKConfig()
	os.Exit(m.Run())
}

// founderAddress is a DEVNET-only address standing in for the Founder's
// public address. Derived from label bytes so it is always a valid checksum
// and so nothing in the repository looks like an address with a key behind it.
func founderAddress() string {
	b := make([]byte, 20)
	copy(b, "DEVNET-FOUNDER-ADDR")
	return sdk.AccAddress(b).String()
}

func buildMainnet(t *testing.T) (*genesis.Result, *app.HashgramApp) {
	t.Helper()

	a := app.NewHashgramApp(
		log.NewNopLogger(), dbm.NewMemDB(), nil, true,
		simtestutil.NewAppOptionsWithFlagHome(t.TempDir()),
	)

	res, err := genesis.Build(a.AppCodec(), a.DefaultGenesis(), genesis.Config{
		FounderAddress: founderAddress(),
		GenesisTime:    time.Unix(1_700_000_000, 0).UTC(),
	})
	require.NoError(t, err)
	return res, a
}

// ---------------------------------------------------------------------------
// The Founder address is a required input
// ---------------------------------------------------------------------------

// TestGenesisRefusesToInventTheFounderAddress is §110 and §116.24: the
// software must never fabricate the Founder address.
func TestGenesisRefusesToInventTheFounderAddress(t *testing.T) {
	a := app.NewHashgramApp(
		log.NewNopLogger(), dbm.NewMemDB(), nil, true,
		simtestutil.NewAppOptionsWithFlagHome(t.TempDir()),
	)

	_, err := genesis.Build(a.AppCodec(), a.DefaultGenesis(), genesis.Config{})
	require.Error(t, err)
	require.Contains(t, err.Error(), "cannot be generated by this software")
	require.Contains(t, err.Error(), "GENESIS_FOUNDER_ADDRESS")
}

func TestGenesisRejectsMalformedFounderAddress(t *testing.T) {
	a := app.NewHashgramApp(
		log.NewNopLogger(), dbm.NewMemDB(), nil, true,
		simtestutil.NewAppOptionsWithFlagHome(t.TempDir()),
	)

	for _, bad := range []string{
		"not-an-address",
		"hash1invalid",
		"cosmos1qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq", // wrong prefix
	} {
		_, err := genesis.Build(a.AppCodec(), a.DefaultGenesis(), genesis.Config{
			FounderAddress: bad,
		})
		require.Error(t, err, "founder address %q was accepted", bad)
		require.Contains(t, err.Error(), "not a valid Hashgram address")
	}
}

// ---------------------------------------------------------------------------
// Supply
// ---------------------------------------------------------------------------

// TestTotalSupplyIsExactlyOneBillion is §116.1 at the genesis layer: the sum
// of every genesis balance must be exactly 1,000,000,000 HASH.
func TestTotalSupplyIsExactlyOneBillion(t *testing.T) {
	res, a := buildMainnet(t)

	want := sdk.NewCoins(sdk.NewCoin(hgparams.BaseCoinDenom, hgparams.MaxSupplyBase()))
	require.Equal(t, want.String(), res.TotalSupply.String())
	require.Equal(t, "1000000000000000uhash", res.TotalSupply.String())

	// And the bank genesis agrees with the sum of its own balances.
	var bank banktypes.GenesisState
	a.AppCodec().MustUnmarshalJSON(res.AppState[banktypes.ModuleName], &bank)

	sum := sdk.NewCoins()
	for _, b := range bank.Balances {
		sum = sum.Add(b.Coins...)
	}
	require.Equal(t, want.String(), sum.String())
	require.Equal(t, want.String(), bank.Supply.String())
}

// TestAllocationsMatchTheDistributionTable checks each documented allocation
// lands where §13 says it should.
func TestAllocationsMatchTheDistributionTable(t *testing.T) {
	res, a := buildMainnet(t)

	var bank banktypes.GenesisState
	a.AppCodec().MustUnmarshalJSON(res.AppState[banktypes.ModuleName], &bank)

	balanceOf := func(addr string) sdk.Coins {
		for _, b := range bank.Balances {
			if b.Address == addr {
				return b.Coins
			}
		}
		return sdk.NewCoins()
	}

	hash := func(n int64) string {
		return sdk.NewCoins(sdk.NewCoin(hgparams.BaseCoinDenom, hgparams.HashToBase(n))).String()
	}

	// Founder: 200,000,000 HASH.
	require.Equal(t, hash(200_000_000), balanceOf(founderAddress()).String(),
		"the Founder allocation is not 200,000,000 HASH")

	// Useful-service reserve: 500,000,000 HASH.
	require.Equal(t, hash(500_000_000),
		balanceOf(authtypes.NewModuleAddress(serviceprooftypes.ModuleName).String()).String())

	// Welcome pool: 1,850,000 HASH.
	require.Equal(t, hash(1_850_000),
		balanceOf(authtypes.NewModuleAddress(welcometypes.ModuleName).String()).String())

	// Treasury reserves.
	for name, amount := range map[string]int64{
		treasurytypes.ReserveTreasury:  150_000_000,
		treasurytypes.ReserveDevGrants: 50_000_000,
		treasurytypes.ReserveLiquidity: 50_000_000,
		// Growth less the welcome pool.
		treasurytypes.ReserveGrowth: 50_000_000 - 1_850_000,
	} {
		require.Equal(t, hash(amount),
			balanceOf(treasurytypes.ReserveAddress(name).String()).String(),
			"reserve %q", name)
	}
}

// TestEveryAllocationHasAnAddress: §13 requires all allocations to be
// transparently visible on chain, which means each must have an address a
// bank query can be pointed at.
func TestEveryAllocationHasAnAddress(t *testing.T) {
	res, _ := buildMainnet(t)

	require.NotEmpty(t, res.Allocations)
	seen := map[string]bool{}
	for _, a := range res.Allocations {
		require.NotEmpty(t, a.Address, "allocation %q has no address", a.Name)
		require.NotEmpty(t, a.Description, "allocation %q has no description", a.Name)
		require.False(t, a.Amount.IsZero(), "allocation %q is empty", a.Name)

		_, err := sdk.AccAddressFromBech32(a.Address)
		require.NoError(t, err, "allocation %q address is malformed", a.Name)

		require.False(t, seen[a.Address], "two allocations share the address %s", a.Address)
		seen[a.Address] = true
	}
}

// ---------------------------------------------------------------------------
// Founder vesting
// ---------------------------------------------------------------------------

// TestFounderVestingIsTwentyMillionUnlockedAndOneEightyVested is §14: the
// Founder holds 200M of which 20M is spendable at genesis and 180M vests.
func TestFounderVestingIsTwentyMillionUnlockedAndOneEightyVested(t *testing.T) {
	res, a := buildMainnet(t)

	var auth authtypes.GenesisState
	a.AppCodec().MustUnmarshalJSON(res.AppState[authtypes.ModuleName], &auth)

	accounts, err := authtypes.UnpackAccounts(auth.Accounts)
	require.NoError(t, err)

	var founder *vestingtypes.PeriodicVestingAccount
	for _, acc := range accounts {
		if acc.GetAddress().String() != founderAddress() {
			continue
		}
		pva, ok := acc.(*vestingtypes.PeriodicVestingAccount)
		require.True(t, ok, "the Founder account is %T, expected a PeriodicVestingAccount", acc)
		founder = pva
	}
	require.NotNil(t, founder, "no Founder account in genesis")

	// original_vesting is the locked part.
	require.Equal(t, hgparams.HashToBase(180_000_000).String(),
		founder.OriginalVesting.AmountOf(hgparams.BaseCoinDenom).String(),
		"the locked portion is not 180,000,000 HASH")

	// The periods must sum to exactly the locked amount: equal monthly
	// amounts with the truncation remainder in the final period, not
	// 180,000,000 minus accumulated rounding.
	total := math.ZeroInt()
	for _, p := range founder.VestingPeriods {
		total = total.Add(p.Amount.AmountOf(hgparams.BaseCoinDenom))
	}
	require.Equal(t, founder.OriginalVesting.AmountOf(hgparams.BaseCoinDenom).String(), total.String(),
		"the vesting periods do not sum to the locked amount")

	require.Len(t, founder.VestingPeriods, 96, "8 years of monthly periods")

	// The spendable-at-genesis part is total balance minus locked.
	var bank banktypes.GenesisState
	a.AppCodec().MustUnmarshalJSON(res.AppState[banktypes.ModuleName], &bank)
	var founderBalance sdk.Coins
	for _, b := range bank.Balances {
		if b.Address == founderAddress() {
			founderBalance = b.Coins
		}
	}
	unlocked, negative := founderBalance.SafeSub(founder.OriginalVesting...)
	require.False(t, negative)
	require.Equal(t, hgparams.HashToBase(20_000_000).String(),
		unlocked.AmountOf(hgparams.BaseCoinDenom).String(),
		"the amount spendable at genesis is not 20,000,000 HASH")
}

// TestNoHiddenAdditionalFounderMint is §95: exactly one account holds the
// Founder allocation, and nothing else is credited to the Founder address.
func TestNoHiddenAdditionalFounderMint(t *testing.T) {
	res, a := buildMainnet(t)

	var bank banktypes.GenesisState
	a.AppCodec().MustUnmarshalJSON(res.AppState[banktypes.ModuleName], &bank)

	count := 0
	total := sdk.NewCoins()
	for _, b := range bank.Balances {
		if b.Address == founderAddress() {
			count++
			total = total.Add(b.Coins...)
		}
	}
	require.Equal(t, 1, count, "the Founder address appears in %d genesis balances", count)
	require.Equal(t, hgparams.HashToBase(200_000_000).String(),
		total.AmountOf(hgparams.BaseCoinDenom).String(),
		"the Founder holds more than the 200,000,000 HASH allocation")
}

// ---------------------------------------------------------------------------
// Founder revenue configuration
// ---------------------------------------------------------------------------

// TestFounderRevenueBeneficiaryIsTheSuppliedAddress is §16: the beneficiary
// is the address the operator supplied, at exactly 1%.
func TestFounderRevenueBeneficiaryIsTheSuppliedAddress(t *testing.T) {
	res, a := buildMainnet(t)

	var founder foundertypes.GenesisState
	a.AppCodec().MustUnmarshalJSON(res.AppState[foundertypes.ModuleName], &founder)

	require.Equal(t, founderAddress(), founder.Params.Beneficiary)
	require.Equal(t, uint32(100), founder.Params.FeeBasisPoints)
	require.Equal(t, "1.00%", founder.Params.FeePercent())

	// Nothing has accrued or been paid on a fresh chain.
	require.True(t, founder.Ledger.TotalAccrued.IsZero())
	require.True(t, founder.Ledger.TotalPaid.IsZero())

	// The genesis file carries no beneficiary history. The audit trail's
	// first entry is written by x/founder's InitGenesis at chain start, from
	// the configured beneficiary, so it records the height at which the
	// chain actually began rather than a value copied from a file.
	require.Empty(t, founder.BeneficiaryHistory)
	require.NoError(t, founder.Validate())
}

// ---------------------------------------------------------------------------
// Network identity
// ---------------------------------------------------------------------------

func TestMainnetGenesisCarriesMainnetIdentity(t *testing.T) {
	res, a := buildMainnet(t)

	require.Equal(t, "hashgram-1", res.ChainID)
	require.Equal(t, "hashgram-mainnet", res.NetworkID)

	var network networktypes.GenesisState
	a.AppCodec().MustUnmarshalJSON(res.AppState[networktypes.ModuleName], &network)

	require.Equal(t, "hashgram-mainnet", network.Info.NetworkId)
	require.Equal(t, "hashgram-1", network.Info.ChainId)
	require.Equal(t, "HGM1", string(network.Info.NetworkMagic))
	require.NoError(t, network.Validate())

	// Every fork-isolation check must be on.
	require.Equal(t, networktypes.StrictForkIsolation(), network.ForkIsolation)
}

// TestDevnetGenesisIsNotMainnet: a devnet must never be able to claim to be
// Mainnet.
func TestDevnetGenesisIsNotMainnet(t *testing.T) {
	a := app.NewHashgramApp(
		log.NewNopLogger(), dbm.NewMemDB(), nil, true,
		simtestutil.NewAppOptionsWithFlagHome(t.TempDir()),
	)

	res, err := genesis.Build(a.AppCodec(), a.DefaultGenesis(), genesis.Config{
		FounderAddress: founderAddress(),
		Devnet:         true,
		GenesisTime:    time.Unix(1_700_000_000, 0).UTC(),
	})
	require.NoError(t, err)

	require.Equal(t, "hashgram-devnet-1", res.ChainID)
	require.Equal(t, "hashgram-devnet", res.NetworkID)

	var network networktypes.GenesisState
	a.AppCodec().MustUnmarshalJSON(res.AppState[networktypes.ModuleName], &network)
	require.Equal(t, "HGD1", string(network.Info.NetworkMagic))

	// Supply is identical: a devnet models the real tokenomics.
	require.Equal(t, "1000000000000000uhash", res.TotalSupply.String())
}

// ---------------------------------------------------------------------------
// Determinism
// ---------------------------------------------------------------------------

// TestGenesisIsDeterministic is what makes the genesis hash a usable network
// identifier: two operators with the same inputs must produce byte-identical
// files.
func TestGenesisIsDeterministic(t *testing.T) {
	build := func() []byte {
		a := app.NewHashgramApp(
			log.NewNopLogger(), dbm.NewMemDB(), nil, true,
			simtestutil.NewAppOptionsWithFlagHome(t.TempDir()),
		)
		res, err := genesis.Build(a.AppCodec(), a.DefaultGenesis(), genesis.Config{
			FounderAddress: founderAddress(),
			GenesisTime:    time.Unix(1_700_000_000, 0).UTC(),
		})
		require.NoError(t, err)

		out, err := json.Marshal(res.AppState)
		require.NoError(t, err)
		return out
	}

	first := build()
	second := build()
	require.Equal(t, string(first), string(second),
		"two builds with identical inputs produced different genesis app state")
}

// TestGenesisTimeIsTruncatedToTheSecond: a sub-second component would make
// two runs differ and produce different genesis hashes.
func TestGenesisTimeIsTruncatedToTheSecond(t *testing.T) {
	a := app.NewHashgramApp(
		log.NewNopLogger(), dbm.NewMemDB(), nil, true,
		simtestutil.NewAppOptionsWithFlagHome(t.TempDir()),
	)

	buildAt := func(ts time.Time) []byte {
		res, err := genesis.Build(a.AppCodec(), a.DefaultGenesis(), genesis.Config{
			FounderAddress: founderAddress(),
			GenesisTime:    ts,
		})
		require.NoError(t, err)
		out, err := json.Marshal(res.AppState)
		require.NoError(t, err)
		return out
	}

	base := time.Unix(1_700_000_000, 0).UTC()
	withNanos := base.Add(123456 * time.Microsecond)

	require.Equal(t, string(buildAt(base)), string(buildAt(withNanos)),
		"a sub-second genesis time changed the output")
}

// ---------------------------------------------------------------------------
// The genesis actually starts a chain
// ---------------------------------------------------------------------------

// TestGenesisValidatesAgainstEveryModule: a genesis file that no module will
// accept is worse than no genesis file.
func TestGenesisValidatesAgainstEveryModule(t *testing.T) {
	res, a := buildMainnet(t)

	// The basic manager validates every module that implements genesis
	// validation, which is the same path `hashgramd genesis validate` takes.
	require.NoError(t, a.BasicModuleManager.ValidateGenesis(a.AppCodec(), a.TxConfig(), res.AppState),
		"the built genesis was rejected by a module")
}
