// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: hashgram/network/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryInfoRequest is the request for Query/Info.
type QueryInfoRequest struct {
}

func (m *QueryInfoRequest) Reset()         { *m = QueryInfoRequest{} }
func (m *QueryInfoRequest) String() string { return proto.CompactTextString(m) }
func (*QueryInfoRequest) ProtoMessage()    {}
func (*QueryInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a786f530bfca1a21, []int{0}
}
func (m *QueryInfoRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryInfoRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryInfoRequest.Merge(m, src)
}
func (m *QueryInfoRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryInfoRequest proto.InternalMessageInfo

// QueryInfoResponse is the response for Query/Info.
type QueryInfoResponse struct {
	Info NetworkInfo `protobuf:"bytes,1,opt,name=info,proto3" json:"info"`
}

func (m *QueryInfoResponse) Reset()         { *m = QueryInfoResponse{} }
func (m *QueryInfoResponse) String() string { return proto.CompactTextString(m) }
func (*QueryInfoResponse) ProtoMessage()    {}
func (*QueryInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a786f530bfca1a21, []int{1}
}
func (m *QueryInfoResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryInfoResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryInfoResponse.Merge(m, src)
}
func (m *QueryInfoResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryInfoResponse proto.InternalMessageInfo

func (m *QueryInfoResponse) GetInfo() NetworkInfo {
	if m != nil {
		return m.Info
	}
	return NetworkInfo{}
}

// QueryForkIsolationRequest is the request for Query/ForkIsolation.
type QueryForkIsolationRequest struct {
}

func (m *QueryForkIsolationRequest) Reset()         { *m = QueryForkIsolationRequest{} }
func (m *QueryForkIsolationRequest) String() string { return proto.CompactTextString(m) }
func (*QueryForkIsolationRequest) ProtoMessage()    {}
func (*QueryForkIsolationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a786f530bfca1a21, []int{2}
}
func (m *QueryForkIsolationRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryForkIsolationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryForkIsolationRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryForkIsolationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryForkIsolationRequest.Merge(m, src)
}
func (m *QueryForkIsolationRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryForkIsolationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryForkIsolationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryForkIsolationRequest proto.InternalMessageInfo

// QueryForkIsolationResponse is the response for Query/ForkIsolation.
type QueryForkIsolationResponse struct {
	Policy ForkIsolationPolicy `protobuf:"bytes,1,opt,name=policy,proto3" json:"policy"`
}

func (m *QueryForkIsolationResponse) Reset()         { *m = QueryForkIsolationResponse{} }
func (m *QueryForkIsolationResponse) String() string { return proto.CompactTextString(m) }
func (*QueryForkIsolationResponse) ProtoMessage()    {}
func (*QueryForkIsolationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a786f530bfca1a21, []int{3}
}
func (m *QueryForkIsolationResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryForkIsolationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryForkIsolationResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryForkIsolationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryForkIsolationResponse.Merge(m, src)
}
func (m *QueryForkIsolationResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryForkIsolationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryForkIsolationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryForkIsolationResponse proto.InternalMessageInfo

func (m *QueryForkIsolationResponse) GetPolicy() ForkIsolationPolicy {
	if m != nil {
		return m.Policy
	}
	return ForkIsolationPolicy{}
}

// QuerySigningDomainRequest is the request for Query/SigningDomain.
type QuerySigningDomainRequest struct {
	// purpose is one of the signing purposes defined by the protocol, e.g.
	// "social-event", "device-cert", "service-receipt".
	Purpose string `protobuf:"bytes,1,opt,name=purpose,proto3" json:"purpose,omitempty"`
}

func (m *QuerySigningDomainRequest) Reset()         { *m = QuerySigningDomainRequest{} }
func (m *QuerySigningDomainRequest) String() string { return proto.CompactTextString(m) }
func (*QuerySigningDomainRequest) ProtoMessage()    {}
func (*QuerySigningDomainRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a786f530bfca1a21, []int{4}
}
func (m *QuerySigningDomainRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QuerySigningDomainRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QuerySigningDomainRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QuerySigningDomainRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuerySigningDomainRequest.Merge(m, src)
}
func (m *QuerySigningDomainRequest) XXX_Size() int {
	return m.Size()
}
func (m *QuerySigningDomainRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QuerySigningDomainRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QuerySigningDomainRequest proto.InternalMessageInfo

func (m *QuerySigningDomainRequest) GetPurpose() string {
	if m != nil {
		return m.Purpose
	}
	return ""
}

// QuerySigningDomainResponse is the response for Query/SigningDomain.
type QuerySigningDomainResponse struct {
	// domain is the full domain string, e.g.
	// "hashgram/v1/hashgram-mainnet/social-event".
	Domain string `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	// network_magic is prepended to the signing preimage before the
	// length-prefixed domain and payload.
	NetworkMagic []byte `protobuf:"bytes,2,opt,name=network_magic,json=networkMagic,proto3" json:"network_magic,omitempty"`
	// preimage_layout documents the exact byte layout that is hashed, so an SDK
	// author does not have to infer it:
	//   magic(4) || uint32be(len(domain)) || domain || uint32be(len(payload)) || payload
	PreimageLayout string `protobuf:"bytes,3,opt,name=preimage_layout,json=preimageLayout,proto3" json:"preimage_layout,omitempty"`
}

func (m *QuerySigningDomainResponse) Reset()         { *m = QuerySigningDomainResponse{} }
func (m *QuerySigningDomainResponse) String() string { return proto.CompactTextString(m) }
func (*QuerySigningDomainResponse) ProtoMessage()    {}
func (*QuerySigningDomainResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a786f530bfca1a21, []int{5}
}
func (m *QuerySigningDomainResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QuerySigningDomainResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QuerySigningDomainResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QuerySigningDomainResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuerySigningDomainResponse.Merge(m, src)
}
func (m *QuerySigningDomainResponse) XXX_Size() int {
	return m.Size()
}
func (m *QuerySigningDomainResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QuerySigningDomainResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QuerySigningDomainResponse proto.InternalMessageInfo

func (m *QuerySigningDomainResponse) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *QuerySigningDomainResponse) GetNetworkMagic() []byte {
	if m != nil {
		return m.NetworkMagic
	}
	return nil
}

func (m *QuerySigningDomainResponse) GetPreimageLayout() string {
	if m != nil {
		return m.PreimageLayout
	}
	return ""
}

func init() {
	proto.RegisterType((*QueryInfoRequest)(nil), "hashgram.network.v1.QueryInfoRequest")
	proto.RegisterType((*QueryInfoResponse)(nil), "hashgram.network.v1.QueryInfoResponse")
	proto.RegisterType((*QueryForkIsolationRequest)(nil), "hashgram.network.v1.QueryForkIsolationRequest")
	proto.RegisterType((*QueryForkIsolationResponse)(nil), "hashgram.network.v1.QueryForkIsolationResponse")
	proto.RegisterType((*QuerySigningDomainRequest)(nil), "hashgram.network.v1.QuerySigningDomainRequest")
	proto.RegisterType((*QuerySigningDomainResponse)(nil), "hashgram.network.v1.QuerySigningDomainResponse")
}

func init() { proto.RegisterFile("hashgram/network/v1/query.proto", fileDescriptor_a786f530bfca1a21) }

var fileDescriptor_a786f530bfca1a21 = []byte{
	// 499 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xc7, 0xb3, 0x6d, 0x08, 0x62, 0x69, 0xf8, 0x58, 0x10, 0x4a, 0x5d, 0xe4, 0xa6, 0xae, 0x0a,
	0x91, 0x00, 0xaf, 0x5a, 0xd4, 0x0b, 0xc7, 0x0a, 0x45, 0x42, 0xe2, 0x33, 0xdc, 0xb8, 0x44, 0xdb,
	0x74, 0xb3, 0x59, 0x11, 0xef, 0xb8, 0x5e, 0xbb, 0xd4, 0x42, 0x5c, 0xfa, 0x04, 0x48, 0x9c, 0x39,
	0xf3, 0x2a, 0x95, 0xb8, 0x54, 0xe2, 0xc2, 0x09, 0xa1, 0x84, 0x07, 0x41, 0x5e, 0xaf, 0x03, 0xa9,
	0x96, 0xd2, 0xdb, 0x7a, 0x66, 0xfe, 0xf3, 0xff, 0x65, 0x66, 0x82, 0x57, 0x47, 0x4c, 0x8f, 0x44,
	0xc2, 0x22, 0xaa, 0x78, 0xfa, 0x0e, 0x92, 0xb7, 0xf4, 0x60, 0x93, 0xee, 0x67, 0x3c, 0xc9, 0xc3,
	0x38, 0x81, 0x14, 0xc8, 0x8d, 0xaa, 0x20, 0xb4, 0x05, 0xe1, 0xc1, 0xa6, 0x77, 0x53, 0x80, 0x00,
	0x93, 0xa7, 0xc5, 0xab, 0x2c, 0xf5, 0x6e, 0x0b, 0x00, 0x31, 0xe6, 0x94, 0xc5, 0x92, 0x32, 0xa5,
	0x20, 0x65, 0xa9, 0x04, 0xa5, 0x6d, 0x76, 0xcd, 0xe5, 0x54, 0xf5, 0x34, 0x25, 0x01, 0xc1, 0xd7,
	0x5e, 0x15, 0xd6, 0x4f, 0xd4, 0x10, 0x7a, 0x7c, 0x3f, 0xe3, 0x3a, 0x0d, 0x5e, 0xe0, 0xeb, 0x7f,
	0xc5, 0x74, 0x0c, 0x4a, 0x73, 0xf2, 0x08, 0xd7, 0xa5, 0x1a, 0x42, 0x0b, 0xb5, 0x51, 0xe7, 0xf2,
	0x56, 0x3b, 0x74, 0x30, 0x86, 0xcf, 0xcb, 0x67, 0xa1, 0xdb, 0xa9, 0x1f, 0xff, 0x58, 0xad, 0xf5,
	0x8c, 0x26, 0x58, 0xc1, 0xcb, 0xa6, 0x61, 0xb7, 0x48, 0x6a, 0x18, 0x1b, 0xc8, 0xca, 0x6d, 0x0f,
	0x7b, 0xae, 0xa4, 0xb5, 0xed, 0xe2, 0x46, 0x0c, 0x63, 0x39, 0xc8, 0xad, 0x71, 0xc7, 0x69, 0x3c,
	0xa7, 0x7d, 0x69, 0xea, 0x2d, 0x80, 0x55, 0x07, 0xdb, 0x16, 0xe1, 0xb5, 0x14, 0x4a, 0x2a, 0xf1,
	0x18, 0x22, 0x26, 0x2b, 0x04, 0xd2, 0xc2, 0x17, 0xe3, 0x2c, 0x89, 0x41, 0x73, 0xe3, 0x72, 0xa9,
	0x57, 0x7d, 0x06, 0x47, 0xc8, 0xd2, 0x9d, 0xd2, 0x59, 0xba, 0x5b, 0xb8, 0xb1, 0x67, 0x22, 0x56,
	0x67, 0xbf, 0xc8, 0x3a, 0x6e, 0x5a, 0xba, 0x7e, 0xc4, 0x84, 0x1c, 0xb4, 0x16, 0xda, 0xa8, 0xb3,
	0xd4, 0x5b, 0xb2, 0xc1, 0x67, 0x45, 0x8c, 0xdc, 0xc5, 0x57, 0xe3, 0x84, 0xcb, 0x88, 0x09, 0xde,
	0x1f, 0xb3, 0x1c, 0xb2, 0xb4, 0xb5, 0x68, 0xba, 0x5c, 0xa9, 0xc2, 0x4f, 0x4d, 0x74, 0xeb, 0xeb,
	0x22, 0xbe, 0x60, 0x20, 0xc8, 0x21, 0xae, 0x17, 0xc3, 0x25, 0x1b, 0xce, 0x29, 0x9c, 0x5e, 0xa4,
	0x77, 0xe7, 0x7f, 0x65, 0xe5, 0xcf, 0x08, 0xd6, 0x8e, 0xbe, 0xfd, 0xfa, 0xb4, 0xb0, 0x42, 0x96,
	0xa9, 0xeb, 0x60, 0x8a, 0x15, 0x92, 0xcf, 0x08, 0x37, 0xe7, 0xa6, 0x4c, 0xc2, 0x7f, 0x37, 0x77,
	0xed, 0xd9, 0xa3, 0xe7, 0xae, 0xb7, 0x54, 0xf7, 0x0c, 0xd5, 0x06, 0x59, 0x77, 0x52, 0x0d, 0x8b,
	0xe1, 0xca, 0x19, 0xcd, 0x17, 0x84, 0x9b, 0x73, 0x3b, 0x3a, 0x8b, 0xcf, 0x75, 0x04, 0x67, 0xf1,
	0x39, 0x97, 0x1f, 0x6c, 0x1b, 0x3e, 0x4a, 0x1e, 0x38, 0xf9, 0x74, 0xa9, 0xe9, 0x97, 0x17, 0x41,
	0xdf, 0xdb, 0x8b, 0xfa, 0xb0, 0xd3, 0x3d, 0x9e, 0xf8, 0xe8, 0x64, 0xe2, 0xa3, 0x9f, 0x13, 0x1f,
	0x7d, 0x9c, 0xfa, 0xb5, 0x93, 0xa9, 0x5f, 0xfb, 0x3e, 0xf5, 0x6b, 0x6f, 0xee, 0x0b, 0x99, 0x8e,
	0xb2, 0xdd, 0x70, 0x00, 0xd1, 0x9f, 0x96, 0xb3, 0xc7, 0xe1, 0xac, 0x7b, 0x9a, 0xc7, 0x5c, 0xef,
	0x36, 0xcc, 0x1f, 0xf8, 0xe1, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd9, 0x90, 0x18, 0x72, 0x4f,
	0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Info returns the immutable on-chain network identity.
	Info(ctx context.Context, in *QueryInfoRequest, opts ...grpc.CallOption) (*QueryInfoResponse, error)
	// ForkIsolation returns the peer-rejection policy in force.
	ForkIsolation(ctx context.Context, in *QueryForkIsolationRequest, opts ...grpc.CallOption) (*QueryForkIsolationResponse, error)
	// SigningDomain returns the exact domain-separation string used when signing
	// for a given purpose on this network.
	//
	// Clients and the Rust P2P layer must reproduce this string byte for byte.
	// Exposing it as a query means a client can assert agreement at runtime
	// instead of discovering a mismatch as an unexplained signature failure.
	SigningDomain(ctx context.Context, in *QuerySigningDomainRequest, opts ...grpc.CallOption) (*QuerySigningDomainResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Info(ctx context.Context, in *QueryInfoRequest, opts ...grpc.CallOption) (*QueryInfoResponse, error) {
	out := new(QueryInfoResponse)
	err := c.cc.Invoke(ctx, "/hashgram.network.v1.Query/Info", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ForkIsolation(ctx context.Context, in *QueryForkIsolationRequest, opts ...grpc.CallOption) (*QueryForkIsolationResponse, error) {
	out := new(QueryForkIsolationResponse)
	err := c.cc.Invoke(ctx, "/hashgram.network.v1.Query/ForkIsolation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) SigningDomain(ctx context.Context, in *QuerySigningDomainRequest, opts ...grpc.CallOption) (*QuerySigningDomainResponse, error) {
	out := new(QuerySigningDomainResponse)
	err := c.cc.Invoke(ctx, "/hashgram.network.v1.Query/SigningDomain", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Info returns the immutable on-chain network identity.
	Info(context.Context, *QueryInfoRequest) (*QueryInfoResponse, error)
	// ForkIsolation returns the peer-rejection policy in force.
	ForkIsolation(context.Context, *QueryForkIsolationRequest) (*QueryForkIsolationResponse, error)
	// SigningDomain returns the exact domain-separation string used when signing
	// for a given purpose on this network.
	//
	// Clients and the Rust P2P layer must reproduce this string byte for byte.
	// Exposing it as a query means a client can assert agreement at runtime
	// instead of discovering a mismatch as an unexplained signature failure.
	SigningDomain(context.Context, *QuerySigningDomainRequest) (*QuerySigningDomainResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Info(ctx context.Context, req *QueryInfoRequest) (*QueryInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Info not implemented")
}
func (*UnimplementedQueryServer) ForkIsolation(ctx context.Context, req *QueryForkIsolationRequest) (*QueryForkIsolationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ForkIsolation not implemented")
}
func (*UnimplementedQueryServer) SigningDomain(ctx context.Context, req *QuerySigningDomainRequest) (*QuerySigningDomainResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SigningDomain not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hashgram.network.v1.Query/Info",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Info(ctx, req.(*QueryInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ForkIsolation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryForkIsolationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ForkIsolation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hashgram.network.v1.Query/ForkIsolation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ForkIsolation(ctx, req.(*QueryForkIsolationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_SigningDomain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuerySigningDomainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).SigningDomain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hashgram.network.v1.Query/SigningDomain",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).SigningDomain(ctx, req.(*QuerySigningDomainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "hashgram.network.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Info",
			Handler:    _Query_Info_Handler,
		},
		{
			MethodName: "ForkIsolation",
			Handler:    _Query_ForkIsolation_Handler,
		},
		{
			MethodName: "SigningDomain",
			Handler:    _Query_SigningDomain_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hashgram/network/v1/query.proto",
}

func (m *QueryInfoRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryInfoRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryInfoRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryInfoResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryInfoResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryInfoResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Info.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryForkIsolationRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryForkIsolationRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryForkIsolationRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryForkIsolationResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryForkIsolationResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryForkIsolationResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Policy.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QuerySigningDomainRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QuerySigningDomainRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QuerySigningDomainRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Purpose) > 0 {
		i -= len(m.Purpose)
		copy(dAtA[i:], m.Purpose)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Purpose)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QuerySigningDomainResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QuerySigningDomainResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QuerySigningDomainResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.PreimageLayout) > 0 {
		i -= len(m.PreimageLayout)
		copy(dAtA[i:], m.PreimageLayout)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.PreimageLayout)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.NetworkMagic) > 0 {
		i -= len(m.NetworkMagic)
		copy(dAtA[i:], m.NetworkMagic)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.NetworkMagic)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Domain) > 0 {
		i -= len(m.Domain)
		copy(dAtA[i:], m.Domain)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Domain)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryInfoRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryInfoResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Info.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryForkIsolationRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryForkIsolationResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Policy.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QuerySigningDomainRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Purpose)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QuerySigningDomainResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Domain)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.NetworkMagic)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.PreimageLayout)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryInfoRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryInfoRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryInfoRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryInfoResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryInfoResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryInfoResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Info", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Info.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryForkIsolationRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryForkIsolationRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryForkIsolationRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryForkIsolationResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryForkIsolationResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryForkIsolationResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Policy", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Policy.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QuerySigningDomainRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QuerySigningDomainRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QuerySigningDomainRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Purpose", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Purpose = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QuerySigningDomainResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QuerySigningDomainResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QuerySigningDomainResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Domain", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Domain = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NetworkMagic", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NetworkMagic = append(m.NetworkMagic[:0], dAtA[iNdEx:postIndex]...)
			if m.NetworkMagic == nil {
				m.NetworkMagic = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PreimageLayout", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PreimageLayout = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
