// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: hashgram/identity/v1/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState is the x/identity genesis state.
type GenesisState struct {
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	// identities and devices are empty on a fresh chain.
	Identities       []RootIdentity    `protobuf:"bytes,2,rep,name=identities,proto3" json:"identities"`
	Devices          []Device          `protobuf:"bytes,3,rep,name=devices,proto3" json:"devices"`
	RecoveryRequests []RecoveryRequest `protobuf:"bytes,4,rep,name=recovery_requests,json=recoveryRequests,proto3" json:"recovery_requests"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f2e65e58c88be52, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetIdentities() []RootIdentity {
	if m != nil {
		return m.Identities
	}
	return nil
}

func (m *GenesisState) GetDevices() []Device {
	if m != nil {
		return m.Devices
	}
	return nil
}

func (m *GenesisState) GetRecoveryRequests() []RecoveryRequest {
	if m != nil {
		return m.RecoveryRequests
	}
	return nil
}

// Params configures the identity system.
type Params struct {
	// max_devices_per_identity bounds how many devices one identity may hold.
	//
	// A bound is necessary because every device is a signing key that other
	// users' clients must fetch and check; an unbounded set is both a state
	// growth vector and a way to make a client's verification work unbounded.
	MaxDevicesPerIdentity uint32 `protobuf:"varint,1,opt,name=max_devices_per_identity,json=maxDevicesPerIdentity,proto3" json:"max_devices_per_identity,omitempty"`
	// max_guardians bounds the recovery guardian set.
	MaxGuardians uint32 `protobuf:"varint,2,opt,name=max_guardians,json=maxGuardians,proto3" json:"max_guardians,omitempty"`
	// min_recovery_delay_blocks is the shortest recovery delay a user may
	// configure.
	//
	// A floor rather than a suggestion: the delay is the window in which a user
	// whose guardians have been socially engineered can notice and cancel, and
	// a user who sets it to zero has no such window.
	MinRecoveryDelayBlocks int64 `protobuf:"varint,3,opt,name=min_recovery_delay_blocks,json=minRecoveryDelayBlocks,proto3" json:"min_recovery_delay_blocks,omitempty"`
	// max_certificate_age_blocks bounds how far in the future a device
	// certificate's expiry may be set, so a certificate cannot become an
	// effectively permanent bearer authorisation.
	MaxCertificateAgeBlocks int64 `protobuf:"varint,4,opt,name=max_certificate_age_blocks,json=maxCertificateAgeBlocks,proto3" json:"max_certificate_age_blocks,omitempty"`
	// max_device_label_length and max_device_id_length bound client-supplied
	// strings.
	MaxDeviceLabelLength uint32 `protobuf:"varint,5,opt,name=max_device_label_length,json=maxDeviceLabelLength,proto3" json:"max_device_label_length,omitempty"`
	MaxDeviceIdLength    uint32 `protobuf:"varint,6,opt,name=max_device_id_length,json=maxDeviceIdLength,proto3" json:"max_device_id_length,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f2e65e58c88be52, []int{1}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetMaxDevicesPerIdentity() uint32 {
	if m != nil {
		return m.MaxDevicesPerIdentity
	}
	return 0
}

func (m *Params) GetMaxGuardians() uint32 {
	if m != nil {
		return m.MaxGuardians
	}
	return 0
}

func (m *Params) GetMinRecoveryDelayBlocks() int64 {
	if m != nil {
		return m.MinRecoveryDelayBlocks
	}
	return 0
}

func (m *Params) GetMaxCertificateAgeBlocks() int64 {
	if m != nil {
		return m.MaxCertificateAgeBlocks
	}
	return 0
}

func (m *Params) GetMaxDeviceLabelLength() uint32 {
	if m != nil {
		return m.MaxDeviceLabelLength
	}
	return 0
}

func (m *Params) GetMaxDeviceIdLength() uint32 {
	if m != nil {
		return m.MaxDeviceIdLength
	}
	return 0
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "hashgram.identity.v1.GenesisState")
	proto.RegisterType((*Params)(nil), "hashgram.identity.v1.Params")
}

func init() {
	proto.RegisterFile("hashgram/identity/v1/genesis.proto", fileDescriptor_7f2e65e58c88be52)
}

var fileDescriptor_7f2e65e58c88be52 = []byte{
	// 466 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0x4f, 0x6f, 0xd3, 0x30,
	0x18, 0x87, 0x9b, 0xb6, 0x14, 0xc9, 0xdb, 0x24, 0x66, 0x15, 0x16, 0x2a, 0x14, 0xa6, 0x4e, 0x48,
	0xbd, 0x90, 0x68, 0x43, 0x08, 0xf1, 0xe7, 0x42, 0x99, 0x54, 0x26, 0xed, 0x30, 0x85, 0x0b, 0xe2,
	0x12, 0xb9, 0xc9, 0x8b, 0x6b, 0x11, 0xc7, 0xc5, 0x76, 0xab, 0xf4, 0x5b, 0xf0, 0x41, 0xf8, 0x1c,
	0x68, 0xc7, 0x1d, 0x39, 0x21, 0xd4, 0x7e, 0x11, 0x14, 0xc7, 0x4e, 0x87, 0xd4, 0xdd, 0x12, 0xbf,
	0xcf, 0xf3, 0xf3, 0xfb, 0x5a, 0x2f, 0x1a, 0xce, 0x88, 0x9a, 0x51, 0x49, 0x78, 0xc4, 0x32, 0x28,
	0x34, 0xd3, 0xab, 0x68, 0x79, 0x1a, 0x51, 0x28, 0x40, 0x31, 0x15, 0xce, 0xa5, 0xd0, 0x02, 0xf7,
	0x1d, 0x13, 0x3a, 0x26, 0x5c, 0x9e, 0x0e, 0xfa, 0x54, 0x50, 0x61, 0x80, 0xa8, 0xfa, 0xaa, 0xd9,
	0xc1, 0xc9, 0xce, 0xbc, 0xc6, 0x33, 0xd0, 0xf0, 0x67, 0x1b, 0xed, 0x4f, 0xea, 0x2b, 0x3e, 0x69,
	0xa2, 0x01, 0xbf, 0x41, 0xbd, 0x39, 0x91, 0x84, 0x2b, 0xdf, 0x3b, 0xf6, 0x46, 0x7b, 0x67, 0x4f,
	0xc2, 0x5d, 0x57, 0x86, 0x57, 0x86, 0x19, 0x77, 0xaf, 0xff, 0x3c, 0x6d, 0xc5, 0xd6, 0xc0, 0x1f,
	0x11, 0xb2, 0x0c, 0x03, 0xe5, 0xb7, 0x8f, 0x3b, 0xa3, 0xbd, 0xb3, 0xe1, 0x6e, 0x3f, 0x16, 0x42,
	0x5f, 0xd8, 0x7f, 0x9b, 0x72, 0xcb, 0xc5, 0xef, 0xd0, 0xfd, 0x0c, 0x96, 0x2c, 0x05, 0xe5, 0x77,
	0x4c, 0xcc, 0x1d, 0x6d, 0x9c, 0x1b, 0xc8, 0x06, 0x38, 0x05, 0x7f, 0x46, 0x87, 0x12, 0x52, 0xb1,
	0x04, 0xb9, 0x4a, 0x24, 0x7c, 0x5f, 0x80, 0xd2, 0xca, 0xef, 0x9a, 0x9c, 0x67, 0x77, 0xb4, 0x63,
	0xf1, 0xb8, 0xa6, 0x6d, 0xe0, 0x03, 0xf9, 0xff, 0xb1, 0x1a, 0xfe, 0x6a, 0xa3, 0x5e, 0x3d, 0x3a,
	0x7e, 0x85, 0x7c, 0x4e, 0xca, 0xc4, 0xde, 0x99, 0xcc, 0x41, 0x26, 0x2e, 0xd1, 0x3c, 0xdd, 0x41,
	0xfc, 0x90, 0x93, 0xb2, 0x6e, 0x50, 0x5d, 0x81, 0x74, 0xd3, 0xe2, 0x13, 0x74, 0x50, 0x89, 0x74,
	0x41, 0x64, 0xc6, 0x48, 0x51, 0x3d, 0x54, 0x45, 0xef, 0x73, 0x52, 0x4e, 0xdc, 0x19, 0x7e, 0x8d,
	0x1e, 0x73, 0x56, 0x24, 0xcd, 0x18, 0x19, 0xe4, 0x64, 0x95, 0x4c, 0x73, 0x91, 0x7e, 0xab, 0x9e,
	0xc4, 0x1b, 0x75, 0xe2, 0x47, 0x9c, 0x15, 0xae, 0xef, 0xf3, 0xaa, 0x3c, 0x36, 0x55, 0xfc, 0x16,
	0x0d, 0xaa, 0xfc, 0x14, 0xa4, 0x66, 0x5f, 0x59, 0x4a, 0x34, 0x24, 0x84, 0x82, 0x73, 0xbb, 0xc6,
	0x3d, 0xe2, 0xa4, 0xfc, 0xb0, 0x05, 0xde, 0x53, 0xb0, 0xf2, 0x4b, 0x74, 0xb4, 0x9d, 0x2a, 0xc9,
	0xc9, 0x14, 0xf2, 0x24, 0x87, 0x82, 0xea, 0x99, 0x7f, 0xcf, 0xb4, 0xd9, 0x6f, 0x86, 0xba, 0xac,
	0x8a, 0x97, 0xa6, 0x86, 0x23, 0xd4, 0xbf, 0xa5, 0xb1, 0xcc, 0x39, 0x3d, 0xe3, 0x1c, 0x36, 0xce,
	0x45, 0x56, 0x0b, 0xe3, 0xc9, 0xf5, 0x3a, 0xf0, 0x6e, 0xd6, 0x81, 0xf7, 0x77, 0x1d, 0x78, 0x3f,
	0x36, 0x41, 0xeb, 0x66, 0x13, 0xb4, 0x7e, 0x6f, 0x82, 0xd6, 0x97, 0xe7, 0x94, 0xe9, 0xd9, 0x62,
	0x1a, 0xa6, 0x82, 0x47, 0xcd, 0x06, 0x37, 0x1f, 0xe5, 0x76, 0x99, 0xf5, 0x6a, 0x0e, 0x6a, 0xda,
	0x33, 0x7b, 0xfc, 0xe2, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x27, 0x70, 0x98, 0x6f, 0x3e, 0x03,
	0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.RecoveryRequests) > 0 {
		for iNdEx := len(m.RecoveryRequests) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.RecoveryRequests[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.Devices) > 0 {
		for iNdEx := len(m.Devices) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Devices[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Identities) > 0 {
		for iNdEx := len(m.Identities) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Identities[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MaxDeviceIdLength != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.MaxDeviceIdLength))
		i--
		dAtA[i] = 0x30
	}
	if m.MaxDeviceLabelLength != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.MaxDeviceLabelLength))
		i--
		dAtA[i] = 0x28
	}
	if m.MaxCertificateAgeBlocks != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.MaxCertificateAgeBlocks))
		i--
		dAtA[i] = 0x20
	}
	if m.MinRecoveryDelayBlocks != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.MinRecoveryDelayBlocks))
		i--
		dAtA[i] = 0x18
	}
	if m.MaxGuardians != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.MaxGuardians))
		i--
		dAtA[i] = 0x10
	}
	if m.MaxDevicesPerIdentity != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.MaxDevicesPerIdentity))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.Identities) > 0 {
		for _, e := range m.Identities {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.Devices) > 0 {
		for _, e := range m.Devices {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.RecoveryRequests) > 0 {
		for _, e := range m.RecoveryRequests {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.MaxDevicesPerIdentity != 0 {
		n += 1 + sovGenesis(uint64(m.MaxDevicesPerIdentity))
	}
	if m.MaxGuardians != 0 {
		n += 1 + sovGenesis(uint64(m.MaxGuardians))
	}
	if m.MinRecoveryDelayBlocks != 0 {
		n += 1 + sovGenesis(uint64(m.MinRecoveryDelayBlocks))
	}
	if m.MaxCertificateAgeBlocks != 0 {
		n += 1 + sovGenesis(uint64(m.MaxCertificateAgeBlocks))
	}
	if m.MaxDeviceLabelLength != 0 {
		n += 1 + sovGenesis(uint64(m.MaxDeviceLabelLength))
	}
	if m.MaxDeviceIdLength != 0 {
		n += 1 + sovGenesis(uint64(m.MaxDeviceIdLength))
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Identities", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Identities = append(m.Identities, RootIdentity{})
			if err := m.Identities[len(m.Identities)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Devices", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Devices = append(m.Devices, Device{})
			if err := m.Devices[len(m.Devices)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RecoveryRequests", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RecoveryRequests = append(m.RecoveryRequests, RecoveryRequest{})
			if err := m.RecoveryRequests[len(m.RecoveryRequests)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxDevicesPerIdentity", wireType)
			}
			m.MaxDevicesPerIdentity = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxDevicesPerIdentity |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxGuardians", wireType)
			}
			m.MaxGuardians = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxGuardians |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinRecoveryDelayBlocks", wireType)
			}
			m.MinRecoveryDelayBlocks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MinRecoveryDelayBlocks |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxCertificateAgeBlocks", wireType)
			}
			m.MaxCertificateAgeBlocks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxCertificateAgeBlocks |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxDeviceLabelLength", wireType)
			}
			m.MaxDeviceLabelLength = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxDeviceLabelLength |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxDeviceIdLength", wireType)
			}
			m.MaxDeviceIdLength = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxDeviceIdLength |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
