package cmd

import (
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/spf13/cobra"

	cmtjson "github.com/cometbft/cometbft/libs/json"
	cmttypes "github.com/cometbft/cometbft/types"
	dbm "github.com/cosmos/cosmos-db"

	"cosmossdk.io/log"

	simtestutil "github.com/cosmos/cosmos-sdk/testutil/sims"

	"github.com/hashgram/hashgram/app"
	hgparams "github.com/hashgram/hashgram/app/params"
	"github.com/hashgram/hashgram/cmd/hashgramctl/internal/hgconfig"
	"github.com/hashgram/hashgram/genesis"
)

// EnvFounderAddress is the environment variable the runbook tells the Founder
// to set.
const EnvFounderAddress = "GENESIS_FOUNDER_ADDRESS"

func cmdInitMainnetGenesis() *cobra.Command {
	var (
		founderAddress string
		moniker        string
		devnet         bool
		force          bool
		outputDir      string
	)

	cmd := &cobra.Command{
		Use:   "init-mainnet-genesis",
		Short: "Create the Hashgram Mainnet genesis file",
		Long: `Create the Hashgram Mainnet genesis file.

This is irreversible. The genesis file defines the network's permanent
identity: once other nodes have joined, its hash is what tells them they are
on Hashgram Mainnet, and it cannot be changed without creating a different
network.

The Founder PUBLIC address is required and cannot be generated by this
software. Create it on a machine that is not this server, and pass only the
public address:

  hashgramctl init-mainnet-genesis --founder-address hash1...

or set ` + EnvFounderAddress + ` in the environment.

The Founder private key must never be present on this machine. See
docs/FOUNDER_LAUNCH_RUNBOOK.md Part A.

Afterwards, record the printed GENESIS HASH somewhere outside this server.
It is what every future node and client uses to verify the network.`,
		Args: cobra.NoArgs,
		RunE: func(cmd *cobra.Command, _ []string) error {
			ctx, cancel := commandContext()
			defer cancel()
			_ = ctx

			if founderAddress == "" {
				founderAddress = os.Getenv(EnvFounderAddress)
			}
			if founderAddress == "" {
				return fmt.Errorf(
					"the Founder PUBLIC address is required.\n\n"+
						"  hashgramctl init-mainnet-genesis --founder-address hash1...\n\n"+
						"or set %s in the environment.\n\n"+
						"This software will not invent the address. Create the Founder wallet on a\n"+
						"machine that is not this server and supply only the public address; see\n"+
						"docs/FOUNDER_LAUNCH_RUNBOOK.md Part A.",
					EnvFounderAddress)
			}

			// Build the application once to obtain the real codec and the
			// real per-module defaults, so nothing is omitted and nothing is
			// hand-transcribed.
			tempApp := app.NewHashgramApp(
				log.NewNopLogger(), dbm.NewMemDB(), nil, true,
				simtestutil.NewAppOptionsWithFlagHome(paths.NodeHome),
			)

			genesisTime := time.Now().UTC()
			result, err := genesis.Build(tempApp.AppCodec(), tempApp.DefaultGenesis(), genesis.Config{
				FounderAddress: founderAddress,
				Devnet:         devnet,
				GenesisTime:    genesisTime,
			})
			if err != nil {
				return err
			}

			// Show the operator exactly what will be created, before creating
			// it. §69 requires this summary and an explicit confirmation.
			printGenesisSummary(cmd.OutOrStdout(), result, founderAddress, devnet)

			word := "CREATE MAINNET"
			if devnet {
				word = "CREATE DEVNET"
			}
			if err := confirm(
				"\nThis creates a permanent network identity and cannot be undone.",
				word); err != nil {
				return err
			}

			appState, err := json.MarshalIndent(result.AppState, "", "  ")
			if err != nil {
				return err
			}

			doc := &cmttypes.GenesisDoc{
				GenesisTime:     genesisTime,
				ChainID:         result.ChainID,
				InitialHeight:   1,
				ConsensusParams: consensusParams(),
				AppState:        appState,
			}
			if err := doc.ValidateAndComplete(); err != nil {
				return fmt.Errorf("the assembled genesis document is invalid: %w", err)
			}

			target := paths.GenesisFile()
			if outputDir != "" {
				target = filepath.Join(outputDir, "genesis.json")
			}
			if fileExists(target) && !force {
				return fmt.Errorf(
					"%s already exists.\n\n"+
						"Refusing to overwrite an existing genesis file: doing so would silently\n"+
						"change this node's network identity. Move it aside first, or pass --force\n"+
						"if you are certain.", target)
			}

			raw, err := cmtjson.MarshalIndent(doc, "", "  ")
			if err != nil {
				return err
			}
			if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
				return err
			}
			if err := os.WriteFile(target, raw, 0o644); err != nil {
				return err
			}

			// The genesis hash is taken over the exact bytes on disk, so that
			// `sha256sum genesis.json` gives the same answer.
			onDisk, err := os.ReadFile(target)
			if err != nil {
				return err
			}
			genesisHash := hgparams.ComputeGenesisHash(onDisk)

			identity := hgparams.MainnetIdentity(genesisHash)
			if devnet {
				identity = hgparams.DevnetIdentity(genesisHash)
			}

			network := hgconfig.Network{
				NetworkName:          identity.NetworkName,
				NetworkID:            identity.NetworkID,
				ChainID:              identity.ChainID,
				NetworkMagic:         string(identity.NetworkMagic[:]),
				ProtocolMajorVersion: identity.ProtocolMajorVersion,
				GenesisHash:          genesisHash,
				GenesisTime:          genesisTime.Format(time.RFC3339),
				CreatedBy:            "hashgramctl init-mainnet-genesis",
			}
			if err := hgconfig.SaveNetwork(paths, network, force); err != nil {
				return err
			}

			printGenesisResult(cmd.OutOrStdout(), target, genesisHash, identity, moniker)
			return nil
		},
	}

	cmd.Flags().StringVar(&founderAddress, "founder-address", "",
		"the Founder PUBLIC Hashgram address (hash1...); required")
	cmd.Flags().StringVar(&moniker, "moniker", "genesis-full", "node moniker")
	cmd.Flags().BoolVar(&devnet, "devnet", false,
		"create a DEVNET ONLY network instead of Mainnet")
	cmd.Flags().BoolVar(&force, "force", false,
		"overwrite an existing genesis file and network configuration")
	cmd.Flags().StringVar(&outputDir, "output-dir", "",
		"write genesis.json here instead of the node home")

	return cmd
}

func printGenesisSummary(w io.Writer, r *genesis.Result, founderAddress string, devnet bool) {
	banner := "HASHGRAM MAINNET"
	if devnet {
		banner = "HASHGRAM DEVNET  (DEVNET ONLY - NOT MAINNET)"
	}

	fmt.Fprintf(w, "\n%s\n", strings.Repeat("=", 74))
	fmt.Fprintf(w, "  %s\n", banner)
	fmt.Fprintf(w, "%s\n\n", strings.Repeat("=", 74))

	fmt.Fprintf(w, "  Network        %s\n", r.NetworkID)
	fmt.Fprintf(w, "  Chain          %s\n", r.ChainID)
	fmt.Fprintf(w, "  Native coin    %s (base denomination %s, 1 %s = %d %s)\n",
		hgparams.HumanCoinDenom, hgparams.BaseCoinDenom,
		hgparams.HumanCoinDenom, hgparams.MicroUnit, hgparams.BaseCoinDenom)
	fmt.Fprintf(w, "  Total supply   %s %s\n\n",
		commas(hgparams.MaxSupplyHash), hgparams.HumanCoinDenom)

	fmt.Fprintf(w, "  GENESIS DISTRIBUTION\n")
	fmt.Fprintf(w, "  %s\n", strings.Repeat("-", 70))
	for _, a := range r.Allocations {
		amountHash := a.Amount.AmountOf(hgparams.BaseCoinDenom).QuoRaw(hgparams.MicroUnit)
		pct := float64(amountHash.Int64()) / float64(hgparams.MaxSupplyHash) * 100

		fmt.Fprintf(w, "  %-16s %18s HASH  %5.2f%%\n",
			a.Name, commasStr(amountHash.String()), pct)
		fmt.Fprintf(w, "  %-16s %s\n", "", a.Address)
		if !a.Vesting.IsZero() {
			vestHash := a.Vesting.AmountOf(hgparams.BaseCoinDenom).QuoRaw(hgparams.MicroUnit)
			fmt.Fprintf(w, "  %-16s of which %s HASH vests; the remainder is spendable at genesis\n",
				"", commasStr(vestHash.String()))
		}
	}
	fmt.Fprintf(w, "  %s\n", strings.Repeat("-", 70))
	fmt.Fprintf(w, "  %-16s %18s HASH  100.00%%\n\n",
		"TOTAL", commas(hgparams.MaxSupplyHash))

	fmt.Fprintf(w, "  FOUNDER\n")
	fmt.Fprintf(w, "  Allocation     %s HASH (20%% of supply)\n", commas(hgparams.AllocFounderHash))
	fmt.Fprintf(w, "  Unlocked       %s HASH at genesis\n", commas(hgparams.FounderUnlockedAtGenesisHash))
	fmt.Fprintf(w, "  Vesting        %s HASH over %d years (%d monthly periods)\n",
		commas(hgparams.FounderVestedHash), hgparams.FounderVestingYears, hgparams.FounderVestingPeriods)
	fmt.Fprintf(w, "  Revenue share  %d basis points (1%%) of qualifying protocol fee revenue\n",
		hgparams.FounderFeeBasisPoints)
	fmt.Fprintf(w, "                 This is NOT a tax on transfers. Sending 100 HASH delivers 100 HASH.\n")
	fmt.Fprintf(w, "  Beneficiary    %s\n", founderAddress)
	fmt.Fprintf(w, "                 A PUBLIC address. No Founder private key is stored on this server.\n\n")

	fmt.Fprintf(w, "  WELCOME POOL\n")
	fmt.Fprintf(w, "  Reserved       %s HASH\n", commas(hgparams.WelcomePoolHash))
	fmt.Fprintf(w, "  Attestors      none registered; no welcome reward is claimable until\n")
	fmt.Fprintf(w, "                 governance registers one. Creating a key earns nothing.\n\n")

	fmt.Fprintf(w, "  INITIAL VALIDATORS\n")
	fmt.Fprintf(w, "  Count          0 in this genesis file\n")
	fmt.Fprintf(w, "                 Add validator gentxs with 'hashgramd genesis gentx' and\n")
	fmt.Fprintf(w, "                 'hashgramd genesis collect-gentxs' before starting.\n")
}

func printGenesisResult(w io.Writer, path, genesisHash string, identity hgparams.NetworkIdentity, moniker string) {
	fmt.Fprintf(w, "\n%s\n", strings.Repeat("=", 74))
	fmt.Fprintf(w, "  GENESIS CREATED\n")
	fmt.Fprintf(w, "%s\n\n", strings.Repeat("=", 74))

	fmt.Fprintf(w, "  File           %s\n", path)
	fmt.Fprintf(w, "  Network        %s\n", identity.NetworkName)
	fmt.Fprintf(w, "  Network id     %s\n", identity.NetworkID)
	fmt.Fprintf(w, "  Chain id       %s\n", identity.ChainID)
	fmt.Fprintf(w, "  Network magic  %s\n", string(identity.NetworkMagic[:]))
	fmt.Fprintf(w, "  Protocol       v%d\n\n", identity.ProtocolMajorVersion)

	fmt.Fprintf(w, "  GENESIS HASH\n")
	fmt.Fprintf(w, "  %s\n\n", genesisHash)

	fmt.Fprintf(w, "  This hash is the network's identity. Record it somewhere outside this\n")
	fmt.Fprintf(w, "  server. Every future node and client uses it to verify they are on the\n")
	fmt.Fprintf(w, "  same network, and a fork with a different genesis will be rejected.\n\n")
	fmt.Fprintf(w, "  Verify it yourself at any time:\n")
	fmt.Fprintf(w, "    sha256sum %s\n\n", path)

	fmt.Fprintf(w, "  NEXT STEPS\n")
	fmt.Fprintf(w, "    1. Back up the genesis file off this server.\n")
	fmt.Fprintf(w, "    2. Create the validator gentx:\n")
	fmt.Fprintf(w, "         hashgramd genesis gentx <key-name> <amount>uhash --chain-id %s\n", identity.ChainID)
	fmt.Fprintf(w, "         hashgramd genesis collect-gentxs\n")
	fmt.Fprintf(w, "    3. Run the pre-launch checks:\n")
	fmt.Fprintf(w, "         hashgramctl mainnet-preflight\n")
	fmt.Fprintf(w, "    4. Start the node:\n")
	fmt.Fprintf(w, "         hashgramctl start\n")
	fmt.Fprintf(w, "         hashgramctl chain-status\n\n")
}

// consensusParams returns the CometBFT consensus parameters for genesis.
func consensusParams() *cmttypes.ConsensusParams {
	p := cmttypes.DefaultConsensusParams()

	// A 5 MiB block cap. Hashgram deliberately keeps media and messages off
	// chain, so blocks carry transactions rather than payloads; a larger cap
	// would only make it easier to bloat state.
	p.Block.MaxBytes = 5 * 1024 * 1024
	p.Block.MaxGas = 100_000_000

	// Evidence must remain submittable for long enough that a double-sign is
	// still punishable after a realistic detection delay.
	p.Evidence.MaxAgeNumBlocks = 200_000
	p.Evidence.MaxAgeDuration = 48 * time.Hour
	p.Evidence.MaxBytes = 1024 * 1024

	// ed25519 only for consensus keys, matching CometBFT's supported set.
	p.Validator.PubKeyTypes = []string{cmttypes.ABCIPubKeyTypeEd25519}

	return p
}

// download fetches a URL into memory, for join-mainnet.
func download(url string) ([]byte, error) {
	client := &http.Client{Timeout: 60 * time.Second}
	resp, err := client.Get(url)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("%s returned HTTP %d", url, resp.StatusCode)
	}
	// Bounded read: a genesis file is small, and an unbounded read from a
	// URL an operator was given is an easy way to exhaust memory.
	return io.ReadAll(io.LimitReader(resp.Body, 64*1024*1024))
}

func commas(n int64) string { return commasStr(fmt.Sprintf("%d", n)) }

func commasStr(s string) string {
	if len(s) <= 3 {
		return s
	}
	out := make([]byte, 0, len(s)+len(s)/3)
	lead := len(s) % 3
	if lead > 0 {
		out = append(out, s[:lead]...)
	}
	for i := lead; i < len(s); i += 3 {
		if len(out) > 0 {
			out = append(out, ',')
		}
		out = append(out, s[i:i+3]...)
	}
	return string(out)
}
